/* Brisket's Crossing: original frontier art, shared arcade sound and settings. */
(function(){'use strict';
 const M=BrisketModel,$=id=>document.getElementById(id),canvas=$('sea'),ctx=canvas.getContext('2d'),KEY='briskets-crossing-save-v1',VERSION='0.1.0';
 Arcade.validators[KEY]=o=>!!o&&o.v===1&&o.game==='briskets-crossing'&&Array.isArray(o.scores);
 const raw=Arcade.load(KEY),valid=Arcade.validators[KEY](raw),save={v:1,game:'briskets-crossing',scores:M.scores(valid?raw.scores:[]),sound:valid&&[0,1,2].includes(raw.sound)?raw.sound:0,scanlines:!!(valid&&raw.scanlines===true)};
 let state=null,demo=M.create(1,17),last=0,tapAt=null,padPause=false,padMove=false,entry=0,entries=[],uiPhase='title';
 M.ready(demo);const keys=new Set(),pointers=new Map(),reduce=Settings.reduced();
 function persist(){return Arcade.save(KEY,save);}
 function scan(){document.body.classList.toggle('scanlines',save.scanlines&&!reduce);}scan();
 const audio=ArcadeSound.create({mode:()=>save.sound,setMode:v=>{save.sound=v;persist();},button:()=>$('sound'),musicKey:()=>state&&state.phase==='playing'&&!state.paused?'cross':null,tracks:{cross:{bpm:104,lead:'square',mel:'D4 F4 A4 . G4 F4 D4 . C4 D4 F4 . E4 . D4 .',bass:'D2 . D2 . A2 . A2 . C2 . C2 . D2 . D2 .',drum:'k . h s . h k .'}}});
 $('sound').addEventListener('click',()=>audio.cycle());audio.render();
 const settings=Settings.create({mount:'#settingsMount',rows:[{label:'Sound',options:[[0,'Off'],[1,'Effects'],[2,'Effects and music']],get:()=>save.sound,set:v=>{save.sound=v;persist();audio.render();audio.sfx('select');}},{label:'Scanlines',options:[[false,'Off'],[true,'On']],get:()=>save.scanlines,set:v=>{save.scanlines=v;scan();persist();},note:'A soft cabinet texture. Hidden with reduced motion.'}]});
 if(window.Feedback)Feedback.register("Brisket's Crossing",VERSION,()=>state?'player '+(state.active+1)+' of '+state.players.length+', run '+M.current(state).round+', '+M.current(state).score+' points':'title screen');
 settings.button.addEventListener('click',()=>{clearInput();if(state&&state.phase==='playing')pause();});
 function clearInput(){keys.clear();pointers.clear();tapAt=null;}
 function table(){return '<table class="scores"><caption>Crossing high scores</caption><tbody>'+(save.scores.length?save.scores.map((r,i)=>'<tr><td>'+String(i+1).padStart(2,'0')+'</td><th scope="row">'+r.name+'</th><td>'+String(r.score).padStart(6,'0')+'</td></tr>').join(''):'<tr><td>No scores yet. Get the lanterns across.</td></tr>')+'</tbody></table>';}
 function modal(title,body){clearInput();$('panel').innerHTML='<p class="eyebrow">PELL\'S CROSSING</p><h2 id="panelTitle">'+title+'</h2>'+body;$('curtain').hidden=false;canvas.inert=true;$('pause').hidden=true;document.querySelector('.touch-controls').inert=true;const first=$('panel').querySelector('button,input');if(first)first.focus();}
 function buttons(){return '<div class="actions"><button data-start="1">One player</button><button class="secondary" data-start="2">Two players · take turns</button></div>';}
 function title(){uiPhase='title';state=null;modal("Brisket's Crossing",'<p>Help Pell\'s mule Brisket carry lanterns across the wagon road and the log river.</p>'+buttons()+table()+'<p class="fine">Three lives. 10 points a step toward the far bank, 100 plus the time left for each lantern, 200 when all five are lit. The next run is faster.<br>Demo plays behind this window.</p>');}
 function start(count){state=M.create(count,(Date.now()>>>0));entries=[];entry=0;readyPanel();}
 function readyPanel(){uiPhase='ready';modal('Player '+(state.active+1)+' · get ready','<p>'+(state.players.length===2?'Each player has their own score and three lives. Player 2 starts when Player 1 finishes.':'Hop the roads, ride the logs, and light every post.')+'</p><div class="actions"><button data-launch>Lead Brisket out</button></div>');}
 function launch(){uiPhase='playing';M.ready(state);state.paused=false;$('curtain').hidden=true;canvas.inert=false;document.querySelector('.touch-controls').inert=false;$('pause').hidden=false;canvas.focus();clearInput();last=performance.now();}
 function pause(){if(!state||state.phase!=='playing')return;state.paused=true;modal('Crossing paused','<div class="actions"><button data-resume>Resume</button><button class="secondary" data-title>Finish this run</button></div><p class="fine">Unfinished runs do not enter the high-score table.</p>');}
 function finish(){uiPhase='over';entries=state.players.map((p,i)=>({player:i+1,score:p.score})).filter(p=>p.score>0&&(save.scores.length<5||p.score>save.scores[save.scores.length-1].score));entry=0;nextScore();}
 function nextScore(){if(entry>=entries.length){modal('The lanterns are in','<p>'+state.players.map((p,i)=>'Player '+(i+1)+': '+p.score+' points').join(' · ')+'</p>'+table()+buttons());return;}const p=entries[entry];modal('Player '+p.player+' · high score','<p>'+p.score+' points. Enter three initials for the crossing board.</p><form id="initialForm"><label for="initials">Your initials</label><input id="initials" name="initials" maxlength="3" pattern="[A-Za-z0-9]{3}" value="AAA" autocomplete="off" autocapitalize="characters" required aria-describedby="initialHint"><p id="initialHint" class="fine">Three letters or numbers. Saved on this device.</p><div class="actions"><button type="submit">Keep score</button><button type="button" class="secondary" data-skip>Skip</button></div></form>');$('initials').focus();$('initials').select();$('initialForm').addEventListener('submit',e=>{e.preventDefault();if(!$('initialForm').checkValidity())return;save.scores=M.record(save.scores,$('initials').value,p.score);const kept=persist();if(kept)Arcade.report('briskets-crossing',{summary:'Best: '+save.scores[0].score+' points',detail:"Brisket's Crossing high scores"});entry++;nextScore();if(!kept)$('notice').textContent='Score kept for this visit. This browser could not save it.';});}
 $('panel').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.start)start(Number(b.dataset.start));else if(b.hasAttribute('data-launch')||b.hasAttribute('data-resume'))launch();else if(b.hasAttribute('data-title'))title();else if(b.hasAttribute('data-skip')){entry++;nextScore();}});
 $('pause').addEventListener('click',pause);
 canvas.addEventListener('pointerdown',e=>{if(!state||state.paused||state.phase!=='playing')return;const r=canvas.getBoundingClientRect();tapAt={x:(e.clientX-r.left)/r.width*M.W,y:(e.clientY-r.top)/r.height*M.H};});
 const gameKey=k=>['arrowleft','arrowright','arrowup','arrowdown','a','d','w','s',' '].includes(k);
 window.addEventListener('keydown',e=>{if(e.target.closest&&e.target.closest('input,button,a,select,textarea,.arc-set-bg'))return;const k=e.key.toLowerCase();if(k==='p'||k==='escape'){e.preventDefault();if(state&&state.paused)launch();else pause();return;}if(gameKey(k)&&state&&state.phase==='playing'&&!state.paused){e.preventDefault();keys.add(k);}});
 window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pause();}});
 document.querySelectorAll('[data-hold]').forEach(b=>{b.addEventListener('pointerdown',e=>{if(!state||state.paused||state.phase!=='playing')return;e.preventDefault();try{b.setPointerCapture(e.pointerId);}catch(_){}pointers.set(e.pointerId,b.dataset.hold);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,e=>pointers.delete(e.pointerId));b.addEventListener('keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();keys.add('touch-'+b.dataset.hold);}});b.addEventListener('keyup',()=>keys.delete('touch-'+b.dataset.hold));});
 function axis(){const held=v=>[...pointers.values()].includes(v)||keys.has('touch-'+v);let dx=(keys.has('arrowright')||keys.has('d')||held('right')?1:0)-(keys.has('arrowleft')||keys.has('a')||held('left')?1:0),dy=(keys.has('arrowdown')||keys.has('s')||held('down')?1:0)-(keys.has('arrowup')||keys.has('w')||keys.has(' ')||held('up')?1:0);const pad=[...(navigator.getGamepads?navigator.getGamepads():[])].find(p=>p&&p.connected);if(pad){const press=i=>!!(pad.buttons[i]&&pad.buttons[i].pressed),x=pad.axes[0]||0,y=pad.axes[1]||0;if(Math.abs(x)>.45)dx=x>0?1:-1;if(Math.abs(y)>.45)dy=y>0?1:-1;if(press(14))dx=-1;if(press(15))dx=1;if(press(12))dy=-1;if(press(13))dy=1;if(press(0))dy=-1;}if(tapAt&&state){const pose=M.pose(M.current(state)),cx=pose.x/M.COLS*M.W,cy=(pose.y+.5)/M.ROWS*M.H,adx=tapAt.x-cx,ady=tapAt.y-cy;if(Math.abs(adx)>Math.abs(ady)){dx=adx>8?1:adx<-8?-1:0;dy=0;}else{dy=ady>8?1:ady<-8?-1:0;dx=0;}tapAt=null;}if(dx&&dy)dx=0;return {dx,dy};}
 function menuPad(){const pad=[...(navigator.getGamepads?navigator.getGamepads():[])].find(p=>p&&p.connected);if(!pad){padPause=false;padMove=false;return;}const press=i=>!!pad.buttons[i]?.pressed,settingsOpen=!!document.querySelector('.arc-set-bg:not([hidden])');const action=press(9)||(!$('curtain').hidden&&press(0)),move=!$('curtain').hidden&&(press(12)||press(13)||press(14)||press(15)||Math.abs(pad.axes[1]||0)>.55);if(!settingsOpen){if(move&&!padMove){const buttons=[...$('panel').querySelectorAll('button')],index=buttons.indexOf(document.activeElement),back=press(12)||press(14)||(pad.axes[1]||0)<-.55;buttons[(index+(back?-1:1)+buttons.length)%buttons.length]?.focus();}if(action&&!padPause){if($('curtain').hidden)pause();else{const active=document.activeElement,b=$('panel').contains(active)&&active.tagName==='BUTTON'?active:$('panel').querySelector('button');b?.click();}}}padPause=action;padMove=move;}
 function hud(s,isDemo){const p=M.current(s);$('playerLabel').textContent=isDemo?'DEMO · PRESS START':'PLAYER '+(s.active+1);$('score').textContent=String(p.score).padStart(6,'0');$('best').textContent=String(save.scores[0]?.score||0).padStart(6,'0');$('wave').textContent='RUN '+String(p.round).padStart(2,'0');$('lives').textContent='◆ '.repeat(Math.max(0,p.lives)).trim();$('lives').setAttribute('aria-label',p.lives+' lives');}
 function covers(left,width,point){const a=(left%M.COLS+M.COLS)%M.COLS,b=a+width;if(b<=M.COLS)return point>=a&&point<b;return point>=a||point<b-M.COLS;}
 function demoInput(s){const p=M.current(s);if(p.hop>0||p.clearing>0||Math.random()>.12)return {};const y=p.y-1;if(y<0)return {dx:Math.random()<.5?-1:1};const lane=p.lanes.find(l=>l.y===y),x=Math.round(p.x-.5)+.5;if(!lane)return {dy:-1};if(lane.kind==='road'&&lane.items.some(it=>covers(it.x,it.w,x)))return Math.random()<.5?{dx:-1}:{dx:1};if(lane.kind==='river'&&!lane.items.some(it=>covers(it.x,it.w,x)))return {};return {dy:-1};}
 function mule(x,y,t){const bob=reduce?0:Math.round(Math.sin(t*8)*1);ctx.fillStyle='#5c3a28';ctx.fillRect(x-7,y-4+bob,5,8);ctx.fillRect(x+3,y-4+bob,5,8);ctx.fillStyle='#8a5a32';ctx.fillRect(x-8,y-14+bob,16,12);ctx.fillStyle='#c4a574';ctx.fillRect(x-3,y-16+bob,6,4);ctx.fillStyle='#3a2418';ctx.fillRect(x-7,y-20+bob,3,6);ctx.fillRect(x+4,y-20+bob,3,6);ctx.fillStyle='#f6d275';ctx.fillRect(x+6,y-12+bob,4,5);ctx.fillStyle='#fff2c0';ctx.fillRect(x+7,y-11+bob,2,2);}
 function draw(s){const r=canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.setTransform(w/M.W,0,0,h/M.H,0,0);const p=M.current(s),t=s.elapsed,cw=M.W/M.COLS,ch=M.H/M.ROWS;
  ctx.fillStyle='#243044';ctx.fillRect(0,0,M.W,M.H);
  for(let y=0;y<M.ROWS;y++){const top=y*ch,kind=M.laneKind(y);
   if(kind==='home'||kind==='start'||kind==='safe'){ctx.fillStyle=kind==='safe'?'#4a6741':'#3d5c3a';ctx.fillRect(0,top,M.W,ch);ctx.fillStyle='#2f4a30';for(let i=0;i<M.COLS;i++)if((i+y)%2)ctx.fillRect(i*cw,top+ch-6,cw,4);}
   else if(kind==='road'){ctx.fillStyle='#6b5344';ctx.fillRect(0,top,M.W,ch);ctx.fillStyle='#8a7360';ctx.fillRect(0,top+ch*.45,M.W,3);}
   else {ctx.fillStyle='#1b4550';ctx.fillRect(0,top,M.W,ch);ctx.fillStyle='#246070';for(let i=0;i<8;i++)ctx.fillRect((i*90+(reduce?0:t*12)+y*20)%M.W,top+8+(i%3)*12,28,3);}
  }
  for(const home of p.homes){const x=home.x*cw,y=ch*.15;ctx.fillStyle='#5c4632';ctx.fillRect(x-8,y+10,16,18);ctx.fillStyle=home.filled?'#f6d275':'#3a342c';ctx.fillRect(x-3,y,6,12);if(home.filled){ctx.fillStyle='#fff2c0';ctx.fillRect(x-1,y+2,2,4);}}
  function drawTraffic(lane,it){const paint=x=>{const y=lane.y*ch+6,ww=it.w*cw;ctx.fillStyle=lane.kind==='road'?'#c4a574':'#6d4c32';ctx.fillRect(x,y,ww,ch-14);if(lane.kind==='road'){ctx.fillStyle='#3a2418';ctx.fillRect(x+4,y+4,ww-8,8);ctx.fillStyle='#2a2a2a';ctx.fillRect(x+2,y+ch-20,6,6);ctx.fillRect(x+ww-8,y+ch-20,6,6);}else{ctx.fillStyle='#8a6848';ctx.fillRect(x,y+4,ww,5);}};paint(it.x*cw);if(it.x+it.w>M.COLS)paint((it.x-M.COLS)*cw);}
  for(const lane of p.lanes)for(const it of lane.items)drawTraffic(lane,it);
  const pose=M.pose(p);mule(pose.x*cw,pose.y*ch+ch*.55,t);
  if(p.clearing>0){ctx.fillStyle='#f6d275';ctx.font='bold 22px monospace';ctx.textAlign='center';ctx.fillText('LANTERNS LIT',M.W/2,M.H*.45);}
  const clock=Math.max(0,p.time/M.plan(p.round).time);ctx.fillStyle='#1a120c';ctx.fillRect(18,M.H-16,120,6);ctx.fillStyle=clock<.25?'#e07050':'#f6d275';ctx.fillRect(18,M.H-16,120*clock,6);
 }
 function frame(now){const dt=Math.min(.08,Math.max(0,(now-last)/1000));last=now;menuPad();const run=s=>{if(s.phase!=='playing')return;M.advance(s,reduce?0:dt,s===demo?demoInput(s):axis());for(const e of s.events)audio.sfx(e==='hop'?'blip':e==='hit'?'hit':e==='lantern'?'coin':e==='clear'||e==='round'||e==='life'?'level':'select');};if(!state){if(demo.phase!=='playing'){demo=M.create(1,17);M.ready(demo);}run(demo);draw(demo);hud(demo,true);}else{if(state.phase==='playing'&&!state.paused)run(state);if(state.phase==='ready'&&uiPhase!=='ready')readyPanel();else if(state.phase==='over'&&uiPhase!=='over')finish();draw(state);hud(state,false);}requestAnimationFrame(frame);}
 title();requestAnimationFrame(frame);
 if(['localhost','127.0.0.1','[::1]'].includes(location.hostname))window.__brisket={M,get state(){return state;},save,start,launch,pause,title,finish};
})();
