/* Lighthouse Watch: original Saltmarsh lighthouse art, shared arcade sound and settings. */
(function(){'use strict';
 const M=WatchModel,$=id=>document.getElementById(id),canvas=$('sea'),ctx=canvas.getContext('2d'),KEY='lighthouse-watch-save-v1';
 Arcade.validators[KEY]=o=>!!o&&o.v===1&&o.game==='lighthouse-watch'&&Array.isArray(o.scores);
 const raw=Arcade.load(KEY),valid=Arcade.validators[KEY](raw),save={v:1,game:'lighthouse-watch',scores:M.scores(valid?raw.scores:[]),sound:valid&&[0,1,2].includes(raw.sound)?raw.sound:0,scanlines:!!(valid&&raw.scanlines===true)};
 let state=null,demo=M.create(1,31),last=0,queuedFire=false,tapAt=null,padPause=false,padMove=false,entry=0,entries=[],uiPhase='title';
 M.ready(demo);const keys=new Set(),pointers=new Map(),reduce=Settings.reduced();
 function persist(){return Arcade.save(KEY,save);}
 function scan(){document.body.classList.toggle('scanlines',save.scanlines&&!reduce);}scan();
 const audio=ArcadeSound.create({mode:()=>save.sound,setMode:v=>{save.sound=v;persist();},button:()=>$('sound'),musicKey:()=>state&&state.phase==='playing'&&!state.paused?'watch':null,tracks:{watch:{bpm:92,lead:'square',mel:'A4 . C5 . E5 . D5 C5 A4 . G4 . A4 . . .',bass:'A2 . A2 . F2 . F2 . G2 . G2 . E2 . E2 .',drum:'k . . h s . h .'}}});
 $('sound').addEventListener('click',()=>audio.cycle());audio.render();
 const settings=Settings.create({mount:'#settingsMount',rows:[{label:'Sound',options:[[0,'Off'],[1,'Effects'],[2,'Effects and music']],get:()=>save.sound,set:v=>{save.sound=v;persist();audio.render();audio.sfx('select');}},{label:'Scanlines',options:[[false,'Off'],[true,'On']],get:()=>save.scanlines,set:v=>{save.scanlines=v;scan();persist();},note:'A soft cabinet texture. Hidden with reduced motion.'}]});
 settings.button.addEventListener('click',()=>{clearInput();if(state&&state.phase==='playing')pause();});
 function clearInput(){keys.clear();pointers.clear();queuedFire=false;tapAt=null;}
 function table(){return '<table class="scores"><caption>Lighthouse high scores</caption><tbody>'+(save.scores.length?save.scores.map((r,i)=>'<tr><td>'+String(i+1).padStart(2,'0')+'</td><th scope="row">'+r.name+'</th><td>'+String(r.score).padStart(6,'0')+'</td></tr>').join(''):'<tr><td>No scores yet. Keep the boats safe.</td></tr>')+'</tbody></table>';}
 function modal(title,body){clearInput();$('panel').innerHTML='<p class="eyebrow">SALTMARSH LIGHTHOUSE</p><h2 id="panelTitle">'+title+'</h2>'+body;$('curtain').hidden=false;canvas.inert=true;$('pause').hidden=true;document.querySelector('.touch-controls').inert=true;const first=$('panel').querySelector('button,input');if(first)first.focus();}
 function buttons(){return '<div class="actions"><button data-start="1">One player</button><button class="secondary" data-start="2">Two players · take turns</button></div>';}
 function title(){uiPhase='title';state=null;modal('Lighthouse Watch','<p>Storm sparks are falling on the harbour boats. Aim the lighthouse beam and burst them in the sky.</p>'+buttons()+table()+'<p class="fine">Four boats per player. 25 points a spark, 100 for each boat still afloat at dawn. A lost boat is rebuilt every third night.<br>Demo plays behind this window.</p>');}
 function start(count){state=M.create(count,(Date.now()>>>0));entries=[];entry=0;readyPanel();}
 function readyPanel(){uiPhase='ready';modal('Player '+(state.active+1)+' · get ready','<p>'+(state.players.length===2?'Each player has their own score and four boats. Player 2 starts when Player 1 finishes.':'Burst the sparks before they reach the boats.')+'</p><div class="actions"><button data-launch>Light the beam</button></div>');}
 function launch(){uiPhase='playing';M.ready(state);state.paused=false;$('curtain').hidden=true;canvas.inert=false;document.querySelector('.touch-controls').inert=false;$('pause').hidden=false;canvas.focus();clearInput();last=performance.now();}
 function pause(){if(!state||state.phase!=='playing')return;state.paused=true;modal('Watch paused','<div class="actions"><button data-resume>Resume</button><button class="secondary" data-title>Finish this run</button></div><p class="fine">Unfinished runs do not enter the high-score table.</p>');}
 function finish(){uiPhase='over';entries=state.players.map((p,i)=>({player:i+1,score:p.score})).filter(p=>p.score>0&&(save.scores.length<5||p.score>save.scores[save.scores.length-1].score));entry=0;nextScore();}
 function nextScore(){if(entry>=entries.length){modal('The watch is over','<p>'+state.players.map((p,i)=>'Player '+(i+1)+': '+p.score+' points').join(' · ')+'</p>'+table()+buttons());return;}const p=entries[entry];modal('Player '+p.player+' · high score','<p>'+p.score+' points. Enter three initials for the lighthouse board.</p><form id="initialForm"><label for="initials">Your initials</label><input id="initials" name="initials" maxlength="3" pattern="[A-Za-z0-9]{3}" value="AAA" autocomplete="off" autocapitalize="characters" required aria-describedby="initialHint"><p id="initialHint" class="fine">Three letters or numbers. Saved on this device.</p><div class="actions"><button type="submit">Keep score</button><button type="button" class="secondary" data-skip>Skip</button></div></form>');$('initials').focus();$('initials').select();$('initialForm').addEventListener('submit',e=>{e.preventDefault();if(!$('initialForm').checkValidity())return;save.scores=M.record(save.scores,$('initials').value,p.score);const kept=persist();if(kept)Arcade.report('lighthouse-watch',{summary:'Best: '+save.scores[0].score+' points',detail:'Saltmarsh lighthouse high scores'});entry++;nextScore();if(!kept)$('notice').textContent='Score kept for this visit. This browser could not save it.';});}
 $('panel').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.start)start(Number(b.dataset.start));else if(b.hasAttribute('data-launch')||b.hasAttribute('data-resume'))launch();else if(b.hasAttribute('data-title'))title();else if(b.hasAttribute('data-skip')){entry++;nextScore();}});
 $('pause').addEventListener('click',pause);
 // tap or click the sky: aim there and fire
 canvas.addEventListener('pointerdown',e=>{if(!state||state.paused||state.phase!=='playing')return;const r=canvas.getBoundingClientRect();tapAt={x:(e.clientX-r.left)/r.width*M.W,y:(e.clientY-r.top)/r.height*M.H};queuedFire=true;});
 const gameKey=k=>['arrowleft','arrowright','arrowup','arrowdown','a','d','w','s',' '].includes(k);
 window.addEventListener('keydown',e=>{if(e.target.closest&&e.target.closest('input,button,a,select,textarea,.arc-set-bg'))return;const k=e.key.toLowerCase();if(k==='p'||k==='escape'){e.preventDefault();if(state&&state.paused)launch();else pause();return;}if(gameKey(k)&&state&&state.phase==='playing'&&!state.paused){e.preventDefault();keys.add(k);if(k===' ')queuedFire=true;}});
 window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pause();}});
 document.querySelectorAll('[data-hold]').forEach(b=>{b.addEventListener('pointerdown',e=>{if(!state||state.paused||state.phase!=='playing')return;e.preventDefault();try{b.setPointerCapture(e.pointerId);}catch(_){}pointers.set(e.pointerId,b.dataset.hold);if(b.dataset.hold==='fire')queuedFire=true;});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,e=>pointers.delete(e.pointerId));b.addEventListener('click',e=>{if(e.detail===0&&b.dataset.hold==='fire')queuedFire=true;});b.addEventListener('keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();keys.add('touch-'+b.dataset.hold);}});b.addEventListener('keyup',()=>keys.delete('touch-'+b.dataset.hold));});
 function input(){const held=v=>[...pointers.values()].includes(v)||keys.has('touch-'+v);let dx=(keys.has('arrowright')||keys.has('d')||held('right')?1:0)-(keys.has('arrowleft')||keys.has('a')||held('left')?1:0),dy=(keys.has('arrowdown')||keys.has('s')||held('down')?1:0)-(keys.has('arrowup')||keys.has('w')||held('up')?1:0),fire=keys.has(' ')||held('fire')||queuedFire,at=tapAt;queuedFire=false;tapAt=null;const pad=[...(navigator.getGamepads?navigator.getGamepads():[])].find(p=>p&&p.connected);if(pad){const press=i=>!!(pad.buttons[i]&&pad.buttons[i].pressed),x=pad.axes[0]||0,y=pad.axes[1]||0;if(Math.abs(x)>.2)dx=x;if(Math.abs(y)>.2)dy=y;if(press(14))dx=-1;if(press(15))dx=1;if(press(12))dy=-1;if(press(13))dy=1;fire=fire||press(0)||press(7);}return {dx,dy,fire,at};}
 function menuPad(){const pad=[...(navigator.getGamepads?navigator.getGamepads():[])].find(p=>p&&p.connected);if(!pad){padPause=false;padMove=false;return;}const press=i=>!!pad.buttons[i]?.pressed,settingsOpen=!!document.querySelector('.arc-set-bg:not([hidden])');const action=press(9)||(!$('curtain').hidden&&press(0)),move=!$('curtain').hidden&&(press(12)||press(13)||press(14)||press(15)||Math.abs(pad.axes[1]||0)>.55);if(!settingsOpen){if(move&&!padMove){const buttons=[...$('panel').querySelectorAll('button')],index=buttons.indexOf(document.activeElement),back=press(12)||press(14)||(pad.axes[1]||0)<-.55;buttons[(index+(back?-1:1)+buttons.length)%buttons.length]?.focus();}if(action&&!padPause){if($('curtain').hidden)pause();else{const active=document.activeElement,b=$('panel').contains(active)&&active.tagName==='BUTTON'?active:$('panel').querySelector('button');b?.click();}}}padPause=action;padMove=move;}
 function hud(s,isDemo){const p=M.current(s),n=M.afloat(p).length;$('playerLabel').textContent=isDemo?'DEMO · PRESS START':'PLAYER '+(s.active+1);$('score').textContent=String(p.score).padStart(6,'0');$('best').textContent=String(save.scores[0]?.score||0).padStart(6,'0');$('wave').textContent='NIGHT '+String(p.wave).padStart(2,'0');$('lives').textContent='◆ '.repeat(n).trim();$('lives').setAttribute('aria-label',n+' boats afloat');}
 function boat(x,afloat,t){const y=M.BOAT_Y;if(!afloat){ctx.fillStyle='#3a4c55';ctx.fillRect(x-14,y+10,28,5);ctx.fillRect(x-2,y+2,3,9);return;}const bob=reduce?0:Math.round(Math.sin(t*2+x)*1.5);ctx.fillStyle='#8a5a3a';ctx.fillRect(x-22,y+6+bob,44,9);ctx.fillRect(x-17,y+15+bob,34,4);ctx.fillStyle='#d9d4ba';ctx.fillRect(x-1,y-22+bob,3,28);ctx.fillStyle='#e9e2c6';ctx.beginPath();ctx.moveTo(x+3,y-20+bob);ctx.lineTo(x+18,y+3+bob);ctx.lineTo(x+3,y+3+bob);ctx.fill();ctx.fillStyle='#f3d580';ctx.fillRect(x-12,y+8+bob,4,3);}
 function draw(s){const r=canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.setTransform(w/640,0,0,h/640,0,0);const p=M.current(s),t=s.elapsed;
  ctx.fillStyle='#0a1426';ctx.fillRect(0,0,640,640);ctx.fillStyle='#16233a';ctx.fillRect(0,0,640,120);ctx.fillStyle='#2a3954';for(let i=0;i<9;i++){const cx=(i*97+(reduce?0:t*6))%720-40;ctx.fillRect(cx,40+(i%3)*22,70,12);ctx.fillRect(cx+14,32+(i%3)*22,40,10);}
  ctx.fillStyle='#4a5f7a';for(let i=0;i<30;i++)ctx.fillRect((i*137+19)%640,130+(i*53)%300,2,2);
  ctx.fillStyle='#0f2c3c';ctx.fillRect(0,560,640,80);ctx.fillStyle='#24566a';for(let y=574;y<638;y+=16)for(let x=0;x<640;x+=58)ctx.fillRect(x+(reduce?0:Math.floor(Math.sin(t*.8+y)*7)),y,30,2);
  // the lighthouse on its rock, centre of the harbour
  ctx.fillStyle='#2e3e44';ctx.fillRect(268,548,104,18);ctx.fillRect(280,536,80,14);ctx.fillStyle='#d8d2bc';ctx.fillRect(304,492,32,46);ctx.fillStyle='#b5463e';ctx.fillRect(304,506,32,8);ctx.fillRect(304,524,32,8);ctx.fillStyle='#3a4a4e';ctx.fillRect(300,486,40,7);ctx.fillStyle='#f6d275';ctx.fillRect(310,470,20,16);ctx.fillStyle='#3a4a4e';ctx.beginPath();ctx.moveTo(306,470);ctx.lineTo(320,458);ctx.lineTo(334,470);ctx.fill();
  for(const b of p.boats)boat(b.x,b.afloat,t);
  // sparks with their trails
  for(const k of p.sparks){ctx.strokeStyle='#ff9a4a66';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(k.x-k.vx*.35,k.y-k.vy*.35);ctx.lineTo(k.x,k.y);ctx.stroke();ctx.fillStyle=k.split?'#ffd36a':'#ff7a3a';ctx.fillRect(k.x-3,k.y-3,6,6);ctx.fillStyle='#fff2c0';ctx.fillRect(k.x-1,k.y-1,2,2);}
  ctx.strokeStyle='#f6d27588';ctx.lineWidth=3;for(const b of p.beams){ctx.beginPath();ctx.moveTo(M.TOWER.x,M.TOWER.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
  for(const b of p.bursts){ctx.fillStyle='rgba(255,236,170,'+(.45+.4*(b.r/36))+')';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff2c0';ctx.lineWidth=2;ctx.stroke();}
  // the aim
  ctx.strokeStyle='#f6d275';ctx.lineWidth=2;const a=p.aim;ctx.beginPath();ctx.moveTo(a.x-10,a.y);ctx.lineTo(a.x-4,a.y);ctx.moveTo(a.x+4,a.y);ctx.lineTo(a.x+10,a.y);ctx.moveTo(a.x,a.y-10);ctx.lineTo(a.x,a.y-4);ctx.moveTo(a.x,a.y+4);ctx.lineTo(a.x,a.y+10);ctx.stroke();
  if(p.clearing>0){ctx.fillStyle='#f6d275';ctx.font='bold 26px monospace';ctx.textAlign='center';ctx.fillText('DAWN · '+M.afloat(p).length+' BOATS SAFE',320,300);}
 }
 function frame(now){const dt=Math.min(.08,Math.max(0,(now-last)/1000));last=now;menuPad();if(!state){if(demo.phase!=='playing'){demo=M.create(1,31);M.ready(demo);}const p=M.current(demo);const k=p.sparks.reduce((lo,c)=>!lo||c.y>lo.y?c:lo,null);M.advance(demo,reduce?0:dt,k&&k.y>140?{at:{x:k.x+k.vx*.6,y:k.y+k.vy*.6},fire:Math.random()<.04}:{});draw(demo);hud(demo,true);}else{if(state.phase==='playing'&&!state.paused){M.advance(state,dt,input());for(const e of state.events){audio.sfx(e==='shot'?'blip':e==='hit'?'hit':e==='spark'?'coin':e==='clear'||e==='wave'||e==='boat'?'level':e==='burst'?null:'select');}}if(state.phase==='ready'&&uiPhase!=='ready')readyPanel();else if(state.phase==='over'&&uiPhase!=='over')finish();draw(state);hud(state,false);}requestAnimationFrame(frame);}
 title();requestAnimationFrame(frame);
 if(['localhost','127.0.0.1','[::1]'].includes(location.hostname))window.__watch={M,get state(){return state;},save,start,launch,pause,title,finish};
})();
