'use strict';
function diamondChecks(){
  const d=window.__dc,out=[],clone=o=>JSON.parse(JSON.stringify(o));
  const check=(label,fn)=>{try{if(!fn())throw Error('assertion false');out.push({label,ok:true});}catch(e){out.push({label:label+' ('+e.message+')',ok:false});}};
  const assert=(n,msg)=>{if(!n)throw Error(msg);};
  const runners=()=>[{hero:false,name:'First'},{hero:false,name:'Second'},{hero:true,name:'Third'}];
  check('Fresh career has no automatic sound, contract or purchases',()=>{const s=d.freshCareer(1);return s.sound===0&&s.phase==='creator'&&!s.contract&&!s.owned.car&&s.cash===0;});
  check('Four balls award first base and reset the count',()=>{const g=d.newGame();for(let i=0;i<4;i++)d.applyPlay(g,'ball');return !!g.bases[0]&&g.count.balls===0&&g.totals[0].walks===1&&g.totals[0].ab===0&&g.order[0]===1;});
  check('Three strikes make exactly one out',()=>{const g=d.newGame();for(let i=0;i<3;i++)d.applyPlay(g,'strike');return g.outs===1&&g.totals[0].k===1&&g.totals[0].pa===1&&g.count.strikes===0;});
  check('A foul adds a strike but cannot be strike three',()=>{const g=d.newGame();for(let i=0;i<8;i++)d.applyPlay(g,'foul');return g.count.strikes===2&&g.outs===0&&g.order[0]===0;});
  check('A full count persists until a legal walk or strikeout',()=>{const g=d.newGame();['ball','strike','ball','strike','ball','foul'].forEach(p=>d.applyPlay(g,p));assert(g.count.balls===3&&g.count.strikes===2,'full count');d.applyPlay(g,'ball');return g.totals[0].walks===1&&g.outs===0;});
  check('Unforced runners do not advance on a walk',()=>{const g=d.newGame();g.bases=[null,runners()[1],runners()[2]];d.applyPlay(g,'walk');return g.bases[1].name==='Second'&&g.bases[2].name==='Third'&&g.score[0]===0;});
  check('A loaded walk forces one run and each occupied base',()=>{const g=d.newGame();g.bases=runners();d.applyPlay(g,'walk');return g.score[0]===1&&g.bases[1].name==='First'&&g.bases[2].name==='Second'&&g.totals[0].rbi===1&&g.hero.runs===1;});
  for(const bases of [1,2,3,4])check(['','Single','Double','Triple','Home run'][bases]+' advances runners and credits exact runs',()=>{const g=d.newGame();g.bases=runners();d.applyPlay(g,bases);return g.score[0]===(bases===4?4:bases)&&g.totals[0].rbi===g.score[0]&&g.hero.runs===1&&g.bases.filter(Boolean).length===(bases===4?0:4-bases);});
  check('A clean out holds runners and scores nothing',()=>{const g=d.newGame();g.bases=runners();const before=JSON.stringify(g.bases);d.applyPlay(g,'out');return g.outs===1&&g.score[0]===0&&JSON.stringify(g.bases)===before;});
  check('Third out clears bases and opens bottom of the same inning',()=>{const g=d.newGame();g.bases=runners();for(let i=0;i<3;i++)d.applyPlay(g,'out');return g.inning===1&&g.half===1&&g.outs===0&&g.bases.every(b=>!b)&&g.score[0]===0;});
  check('Both halves are required before inning advances',()=>{const g=d.newGame();for(let i=0;i<6;i++)d.applyPlay(g,'out');return g.inning===2&&g.half===0&&g.order[0]===3&&g.order[1]===3;});
  check('Home lead skips bottom of ninth',()=>{const g=d.newGame();g.inning=9;g.score=[0,1];for(let i=0;i<3;i++)d.applyPlay(g,'out');return g.finished&&g.half===0&&g.inning===9;});
  check('Visitor lead becomes final after bottom nine',()=>{const g=d.newGame();g.inning=9;g.half=1;g.score=[2,1];for(let i=0;i<3;i++)d.applyPlay(g,'out');return g.finished&&g.score[0]===2;});
  check('A tie opens extra innings, never invents a winning run',()=>{const g=d.newGame();g.inning=9;g.half=1;g.score=[2,2];for(let i=0;i<3;i++)d.applyPlay(g,'out');return !g.finished&&g.inning===10&&g.score[0]===2&&g.score[1]===2;});
  check('Non-homer walk-off ends on the first winning run, including runner statistics',()=>{const g=d.newGame();g.inning=9;g.half=1;g.score=[2,2];g.bases=runners();const r=d.applyPlay(g,3);return g.finished&&g.score[1]===3&&r.runs===1&&g.totals[1].runs===1&&g.hero.runs===1;});
  check('Walk-off home run scores every runner',()=>{const g=d.newGame();g.inning=9;g.half=1;g.score=[2,2];g.bases=runners();d.applyPlay(g,4);return g.finished&&g.score[1]===6&&g.hero.hr===1&&g.hero.rbi===4&&g.hero.runs===2;});
  check('Finished games cannot accept another play',()=>{const g=d.newGame();g.finished=true;const before=JSON.stringify(g);d.applyPlay(g,4);return before===JSON.stringify(g);});
  check('A taken ball and a taken strike follow the actual zone',()=>{const stats={contact:58,power:50},g=d.newGame();return d.resolvePitch(g,stats,{inZone:false},{take:true}).play==='ball'&&d.resolvePitch(g,stats,{inZone:true},{take:true}).play==='strike';});
  function trials(mode,timing,guess,stance='contact',stats={contact:58,power:50,discipline:55}){
    const n={hits:0,hr:0,contact:0};for(let i=1;i<=6000;i++){const g=d.newGame(i*503);const r=d.resolvePitch(g,stats,{type:'change-up',skill:54,inZone:true},{mode,timing,guess,stance});if(typeof r.play==='number'){n.hits++;if(r.play===4)n.hr++;}if(r.play!=='strike')n.contact++;}return n;
  }
  check('On-time batting improves hits over early batting without guaranteeing a home run',()=>{const good=trials('timing',1),early=trials('timing',.45);return good.hits>early.hits*1.15&&good.hr>0&&good.hr<good.hits/2&&good.hits<6000;});
  check('Correct tactical pitch reads improve odds over the wrong guess',()=>{const a=trials('tactical',0,'change-up'),b=trials('tactical',0,'fastball');return a.hits>b.hits*1.15&&a.hits<6000;});
  check('Power trades fewer contacts for more home runs',()=>{const a=trials('tactical',0,'change-up','contact'),b=trials('tactical',0,'change-up','power');return b.contact<a.contact&&b.hr>a.hr;});
  check('Contact and power stats make distinct builds useful',()=>{const a=trials('tactical',0,'change-up','contact',{contact:75,power:40}),b=trials('tactical',0,'change-up','power',{contact:48,power:75});return a.hits>b.hits&&b.hr>a.hr;});
  check('Plain-language timing feedback explains early and late change-ups',()=>{const p={type:'change-up',skill:54,inZone:true},stats={contact:58,power:50};return d.resolvePitch(d.newGame(),stats,p,{mode:'timing',timing:.5}).text.includes('early on the change-up')&&d.resolvePitch(d.newGame(),stats,p,{mode:'timing',timing:1.4}).text.includes('late on the change-up');});
  check('Seeded games are reproducible, independent of rendering',()=>{const a=d.newGame(812),b=d.newGame(812);for(const g of [a,b])d.simulateToMoment(g,{contact:58,power:50,discipline:55},d.DC.pitchers[0],2,true);return JSON.stringify(a)===JSON.stringify(b);});
  let batch=[];
  check('400 simulated games finish with legal totals, untied scores and credible run ranges',()=>{
    for(let i=1;i<=400;i++){const g=d.newGame(i*293);d.simulateToMoment(g,{contact:58,power:50,discipline:55},d.DC.pitchers[i%3],2,true);assert(g.finished&&g.inning>=9&&g.score[0]!==g.score[1],'game '+i+' final');assert(g.count.balls===0&&g.count.strikes===0,'final count');for(let t=0;t<2;t++){const s=g.totals[t];assert(s.pa===s.ab+s.walks&&s.hits<=s.ab&&s.hr<=s.hits&&s.k<=s.ab,'totals');assert(s.runs===g.score[t]&&s.rbi===g.score[t],'score agrees');}batch.push(g);}
    const mean=batch.reduce((n,g)=>n+g.score[0]+g.score[1],0)/batch.length;assert(mean>3&&mean<18,'combined runs/game '+mean.toFixed(2));return true;
  });
  function playSeries(s,mode='tactical'){
    s.mode=mode;while(s.played<6){d.startMatch(s);let guard=0;while(s.phase!=='summary'){
      assert(++guard<1000,'career game loop');if(s.phase==='pitch'){const p=s.active.pitch;d.playPitch(s,{take:!p.inZone,mode,timing:1,guess:p.hint,stance:s.stance});}else d.continueMatch(s);
    }d.afterMatch(s);}return s;
  }
  for(const mode of ['timing','tactical'])check(mode+' career plays six games, reaches two offers and accounts each game once',()=>{const s=d.freshCareer(2871);d.startCareer(s,'Test','left',2);playSeries(s,mode);return s.phase==='offers'&&s.history.length===6&&s.record.pa===s.history.reduce((n,h)=>n+h.hero.pa,0)&&s.active===null&&s.day===7;});
  for(const build of ['contact','power'])check(build+' build can earn the transparent call-up',()=>{let promoted=0;for(let i=1;i<=12;i++){const s=d.freshCareer(i*191);d.startCareer(s,'Test','right',0);s.stats[build]=75;s.stance=build;playSeries(s);if(d.evaluation(s).earned)promoted++;}return promoted>=9;});
  check('A slump gets a paid development offer, with the same visible future target',()=>{const s=d.freshCareer();d.startCareer(s,'Test','right',0);s.phase='offers';s.season={...d.lineStats(),pa:25,ab:25,hits:1};assert(!d.evaluation(s).earned,'slump');return d.signContract(s,'starts')&&s.contract.tier==='Development club'&&s.cash===180;});
  check('Preparation applies once per game and repeated requests cannot farm stats',()=>{const s=d.freshCareer();d.startCareer(s,'Test','right',0);d.training(s,'contact');const before=JSON.stringify(s);return !d.training(s,'power')&&JSON.stringify(s)===before&&s.stats.contact===60;});
  check('Preparation survives reload, so reloading cannot grant another session',()=>{const s=d.freshCareer();d.startCareer(s,'Test','right',0);d.training(s,'contact');const loaded=d.migrateCareer(clone(s));return loaded.prepared&&!d.training(loaded,'contact')&&loaded.stats.contact===60;});
  check('Rest clears fatigue and the next match allows a new preparation',()=>{const s=d.freshCareer();d.startCareer(s,'Test','right',0);s.fatigue=30;d.training(s,'rest');assert(s.fatigue===0,'rest');d.startMatch(s);return !s.prepared;});
  function offered(id){const s=d.freshCareer(223);d.startCareer(s,'Test','right',0);s.phase='offers';s.season={...d.lineStats(),hits:6,ab:20,pa:24,walks:4};d.signContract(s,id);return s;}
  check('Two offers exchange higher total pay for fewer playable opportunities',()=>{const a=d.DC.offers.wage,b=d.DC.offers.starts;return a.bonus+a.wage*3>b.bonus+b.wage*3&&a.moments<b.moments;});
  check('Contract bonus pays once; repeated signing does nothing',()=>{const s=offered('wage'),before=JSON.stringify(s);return s.cash===320&&!d.signContract(s,'starts')&&JSON.stringify(s)===before&&s.contract.tier==='Senior club';});
  check('Salary is paid on due dates, not renders or wall-clock time',()=>{const s=offered('starts'),start=s.day;d.advanceDays(s,1);assert(s.cash===180,'too early');d.advanceDays(s,1);assert(s.cash===350,'first salary');d.advanceDays(s,3);assert(s.cash===520,'second salary');d.advanceDays(s,1);return s.cash===690&&s.ledger.filter(e=>e.id.startsWith('salary-')).every((e,i)=>e.day===start+[2,4,6][i]);});
  check('Skipping dates catches up once without duplicating salary after reload',()=>{const s=offered('wage');d.advanceDays(s,10);const loaded=d.migrateCareer(clone(s));d.advanceDays(loaded,10);return loaded.cash===1040&&loaded.ledger.length===4;});
  check('A calendar day does not expire purchases or charge upkeep',()=>{const s=offered('wage');d.advanceDays(s,8);d.purchase(s,'apartment');d.purchase(s,'car');const cash=s.cash;d.advanceDays(s,30);return s.cash===cash&&s.owned.apartment&&s.owned.car;});
  check('Purchases reject insufficient funds and duplicate spending',()=>{const s=offered('starts');assert(!d.purchase(s,'car')&&s.cash===180,'insufficient');d.advanceDays(s,4);assert(d.purchase(s,'car'),'affordable');const cash=s.cash;return !d.purchase(s,'car')&&s.cash===cash&&s.owned.car;});
  for(const id of ['wage','starts'])check(id+' contract changes actual manual at-bats in the next six games',()=>{const s=offered(id);playSeries(s);return s.history.length===6&&s.history.every(h=>h.manual<=d.DC.offers[id].moments)&&s.history.reduce((n,h)=>n+h.manual,0)>=d.DC.offers[id].moments*5;});
  check('An empty/old partial save receives safe defaults',()=>{for(const old of [null,{}, {game:'diamond-career',player:{name:'Old','bats':'left',look:1},phase:'clubhouse',cash:12}]){const s=d.migrateCareer(old);assert(d.validCareer(s)&&s.sound===0&&s.ledger.length===0,'defaults');}return true;});
  check('A different game or malformed save cannot become a career',()=>!d.validCareer({game:'wildbond',schema:1})&&!d.validCareer([])&&d.migrateCareer({game:'wildbond',cash:500}).phase==='creator');
  check('A mid-at-bat save preserves pitch, RNG, count and bases across modes',()=>{const s=d.freshCareer(581);d.startCareer(s,'Test','left',3);d.startMatch(s);d.playPitch(s,{take:true});d.continueMatch(s);const a=d.migrateCareer(clone(s));const p=JSON.stringify(a.active);a.mode='tactical';return p===JSON.stringify(s.active)&&a.player.bats==='left'&&a.player.look===3;});
  check('Switching style preserves the current pitch and count through real Settings callbacks',()=>{const s=d.freshCareer(119);d.startCareer(s,'Test','right',0);d.startMatch(s);d.S=s;const before=JSON.stringify(s.active);document.querySelector('.arc-set-btn').click();document.querySelector('.arc-set [data-r="0"][data-o="1"]').click();document.querySelector('.arc-set [data-close]').click();return d.S.mode==='tactical'&&JSON.stringify(d.S.active)===before;});
  check('Tactical patience makes an eye check and completes a pitch via the real control',()=>{const s=d.freshCareer(779);d.startCareer(s,'Test','right',0);d.startMatch(s);s.mode='tactical';s.stance='patience';d.S=s;d.actCareer('tactical');return s.phase==='result'&&typeof s.active.last.take==='boolean';});
  check('Completed result reload cannot credit a game twice',()=>{const s=d.freshCareer(931);d.startCareer(s,'Test','right',0);d.startMatch(s);d.simulateToMoment(s.active.g,s.stats,s.active.pitcher,2,true);s.phase='result';s.active.last={ended:true,text:'Game over.'};d.continueMatch(s);const first=s.record.pa,loaded=d.migrateCareer(clone(s));loaded.phase='result';d.continueMatch(loaded);return loaded.record.pa===first&&loaded.played===1;});
  check('Malformed nested save data is rejected safely before rendering',()=>{const s=offered('wage');s.stats.contact='broken';assert(!d.validCareer(s),'invalid stats');return d.migrateCareer(s).phase==='creator';});
  check('Signed clubs never play themselves',()=>{for(const id of ['wage','starts']){const s=offered(id);for(let i=0;i<6;i++){s.played=i;s.phase='home';d.startMatch(s);assert(s.active.opponent!==d.DC.offers[id].name,'self match');}}return true;});
  check('Real shared save/load retains salary, possessions and profile; validator accepts it',()=>{const s=offered('wage');d.advanceDays(s,6);d.purchase(s,'car');d.S=s;d.saveCareer();const loaded=d.migrateCareer(Arcade.load(d.DC.key));return d.validCareer(loaded)&&loaded.owned.car&&loaded.cash===620&&loaded.player.name==='Test'&&loaded.ledger.length===5&&Arcade.readIndex().baseball;});
  check('Save tools expose file download/import and the generated backups',()=>Arcade.saveToolsHTML(d.DC.key).includes('data-arcsave="download"')&&Arcade.backups(d.DC.key).length>=1);
  check('Both original tracks are valid shared-engine note strings',()=>Object.values(d.DC_TRACKS).every(t=>t.bpm>50&&t.bpm<180&&t.mel.split(' ').every(n=>n==='.'||/^[A-G]#?[0-8]$/.test(n))));
  check('The UI escapes player names instead of inserting markup',()=>{const s=d.freshCareer();d.startCareer(s,'<img src=x>','left',0);d.S=s;d.renderCareer();return !document.querySelector('#content img')&&document.querySelector('#content h1').textContent==='<img src=x>';});

  function renewed(first='wage',second='starts') {const s=d.freshCareer(223);d.startCareer(s,'Test','right',0);playSeries(s);d.signContract(s,first);playSeries(s);assert(s.phase==='offers','first term ends at its real date');assert(d.signContract(s,second),'choose second term');return s;}
  for(const first of ['wage','starts'])for(const second of ['wage','starts']) {
    check(first+' to '+second+': second contract pays a unique bonus and preserves owned milestones',()=>{const s=offered(first);d.advanceDays(s,4);d.purchase(s,'apartment');const cash=s.cash;d.advanceDays(s,2);s.phase=d.careerPhase(s);assert(d.signContract(s,second),'renew');assert(s.cash===cash+d.DC.offers[first].wage+d.DC.renewals[second].bonus,'old salary plus new bonus');return s.owned.apartment&&s.contracts.length===1&&s.contracts[0].offer===first&&s.contract.generation===1;});
    check(first+' to '+second+': first full month has 18 scored games and exact wallet',()=>{const s=renewed(first,second);playSeries(s);assert(d.beginSeries(s),'second renewal series');playSeries(s);const a=d.DC.offers[first],b=d.DC.renewals[second];assert(s.phase==='month'&&s.day===s.month.end&&s.month.end-s.month.start===30,'30-day close');assert(s.month.games===18&&s.history.length===24,'development plus professional history');assert(s.cash===a.bonus+a.wage*3+b.bonus+b.wage*4,'stated total');assert(s.ledger.filter(e=>e.id.includes('salary')).length===7,'seven unique salaries');return s.month.record.pa===s.history.filter(h=>h.day>=s.month.start).reduce((n,h)=>n+h.hero.pa,0)&&s.month.record.hits<=s.month.record.ab;});
    check(first+' to '+second+': role changes real at-bat opportunity in both renewal series',()=>{const s=renewed(first,second);const before=s.history.length;playSeries(s);d.beginSeries(s);playSeries(s);const matches=s.history.slice(before),limit=d.DC.renewals[second].moments;return matches.length===12&&matches.every(h=>h.manual<=limit)&&matches.reduce((n,h)=>n+h.manual,0)>=limit*10;});
  }
  check('Renewal salary schedule and next payment agree with ledger at every installment',()=>{const s=renewed();const start=s.day,status=d.calendarStatus(s);assert(status.total===1000&&status.next.day===start+6&&status.paid===0,'starts offer');for(let i=0;i<4;i++){d.advanceDays(s,6);const c=d.calendarStatus(s);assert(c.paid===i+1,'paid count');assert(i===3?!c.next:c.next.day===start+(i+2)*6,'next due');}return s.ledger.filter(e=>e.id.startsWith('contract-1-salary-')).every((e,i)=>e.day===start+(i+1)*6);});
  check('Second signing cannot be replayed and a third contract is not invented',()=>{const s=renewed(),before=JSON.stringify(s);assert(!d.signContract(s,'wage')&&JSON.stringify(s)===before,'duplicate sign');d.advanceDays(s,24);s.phase='offers';const cash=s.cash;return !d.signContract(s,'wage')&&s.cash===cash&&s.contracts.length===1;});
  check('Dates catch up both contracts without duplicate salary after save/reload',()=>{const s=renewed();d.advanceDays(s,18);const cash=s.cash,a=d.migrateCareer(clone(s));d.advanceDays(a,0);assert(a.cash===cash,'reload stable');d.advanceDays(a,30);const final=a.cash;d.advanceDays(a,30);return a.cash===final&&new Set(a.ledger.map(e=>e.id)).size===a.ledger.length&&a.day===a.month.end;});
  check('Contract expires by calendar, even if the player chose rest instead of games',()=>{const s=offered('starts');d.advanceDays(s,6);s.phase=d.careerPhase(s);assert(s.phase==='offers','date expiry');return !d.startMatch(s)&&d.signContract(s,'wage')&&s.month.games===0&&s.contract.tier==='Senior club';});
  check('A development renewal does not secretly promote an incomplete evaluation',()=>{const s=d.freshCareer();d.startCareer(s,'Learner','left',1);s.phase='offers';d.signContract(s,'starts');d.advanceDays(s,6);s.phase=d.careerPhase(s);d.signContract(s,'wage');return s.contract.tier==='Development club'&&s.owned.car===false;});
  check('Month ends cleanly without automatically playing or charging upkeep',()=>{const s=renewed(),before=s.record.pa;d.advanceDays(s,24);s.phase=d.careerPhase(s);const cash=s.cash;return s.phase==='month'&&!d.startMatch(s)&&!d.beginSeries(s)&&!d.training(s,'contact')&&s.cash===cash&&s.record.pa===before;});
  check('Legacy paid prototype begins a calendar without rewriting old date, money or payment IDs',()=>{const s=offered('wage');d.advanceDays(s,8);d.purchase(s,'car');s.day=123;delete s.month;delete s.notes;delete s.contracts;delete s.contract.generation;const a=d.migrateCareer(clone(s));return a.day===123&&a.cash===s.cash&&a.owned.car&&a.ledger.length===s.ledger.length&&a.month.start===123&&a.month.end===153&&a.phase==='offers'&&d.validCareer(a);});
  check('Legacy first-term remainder and close-month button respect original paid dates',()=>{const s=offered('starts');delete s.month;delete s.notes;delete s.contracts;delete s.contract.generation;const a=d.migrateCareer(clone(s));d.advanceDays(a,6);a.phase=d.careerPhase(a);d.signContract(a,'wage');d.advanceDays(a,24);a.phase=d.careerPhase(a);return a.phase==='month'&&a.ledger.filter(e=>e.id.startsWith('salary-')).length===3;});
  check('Expired legacy contract can close its remaining month without another game',()=>{const s=offered('wage');d.advanceDays(s,12);delete s.month;const a=d.migrateCareer(clone(s));a.phase=d.careerPhase(a);d.signContract(a,'starts');d.advanceDays(a,24);a.phase=d.careerPhase(a);return a.phase==='home'&&d.finishMonth(a)&&a.phase==='month'&&a.day===a.month.end;});
  check('Monthly results survive mid-pitch save and never account one match twice',()=>{const s=renewed();d.startMatch(s);const a=d.migrateCareer(clone(s));assert(JSON.stringify(a.active)===JSON.stringify(s.active),'same pitch');d.simulateToMoment(a.active.g,a.stats,a.active.pitcher,3,true);a.phase='result';a.active.last={ended:true,text:'Game over.'};d.continueMatch(a);const count=a.month.games;const b=d.migrateCareer(clone(a));b.phase='result';d.continueMatch(b);return b.month.games===count&&JSON.stringify(b.month.record)===JSON.stringify(a.month.record);});
  check('Patient walk and meaningful rest are remembered only when they really happen',()=>{const s=d.freshCareer(555);d.startCareer(s,'Tester','right',0);d.startMatch(s);s.active.g.count.balls=3;s.active.pitch.inZone=false;d.playPitch(s,{take:true,mode:'tactical'});assert(s.notes.length===1&&s.notes[0].kind==='walk','actual walk');d.continueMatch(s);d.playPitch(s,{take:true});assert(s.notes.length===1,'one note per day');s.active=null;s.phase='clubhouse';s.fatigue=28;d.training(s,'rest');return s.notes.length===2&&s.notes[1].kind==='rest'&&s.fatigue===0;});
  check('Malformed new month, notes or contract history are rejected by shared validator',()=>{for(const key of ['month','notes','contracts']){const s=renewed();s[key]=key==='month'?{start:1,end:99}:['bad'];assert(!d.validCareer(s),key);}return true;});
  check('Renewal offer page shows actual total, dates and playing time through real UI',()=>{const s=offered('starts');d.advanceDays(s,6);s.phase=d.careerPhase(s);d.S=s;const t=document.querySelector('#content').textContent;return t.includes('Your next contract')&&t.includes('$1,440')&&t.includes('$1,000')&&t.includes('24-day term')&&t.includes('3 playable key at-bats');});
  check('Quiet-day UI reaches renewal once; choosing it resets series but keeps career',()=>{const s=offered('starts');d.advanceDays(s,5);d.S=s;const hits=s.record.hits;d.actCareer('day');assert(s.phase==='offers','review');d.actCareer('sign-wage');return s.contract.generation===1&&s.phase==='home'&&s.played===0&&s.record.hits===hits&&s.contracts.length===1;});
  check('Finished month UI states actual recorded totals and keeps permanent purchases available',()=>{const s=renewed();d.advanceDays(s,24);s.phase=d.careerPhase(s);d.S=s;const t=document.querySelector('#content').textContent;return t.includes('A month with your name')&&t.includes(s.month.games+' games')&&t.includes('This playable chapter ends here')&&t.includes('Buy');});

  // D1c: explicit swings, truthful explanations and earned recognition.
  function batting(seed=137){const s=d.freshCareer(seed);d.startCareer(s,'Tester','right',0);d.startMatch(s);return s;}
  check('Timing shows Contact and Power on the field, never Patience or a hidden choice',()=>{const s=batting();s.stance='patience';d.S=s;return s.stance==='contact'&&document.querySelector('#batting-window [data-stance="contact"]').getAttribute('aria-pressed')==='true'&&document.querySelector('#batting-window [data-stance="power"]')&&!document.querySelector('#batting-window [data-stance="patience"]')&&!document.querySelector('#content [data-act="ready"]');});
  check('Real field buttons choose Power before release and preserve the pitch/count/RNG',()=>{const s=batting();d.S=s;const before=JSON.stringify(s.active);document.querySelector('#batting-window [data-stance="power"]').click();return s.stance==='power'&&document.querySelector('#batting-window [data-stance="power"]').getAttribute('aria-pressed')==='true'&&JSON.stringify(s.active)===before;});
  check('Running pitch locks the swing choice and clears the field (nothing covers the ball); duplicate release cannot restart its clock',()=>{const s=batting();d.S=s;d.chooseStance('power');d.actCareer('ready');d.clock.elapsed=321;const before=JSON.stringify(s.active);assert(!d.chooseStance('contact'),'reject midflight change');d.actCareer('ready');return s.stance==='power'&&d.clock.elapsed===321&&document.querySelector('#batting-window').hidden&&!document.querySelector('#swing-tip').hidden&&JSON.stringify(s.active)===before;});
  check('Tapping the field swings, and really applies selected Power in the unchanged pitch model',()=>{const s=batting();d.S=s;d.chooseStance('power');const expected=d.resolvePitch(clone(s.active.g),s.stats,clone(s.active.pitch),{mode:'timing',timing:1,stance:'power'});d.actCareer('ready');d.clock.elapsed=s.active.pitch.duration;document.querySelector('#world').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));return s.phase==='result'&&s.active.last.play===expected.play&&s.active.last.text===expected.text;});
  check('Patience to Timing Settings switch visibly selects Contact without rerolling a pitch',()=>{const s=batting();s.mode='tactical';s.stance='patience';d.S=s;const before=JSON.stringify(s.active);document.querySelector('.arc-set-btn').click();document.querySelector('.arc-set [data-r="0"][data-o="0"]').click();document.querySelector('.arc-set [data-close]').click();return s.mode==='timing'&&s.stance==='contact'&&JSON.stringify(s.active)===before&&document.querySelector('#batting-window [data-stance="contact"]').getAttribute('aria-pressed')==='true';});
  check('Legacy Timing Patience and unknown stances normalize, while Tactical Patience survives',()=>{for(const stance of ['patience','broken',null]){const s=batting();s.stance=stance;const a=d.migrateCareer(clone(s));assert(a.stance==='contact'&&JSON.stringify(a.active)===JSON.stringify(s.active),'safe default');}const s=batting();s.mode='tactical';s.stance='patience';return d.migrateCareer(s).stance==='patience';});
  check('Old saved pitch keeps its hint, seed, count and baseline cue even with a higher Eye',()=>{const s=batting();delete s.active.pitch.cueChance;s.stats.discipline=80;s.active.g.count={balls:2,strikes:1};const a=d.migrateCareer(clone(s));d.S=a;return JSON.stringify(a.active)===JSON.stringify(s.active)&&document.querySelector('.field-cue').textContent.includes('85.3%');});
  check('Cue confidence is bounded and a missing/non-finite Eye safely uses the baseline',()=>{return Math.abs(d.cueAccuracy({discipline:50})- (.78+.22/3))<1e-10&&d.cueAccuracy({discipline:80})>d.cueAccuracy({discipline:50})&&d.cueAccuracy({discipline:999})<1&&d.cueAccuracy({discipline:-999})>0&&d.cueAccuracy({discipline:NaN})===d.cueAccuracy({discipline:50});});
  check('Seeded recognition trials agree with displayed chance and improve with Eye',()=>{const counts=[];for(const eye of [50,80]){let n=0;for(let i=1;i<=20000;i++){const p=d.makePitch(d.newGame(i*503),d.DC.pitchers[0],{discipline:eye});if(p.hint===p.type)n++;assert(Math.abs(p.cueChance-d.cueAccuracy({discipline:eye}))<1e-10,'snapshot');}const ratio=n/20000;assert(Math.abs(ratio-d.cueAccuracy({discipline:eye}))<.012,'honest percent');counts.push(n);}return counts[1]>counts[0]+400;});
  check('Eye does not change pitch type, actual zone, duration or skill for the same seed',()=>{for(let i=1;i<=100;i++){const a=d.makePitch(d.newGame(i),d.DC.pitchers[0],{discipline:50}),b=d.makePitch(d.newGame(i),d.DC.pitchers[0],{discipline:80});for(const k of ['type','inZone','duration','skill'])assert(a[k]===b[k],k);}return true;});
  check('Next manual pitch snapshots the actual trained Eye and reload retains that chance',()=>{const s=batting();s.stats.discipline=80;s.active.pitch.inZone=false;d.playPitch(s,{take:true});d.continueMatch(s);const a=d.migrateCareer(clone(s));return Math.abs(a.active.pitch.cueChance-d.cueAccuracy(s.stats))<1e-10&&JSON.stringify(a.active)===JSON.stringify(s.active);});
  check('Eye training records actual improvement once per preparation and survives old-save defaults',()=>{const s=d.freshCareer();d.startCareer(s,'Learner','left',0);delete s.notes;const a=d.migrateCareer(s),cash=a.cash,eye=a.stats.discipline;assert(d.training(a,'discipline'),'train');const before=JSON.stringify(a);assert(!d.training(a,'discipline')&&JSON.stringify(a)===before,'one prep');const n=a.notes.find(n=>n.kind==='eye');return a.stats.discipline===eye+2&&n.text.includes((d.cueAccuracy(a.stats)*100).toFixed(1)+'%')&&n.text.includes('up from')&&d.migrateCareer(a).notes[0].text===n.text&&a.cash===cash;});
  check('Capped Eye session says zero growth, never invents another improvement',()=>{const s=d.freshCareer();d.startCareer(s,'Learner','left',0);s.stats.discipline=80;d.training(s,'discipline');return s.stats.discipline===80&&s.notes[0].text.includes('80 → 80')&&s.notes[0].text.includes('training limit')&&!s.notes[0].text.includes('up from');});
  check('Iona explains Eye training in a portrait scene inside the clubhouse, with a notebook record',()=>{const s=d.freshCareer();d.startCareer(s,'Learner','left',0);d.S=s;d.actCareer('train-discipline');assert(document.querySelector('#stage .dlg')&&!document.querySelector('#stage .dlg').hidden,'world portrait');const ok=s.notes.some(n=>n.kind==='eye')&&s.stats.discipline===57;d.D.skip();return ok;});
  for(const mode of ['timing','tactical'])check(mode+' off-plate swing explains reach for every model outcome',()=>{const found=new Set();for(let i=1;i<=2000;i++){const r=d.resolvePitch(d.newGame(i*503),{contact:58,power:50},{type:'curve',skill:54,inZone:false},{mode,timing:1,guess:'curve',stance:'contact'});assert(r.text.includes('off the plate')&&r.text.includes('harder to reach'),'reach text');found.add(r.play);}return ['strike','foul','out',1,2,3,4].every(x=>found.has(x));});
  check('Taking an off-plate pitch stays a ball, never claims weak or good contact',()=>{const r=d.resolvePitch(d.newGame(),{contact:58,power:50},{inZone:false},{take:true});return r.play==='ball'&&r.text.includes('missed the zone')&&!r.text.includes('contact');});
  check('Caught good contact and weak contact are distinct in both batting styles',()=>{for(const mode of ['timing','tactical'])for(const good of [true,false]){let caught=false;for(let i=1;i<=500;i++){const r=d.resolvePitch(d.newGame(i*503),{contact:58,power:50},{type:'curve',skill:54,inZone:true},{mode,timing:good?1:.45,guess:good?'curve':'fastball',stance:'contact'});if(r.play==='out'){assert(r.text.includes(good?'Good contact, but a fielder caught it':'Weak contact'),'quality');assert(r.text.includes('runners hold'),'held runners');caught=true;break;}}assert(caught,'found caught out');}return true;});
  check('Result feedback waits in the world and Continue advances once without double credit',()=>{const s=batting();s.active.pitch.inZone=false;d.S=s;d.actCareer('ready');d.actCareer('take');assert(s.phase==='result'&&document.querySelector('#stage .field-result').textContent===s.active.last.text,'world result');const before=s.active.g.pitches;document.querySelector('#batting-window [data-act="continue"]').click();assert(s.phase==='pitch','next pitch');d.actCareer('continue');return s.active.g.pitches===before;});
  return out;
}
