'use strict';
function diamondChecks(){
  const d=window.__dc,out=[],clone=o=>JSON.parse(JSON.stringify(o));
  const check=(label,fn)=>{try{if(!fn())throw Error('assertion false');out.push({label,ok:true});}catch(e){out.push({label:label+' ('+e.message+')',ok:false});}};
  const assert=(n,msg)=>{if(!n)throw Error(msg);};
  const runners=()=>[{hero:false,name:'First'},{hero:false,name:'Second'},{hero:true,name:'Third'}];
  check('Fresh career has no automatic sound, contract or purchases',()=>{const s=d.freshCareer(1);return s.sound===0&&s.phase==='creator'&&!s.contract&&!s.owned.car&&s.cash===0;});
  check('Four balls award first base and reset the count',()=>{const g=d.newGame();for(let i=0;i<4;i++)d.applyPlay(g,'ball');return !!g.bases[0]&&g.count.balls===0&&g.totals[0].walks===1&&g.totals[0].ab===0&&g.order[0]===1;});
  check('Three strikes make exactly one out',()=>{const g=d.newGame();for(let i=0;i<3;i++)d.applyPlay(g,'strike');return g.outs===1&&g.totals[0].k===1&&g.totals[0].pa===1&&g.count.strikes===0;});
  check('A foul adds a strike but cannot be strike three',()=>{const g=d.newGame();for(let i=0;i<8;i++)d.applyPlay(g,'foul');return g.count.strikes===2&&g.outs===0&&g.order[0]===0;});
  check('A full count persists until a legal walk or strikeout',()=>{const g=d.newGame();['ball','strike','ball','strike','ball','foul'].forEach(p=>d.applyPlay(g,p));assert(g.count.balls===3&&g.count.strikes===2,'full count');d.applyPlay(g,'ball');return g.totals[0].walks===1&&g.outs===0;});
  check('Unforced runners do not advance on a walk',()=>{const g=d.newGame();g.bases=[null,runners()[1],runners()[2]];d.applyPlay(g,'walk');return g.bases[1].name==='Second'&&g.bases[2].name==='Third'&&g.score[0]===0;});
  check('A loaded walk forces one run and each occupied base',()=>{const g=d.newGame();g.bases=runners();d.applyPlay(g,'walk');return g.score[0]===1&&g.bases[1].name==='First'&&g.bases[2].name==='Second'&&g.totals[0].rbi===1&&g.hero.runs===1;});
  for(const bases of [1,2,3,4])check(['','Single','Double','Triple','Home run'][bases]+' advances runners and credits exact runs',()=>{const g=d.newGame();g.bases=runners();d.applyPlay(g,bases);return g.score[0]===(bases===4?4:bases)&&g.totals[0].rbi===g.score[0]&&g.hero.runs===1&&g.bases.filter(Boolean).length===(bases===4?0:4-bases);});
  check('A clean out holds runners and scores nothing',()=>{const g=d.newGame();g.bases=runners();const before=JSON.stringify(g.bases);d.applyPlay(g,'out');return g.outs===1&&g.score[0]===0&&JSON.stringify(g.bases)===before;});
  check('Third out clears bases and opens bottom of the same inning',()=>{const g=d.newGame();g.bases=runners();for(let i=0;i<3;i++)d.applyPlay(g,'out');return g.inning===1&&g.half===1&&g.outs===0&&g.bases.every(b=>!b)&&g.score[0]===0;});
  check('Both halves are required before inning advances',()=>{const g=d.newGame();for(let i=0;i<6;i++)d.applyPlay(g,'out');return g.inning===2&&g.half===0&&g.order[0]===3&&g.order[1]===3;});
  check('Home lead skips bottom of ninth',()=>{const g=d.newGame();g.inning=9;g.score=[0,1];for(let i=0;i<3;i++)d.applyPlay(g,'out');return g.finished&&g.half===0&&g.inning===9;});
  check('Visitor lead becomes final after bottom nine',()=>{const g=d.newGame();g.inning=9;g.half=1;g.score=[2,1];for(let i=0;i<3;i++)d.applyPlay(g,'out');return g.finished&&g.score[0]===2;});
  check('A tie opens extra innings, never invents a winning run',()=>{const g=d.newGame();g.inning=9;g.half=1;g.score=[2,2];for(let i=0;i<3;i++)d.applyPlay(g,'out');return !g.finished&&g.inning===10&&g.score[0]===2&&g.score[1]===2;});
  check('Non-homer walk-off ends on the first winning run, including runner statistics',()=>{const g=d.newGame();g.inning=9;g.half=1;g.score=[2,2];g.bases=runners();const r=d.applyPlay(g,3);return g.finished&&g.score[1]===3&&r.runs===1&&g.totals[1].runs===1&&g.hero.runs===1;});
  check('Walk-off home run scores every runner',()=>{const g=d.newGame();g.inning=9;g.half=1;g.score=[2,2];g.bases=runners();d.applyPlay(g,4);return g.finished&&g.score[1]===6&&g.hero.hr===1&&g.hero.rbi===4&&g.hero.runs===2;});
  check('Finished games cannot accept another play',()=>{const g=d.newGame();g.finished=true;const before=JSON.stringify(g);d.applyPlay(g,4);return before===JSON.stringify(g);});
  check('A taken ball and a taken strike follow the actual zone',()=>{const stats={contact:58,power:50},g=d.newGame();return d.resolvePitch(g,stats,{inZone:false},{take:true}).play==='ball'&&d.resolvePitch(g,stats,{inZone:true},{take:true}).play==='strike';});
  function trials(mode,timing,guess,stance='contact',stats={contact:58,power:50,discipline:55}){
    const n={hits:0,hr:0,contact:0};for(let i=1;i<=6000;i++){const g=d.newGame(i*503);const r=d.resolvePitch(g,stats,{type:'change-up',skill:54,inZone:true},{mode,timing,guess,stance});if(typeof r.play==='number'){n.hits++;if(r.play===4)n.hr++;}if(r.play!=='strike')n.contact++;}return n;
  }
  check('On-time batting improves hits over early batting without guaranteeing a home run',()=>{const good=trials('timing',1),early=trials('timing',.45);return good.hits>early.hits*1.15&&good.hr>0&&good.hr<good.hits/2&&good.hits<6000;});
  check('Correct tactical pitch reads improve odds over the wrong guess',()=>{const a=trials('tactical',0,'change-up'),b=trials('tactical',0,'fastball');return a.hits>b.hits*1.15&&a.hits<6000;});
  check('Power trades fewer contacts for more home runs',()=>{const a=trials('tactical',0,'change-up','contact'),b=trials('tactical',0,'change-up','power');return b.contact<a.contact&&b.hr>a.hr;});
  check('Contact and power stats make distinct builds useful',()=>{const a=trials('tactical',0,'change-up','contact',{contact:75,power:40}),b=trials('tactical',0,'change-up','power',{contact:48,power:75});return a.hits>b.hits&&b.hr>a.hr;});
  check('Plain-language timing feedback explains early and late change-ups',()=>{const p={type:'change-up',skill:54,inZone:true},stats={contact:58,power:50};return d.resolvePitch(d.newGame(),stats,p,{mode:'timing',timing:.5}).text.includes('early on the change-up')&&d.resolvePitch(d.newGame(),stats,p,{mode:'timing',timing:1.4}).text.includes('late on the change-up');});
  check('Seeded games are reproducible, independent of rendering',()=>{const a=d.newGame(812),b=d.newGame(812);for(const g of [a,b])d.simulateToMoment(g,{contact:58,power:50,discipline:55},d.DC.pitchers[0],2,true);return JSON.stringify(a)===JSON.stringify(b);});
  let batch=[];
  check('400 simulated games finish with legal totals, untied scores and credible run ranges',()=>{
    for(let i=1;i<=400;i++){const g=d.newGame(i*293);d.simulateToMoment(g,{contact:58,power:50,discipline:55},d.DC.pitchers[i%3],2,true);assert(g.finished&&g.inning>=9&&g.score[0]!==g.score[1],'game '+i+' final');assert(g.count.balls===0&&g.count.strikes===0,'final count');for(let t=0;t<2;t++){const s=g.totals[t];assert(s.pa===s.ab+s.walks&&s.hits<=s.ab&&s.hr<=s.hits&&s.k<=s.ab,'totals');assert(s.runs===g.score[t]&&s.rbi===g.score[t],'score agrees');}batch.push(g);}
    const mean=batch.reduce((n,g)=>n+g.score[0]+g.score[1],0)/batch.length;assert(mean>3&&mean<18,'combined runs/game '+mean.toFixed(2));return true;
  });
  function playSeries(s,mode='tactical'){
    s.mode=mode;while(s.played<6){d.startMatch(s);let guard=0;while(s.phase!=='summary'){
      assert(++guard<1000,'career game loop');if(s.phase==='pitch'){const p=s.active.pitch;d.playPitch(s,{take:!p.inZone,mode,timing:1,guess:p.hint,stance:s.stance});}else d.continueMatch(s);
    }d.afterMatch(s);}return s;
  }
  for(const mode of ['timing','tactical'])check(mode+' career plays six games, reaches two offers and accounts each game once',()=>{const s=d.freshCareer(2871);d.startCareer(s,'Test','left',2);playSeries(s,mode);return s.phase==='offers'&&s.history.length===6&&s.record.pa===s.history.reduce((n,h)=>n+h.hero.pa,0)&&s.active===null&&s.day===7;});
  for(const build of ['contact','power'])check(build+' build can earn the transparent call-up',()=>{let promoted=0;for(let i=1;i<=12;i++){const s=d.freshCareer(i*191);d.startCareer(s,'Test','right',0);s.stats[build]=75;s.stance=build;playSeries(s);if(d.evaluation(s).earned)promoted++;}return promoted>=9;});
  check('A slump gets a paid development offer, with the same visible future target',()=>{const s=d.freshCareer();d.startCareer(s,'Test','right',0);s.phase='offers';s.season={...d.lineStats(),pa:25,ab:25,hits:1};assert(!d.evaluation(s).earned,'slump');return d.signContract(s,'starts')&&s.contract.tier==='Development club'&&s.cash===180;});
  check('Preparation applies once per game and repeated requests cannot farm stats',()=>{const s=d.freshCareer();d.startCareer(s,'Test','right',0);d.training(s,'contact');const before=JSON.stringify(s);return !d.training(s,'power')&&JSON.stringify(s)===before&&s.stats.contact===60;});
  check('Preparation survives reload, so reloading cannot grant another session',()=>{const s=d.freshCareer();d.startCareer(s,'Test','right',0);d.training(s,'contact');const loaded=d.migrateCareer(clone(s));return loaded.prepared&&!d.training(loaded,'contact')&&loaded.stats.contact===60;});
  check('Rest clears fatigue and the next match allows a new preparation',()=>{const s=d.freshCareer();d.startCareer(s,'Test','right',0);s.fatigue=30;d.training(s,'rest');assert(s.fatigue===0,'rest');d.startMatch(s);return !s.prepared;});
  function offered(id){const s=d.freshCareer(223);d.startCareer(s,'Test','right',0);s.phase='offers';s.season={...d.lineStats(),hits:6,ab:20,pa:24,walks:4};d.signContract(s,id);return s;}
  check('Two offers exchange higher total pay for fewer playable opportunities',()=>{const a=d.DC.offers.wage,b=d.DC.offers.starts;return a.bonus+a.wage*3>b.bonus+b.wage*3&&a.moments<b.moments;});
  check('Contract bonus pays once; repeated signing does nothing',()=>{const s=offered('wage'),before=JSON.stringify(s);return s.cash===320&&!d.signContract(s,'starts')&&JSON.stringify(s)===before&&s.contract.tier==='Senior club';});
  check('Salary is paid on due dates, not renders or wall-clock time',()=>{const s=offered('starts'),start=s.day;d.advanceDays(s,1);assert(s.cash===180,'too early');d.advanceDays(s,1);assert(s.cash===350,'first salary');d.advanceDays(s,3);assert(s.cash===520,'second salary');d.advanceDays(s,1);return s.cash===690&&s.ledger.filter(e=>e.id.startsWith('salary-')).every((e,i)=>e.day===start+[2,4,6][i]);});
  check('Skipping dates catches up once without duplicating salary after reload',()=>{const s=offered('wage');d.advanceDays(s,10);const loaded=d.migrateCareer(clone(s));d.advanceDays(loaded,10);return loaded.cash===1040&&loaded.ledger.length===4;});
  check('A calendar day does not expire purchases or charge upkeep',()=>{const s=offered('wage');d.advanceDays(s,8);d.purchase(s,'apartment');d.purchase(s,'car');const cash=s.cash;d.advanceDays(s,30);return s.cash===cash&&s.owned.apartment&&s.owned.car;});
  check('Purchases reject insufficient funds and duplicate spending',()=>{const s=offered('starts');assert(!d.purchase(s,'car')&&s.cash===180,'insufficient');d.advanceDays(s,4);assert(d.purchase(s,'car'),'affordable');const cash=s.cash;return !d.purchase(s,'car')&&s.cash===cash&&s.owned.car;});
  for(const id of ['wage','starts'])check(id+' contract changes actual manual at-bats in the next six games',()=>{const s=offered(id);playSeries(s);return s.history.length===6&&s.history.every(h=>h.manual<=d.DC.offers[id].moments)&&s.history.reduce((n,h)=>n+h.manual,0)>=d.DC.offers[id].moments*5;});
  check('An empty/old partial save receives safe defaults',()=>{for(const old of [null,{}, {game:'diamond-career',player:{name:'Old','bats':'left',look:1},phase:'clubhouse',cash:12}]){const s=d.migrateCareer(old);assert(d.validCareer(s)&&s.sound===0&&s.ledger.length===0,'defaults');}return true;});
  check('A different game or malformed save cannot become a career',()=>!d.validCareer({game:'wildbond',schema:1})&&!d.validCareer([])&&d.migrateCareer({game:'wildbond',cash:500}).phase==='creator');
  check('A mid-at-bat save preserves pitch, RNG, count and bases across modes',()=>{const s=d.freshCareer(581);d.startCareer(s,'Test','left',3);d.startMatch(s);d.playPitch(s,{take:true});d.continueMatch(s);const a=d.migrateCareer(clone(s));const p=JSON.stringify(a.active);a.mode='tactical';return p===JSON.stringify(s.active)&&a.player.bats==='left'&&a.player.look===3;});
  check('Switching style preserves the current pitch and count through real Settings callbacks',()=>{const s=d.freshCareer(119);d.startCareer(s,'Test','right',0);d.startMatch(s);d.S=s;const before=JSON.stringify(s.active);document.querySelector('.arc-set-btn').click();document.querySelector('.arc-set [data-r="0"][data-o="1"]').click();document.querySelector('.arc-set [data-close]').click();return d.S.mode==='tactical'&&JSON.stringify(d.S.active)===before;});
  check('Tactical patience makes an eye check and completes a pitch via the real control',()=>{const s=d.freshCareer(779);d.startCareer(s,'Test','right',0);d.startMatch(s);s.mode='tactical';s.stance='patience';d.S=s;d.actCareer('tactical');return s.phase==='result'&&typeof s.active.last.take==='boolean';});
  check('Completed result reload cannot credit a game twice',()=>{const s=d.freshCareer(931);d.startCareer(s,'Test','right',0);d.startMatch(s);d.simulateToMoment(s.active.g,s.stats,s.active.pitcher,2,true);s.phase='result';s.active.last={ended:true,text:'Game over.'};d.continueMatch(s);const first=s.record.pa,loaded=d.migrateCareer(clone(s));loaded.phase='result';d.continueMatch(loaded);return loaded.record.pa===first&&loaded.played===1;});
  check('Malformed nested save data is rejected safely before rendering',()=>{const s=offered('wage');s.stats.contact='broken';assert(!d.validCareer(s),'invalid stats');return d.migrateCareer(s).phase==='creator';});
  check('Signed clubs never play themselves',()=>{for(const id of ['wage','starts']){const s=offered(id);for(let i=0;i<6;i++){s.played=i;s.phase='home';d.startMatch(s);assert(s.active.opponent!==d.DC.offers[id].name,'self match');}}return true;});
  check('Real shared save/load retains salary, possessions and profile; validator accepts it',()=>{const s=offered('wage');d.advanceDays(s,6);d.purchase(s,'car');d.S=s;d.saveCareer();const loaded=d.migrateCareer(Arcade.load(d.DC.key));return d.validCareer(loaded)&&loaded.owned.car&&loaded.cash===620&&loaded.player.name==='Test'&&loaded.ledger.length===5&&Arcade.readIndex().baseball;});
  check('Save tools expose file download/import and the generated backups',()=>Arcade.saveToolsHTML(d.DC.key).includes('data-arcsave="download"')&&Arcade.backups(d.DC.key).length>=1);
  check('Both original tracks are valid shared-engine note strings',()=>Object.values(d.DC_TRACKS).every(t=>t.bpm>50&&t.bpm<180&&t.mel.split(' ').every(n=>n==='.'||/^[A-G]#?[0-8]$/.test(n))));
  check('The UI escapes player names instead of inserting markup',()=>{const s=d.freshCareer();d.startCareer(s,'<img src=x>','left',0);d.S=s;d.renderCareer();return !document.querySelector('#content img')&&document.querySelector('#content h1').textContent==='<img src=x>';});
  return out;
}
