/* Run: node tests/realmbound-3d.cjs [origin]. Isolated contexts; never reads player saves. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const origin=process.argv[2]||'http://localhost:8766',out=path.join(__dirname,'../docs/screenshots/realmbound-3d');fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});let checks=0;const check=(ok,label)=>{assert.ok(ok,label);checks++;};try{
 for(const [width,height]of [[375,812],[1366,768],[1920,1080],[3440,1440]]){
  const context=await browser.newContext({viewport:{width,height},serviceWorkers:'block',reducedMotion:'reduce',hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await context.addInitScript(()=>{localStorage.setItem('rb','untouched-test-save');localStorage.setItem('wildbond','untouched-test-save');window.saveWrites=[];for(const method of ['setItem','removeItem','clear']){const old=Storage.prototype[method];Storage.prototype[method]=function(...args){window.saveWrites.push(method);return old.apply(this,args);};}});
  await page.goto(origin+'/experiments/realmbound-3d/');await page.waitForFunction(()=>window.__rb3d);await page.waitForTimeout(350);
  check(await page.evaluate(()=>__rb3d.renderer.shadowMap.enabled&&__rb3d.camera.isPerspectiveCamera),'real perspective and shadow maps');
  const shape=await page.evaluate(()=>{const a=__rb3d;return {hero:new THREE.Box3().setFromObject(a.hero).getSize(new THREE.Vector3()).y,bed:a.dimensions.bed,wall:a.dimensions.wall};});check(shape.hero>1.6&&shape.hero<1.9&&shape.bed>shape.hero&&shape.wall>shape.hero,'physical people, bed and wall dimensions');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no sideways overflow');
  await page.screenshot({path:path.join(out,'inn-'+width+'.png')});
  await page.evaluate(()=>{__rb3d.state.yaw=0;});const start=await page.evaluate(()=>__rb3d.hero.position.z);await page.keyboard.down('w');await page.waitForTimeout(450);await page.keyboard.up('w');check(await page.evaluate(z=>__rb3d.hero.position.z<z-.3,start),'actual keyboard walking');
  await page.evaluate(()=>{__rb3d.teleport(-2,-1.4);__rb3d.state.yaw=0;});await page.keyboard.down('w');await page.waitForTimeout(650);await page.keyboard.up('w');check(await page.evaluate(()=>__rb3d.hero.position.z>-1.91),'cannot walk through Merran');
  check(await page.evaluate(()=>__rb3d.isBlocked(-5,-3)&&__rb3d.isBlocked(0,-5.15)&&!__rb3d.isBlocked(0,0)),'beds and hearth have solid footprints, central aisle is clear');
  for(const yaw of [0,Math.PI/2,Math.PI,Math.PI*1.5])check(await page.evaluate(y=>{const a=__rb3d;a.teleport(5.9,4.9);a.state.yaw=y;a.update(0,0);return Math.abs(a.camera.position.x)<=6.61&&Math.abs(a.camera.position.z)<=5.61&&a.camera.position.y<=3.06;},yaw),'orbit camera stays inside the room');
  await page.evaluate(()=>{__rb3d.teleport(-2,-1.3);__rb3d.state.yaw=0;});await page.getByRole('button',{name:'Interact',exact:true}).click();check(await page.evaluate(()=>!!__rb3d.state.dialogue),'shared portrait dialogue opens beside Merran');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.waitForFunction(()=>!__rb3d.state.dialogue);
  await page.evaluate(()=>__rb3d.teleport(0,5));await page.getByRole('button',{name:'Interact',exact:true}).click();check(await page.evaluate(()=>__rb3d.state.outside),'door exits to landing');
  if(width===1920){await page.waitForTimeout(200);await page.screenshot({path:path.join(out,'outside-1920.png')});}
  await page.evaluate(()=>__rb3d.teleport(0,-3.2));await page.getByRole('button',{name:'Interact',exact:true}).click();check(await page.evaluate(()=>!__rb3d.state.outside),'door returns to inn');
  await page.evaluate(()=>{__rb3d.teleport(0,1.5);__rb3d.state.yaw=0;});const button=page.getByRole('button',{name:'Walk forward',exact:true});const bounds=await button.boundingBox(),cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:bounds.x+bounds.width/2,y:bounds.y+bounds.height/2}]});await page.waitForTimeout(350);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();check(await page.evaluate(()=>__rb3d.hero.position.z<1.3),'touch movement control walks');
  const stationary=await page.evaluate(()=>__rb3d.hero.position.z);await page.waitForTimeout(200);check(await page.evaluate(z=>Math.abs(__rb3d.hero.position.z-z)<.001,stationary),'movement stops when touch is released');
  check(await page.evaluate(()=>saveWrites.length===0&&localStorage.getItem('rb')==='untouched-test-save'&&localStorage.getItem('wildbond')==='untouched-test-save'),'trial never changes saves');check(errors.length===0,'no page errors: '+errors.join(';'));await context.close();console.log('ok',width+'x'+height);
 }
 // Normal motion, real camera gestures and front/back presentation.
 const animated=await browser.newContext({viewport:{width:1920,height:1080},serviceWorkers:'block'}),ap=await animated.newPage();await ap.goto(origin+'/experiments/realmbound-3d/');await ap.waitForFunction(()=>window.__rb3d);
 const yaw=await ap.evaluate(()=>__rb3d.state.yaw);await ap.mouse.move(900,400);await ap.mouse.down();await ap.mouse.move(1010,430,{steps:5});await ap.mouse.up();check(await ap.evaluate(y=>Math.abs(__rb3d.state.yaw-y)>.2,yaw),'actual pointer drag orbits camera');const distance=await ap.evaluate(()=>__rb3d.state.distance);await ap.mouse.wheel(0,-120);check(await ap.evaluate(d=>__rb3d.state.distance<d,distance),'wheel adjusts camera distance');await ap.getByRole('button',{name:'Reset view',exact:true}).click();
 await ap.keyboard.down('w');await ap.waitForTimeout(160);const pose=await ap.evaluate(()=>__rb3d.hero.userData.legs[0].rotation.x);await ap.waitForTimeout(180);check(await ap.evaluate(p=>Math.abs(__rb3d.hero.userData.legs[0].rotation.x-p)>.05,pose),'walking animates 3D limbs');await ap.keyboard.up('w');await ap.waitForTimeout(100);check(await ap.evaluate(()=>__rb3d.hero.userData.legs[0].rotation.x===0),'idle legs stop marching');
 await ap.evaluate(()=>{__rb3d.teleport(0,0);__rb3d.state.yaw=Math.PI;});await ap.waitForTimeout(100);await ap.screenshot({path:path.join(out,'front-1920.png')});await animated.close();
 // Library failure is readable rather than a blank scene.
 const context=await browser.newContext({serviceWorkers:'block'}),p=await context.newPage();await p.route('**/three.min.js',r=>r.abort());await p.goto(origin+'/experiments/realmbound-3d/');check((await p.textContent('#loading')).includes('could not load'),'CDN failure explains how to return to the working game');await context.close();
 console.log('PASS — '+checks+' third-person trial checks.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});