/* Run: node tests/realmbound-3d.cjs [origin]. Isolated contexts; never reads player saves. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const origin=process.argv[2]||'http://localhost:8766',out=path.join(__dirname,'../docs/screenshots/realmbound-3d');fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});let checks=0;const check=(ok,label)=>{assert.ok(ok,label);checks++;};try{
 for(const [width,height]of [[375,812],[1366,768],[1920,1080],[3440,1440]]){
  const context=await browser.newContext({viewport:{width,height},serviceWorkers:'block',reducedMotion:'reduce',hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await context.addInitScript(()=>{localStorage.setItem('rb','untouched-test-save');localStorage.setItem('wildbond','untouched-test-save');window.saveWrites=[];for(const method of ['setItem','removeItem','clear']){const old=Storage.prototype[method];Storage.prototype[method]=function(...args){window.saveWrites.push(method);return old.apply(this,args);};}});
  await page.goto(origin+'/experiments/realmbound-3d/');await page.waitForFunction(()=>window.__rb3d);await page.waitForTimeout(350);
  check(await page.evaluate(()=>__rb3d.renderer.shadowMap.enabled&&__rb3d.camera.isPerspectiveCamera),'real perspective and shadow maps');
  const shape=await page.evaluate(()=>{const a=__rb3d;return {hero:new THREE.Box3().setFromObject(a.hero).getSize(new THREE.Vector3()).y,bed:a.dimensions.bed,wall:a.dimensions.wall};});check(shape.hero>1.6&&shape.hero<1.9&&shape.bed>shape.hero&&shape.wall>shape.hero,'physical people, bed and wall dimensions');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no sideways overflow');
  await page.screenshot({path:path.join(out,'inn-'+width+'.png')});
  const outfitBounds=await page.getByRole('button',{name:'Outfits',exact:true}).boundingBox();check(outfitBounds.x>=0&&outfitBounds.x+outfitBounds.width<=width,'outfit button fits the viewport');
  await page.getByRole('button',{name:'Outfits',exact:true}).click();const mageBounds=await page.getByRole('button',{name:'Mage kit',exact:true}).boundingBox();check(mageBounds&&mageBounds.y+mageBounds.height<=height,'outfit choices fit the game window');await page.getByRole('button',{name:'Hunter kit',exact:true}).click();check(await page.evaluate(()=>__rb3d.hero.userData.gearDescriptors.weapon.type==='bow'),'outfit preview works at this viewport');await page.screenshot({path:path.join(out,'gear-hunter-'+width+'.png')});await page.evaluate(()=>RealmTrialGear.apply(__rb3d.hero,{}));
  await page.evaluate(()=>{__rb3d.state.yaw=0;});const start=await page.evaluate(()=>__rb3d.hero.position.z);await page.keyboard.down('w');await page.waitForTimeout(450);await page.keyboard.up('w');check(await page.evaluate(z=>__rb3d.hero.position.z<z-.3,start),'actual keyboard walking');
  await page.evaluate(()=>{__rb3d.teleport(-2,-1.4);__rb3d.state.yaw=0;});await page.keyboard.down('w');await page.waitForTimeout(650);await page.keyboard.up('w');check(await page.evaluate(()=>__rb3d.hero.position.z>-1.91),'cannot walk through Merran');
  check(await page.evaluate(()=>__rb3d.isBlocked(-5,-3)&&__rb3d.isBlocked(0,-5.15)&&!__rb3d.isBlocked(0,0)),'beds and hearth have solid footprints, central aisle is clear');
  for(const yaw of [0,Math.PI/2,Math.PI,Math.PI*1.5])check(await page.evaluate(y=>{const a=__rb3d;a.teleport(5.9,4.9);a.state.yaw=y;a.update(0,0);return Math.abs(a.camera.position.x)<=6.61&&Math.abs(a.camera.position.z)<=5.61&&a.camera.position.y<=3.06;},yaw),'orbit camera stays inside the room');
  await page.evaluate(()=>{__rb3d.teleport(-2,-1.3);__rb3d.state.yaw=0;});await page.getByRole('button',{name:'Interact',exact:true}).click();check(await page.evaluate(()=>!!__rb3d.state.dialogue),'shared portrait dialogue opens beside Merran');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.waitForFunction(()=>!__rb3d.state.dialogue);
  await page.evaluate(()=>__rb3d.teleport(0,5));await page.getByRole('button',{name:'Interact',exact:true}).click();check(await page.evaluate(()=>__rb3d.state.outside),'door exits to landing');
  if(width===1920){await page.waitForTimeout(200);await page.screenshot({path:path.join(out,'outside-1920.png')});}
  await page.evaluate(()=>__rb3d.teleport(0,-3.2));await page.getByRole('button',{name:'Interact',exact:true}).click();check(await page.evaluate(()=>!__rb3d.state.outside),'door returns to inn');
  await page.evaluate(()=>{__rb3d.teleport(0,1.5);__rb3d.state.yaw=0;});const button=page.getByRole('button',{name:'Walk forward',exact:true});const bounds=await button.boundingBox(),cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:bounds.x+bounds.width/2,y:bounds.y+bounds.height/2}]});await page.waitForTimeout(350);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();check(await page.evaluate(()=>__rb3d.hero.position.z<1.3),'touch movement control walks');
  const stationary=await page.evaluate(()=>__rb3d.hero.position.z);await page.waitForTimeout(200);check(await page.evaluate(z=>Math.abs(__rb3d.hero.position.z-z)<.001,stationary),'movement stops when touch is released');
  check(await page.evaluate(()=>saveWrites.length===0&&localStorage.getItem('rb')==='untouched-test-save'&&localStorage.getItem('wildbond')==='untouched-test-save'),'trial never changes saves');check(errors.length===0,'no page errors: '+errors.join(';'));await context.close();console.log('ok',width+'x'+height);
 }
 // Normal motion, real camera gestures and front/back presentation.
 const animated=await browser.newContext({viewport:{width:1920,height:1080},serviceWorkers:'block'}),ap=await animated.newPage();await ap.goto(origin+'/experiments/realmbound-3d/');await ap.waitForFunction(()=>window.__rb3d);
 const yaw=await ap.evaluate(()=>__rb3d.state.yaw);await ap.mouse.move(900,400);await ap.mouse.down();await ap.mouse.move(1010,430,{steps:5});await ap.mouse.up();check(await ap.evaluate(y=>Math.abs(__rb3d.state.yaw-y)>.2,yaw),'actual pointer drag orbits camera');const distance=await ap.evaluate(()=>__rb3d.state.distance);await ap.mouse.wheel(0,-120);check(await ap.evaluate(d=>__rb3d.state.distance<d,distance),'wheel adjusts camera distance');await ap.getByRole('button',{name:'Reset view',exact:true}).click();
 await ap.keyboard.down('w');const poses=[];for(let i=0;i<6;i++){await ap.waitForTimeout(90);poses.push(await ap.evaluate(()=>__rb3d.hero.userData.legs[0].rotation.x));}check(Math.max(...poses)-Math.min(...poses)>.08,'walking animates 3D limbs across several frames');await ap.keyboard.up('w');await ap.waitForTimeout(100);check(await ap.evaluate(()=>__rb3d.hero.userData.legs[0].rotation.x===0),'idle legs stop marching');
 await ap.evaluate(()=>{__rb3d.teleport(0,0);__rb3d.state.yaw=Math.PI;});await ap.waitForTimeout(100);await ap.screenshot({path:path.join(out,'front-1920.png')});await animated.close();
 const rigContext=await browser.newContext({viewport:{width:1366,height:768},serviceWorkers:'block'}),rp=await rigContext.newPage();await rp.goto(origin+'/experiments/realmbound-3d/');await rp.waitForFunction(()=>window.__rb3d);
 check(await rp.evaluate(()=>{const g=RealmTrialCharacters.create(),size=o=>new THREE.Box3().setFromObject(o).getSize(new THREE.Vector3()).y;const ratio=size(g)/size(g.userData.head);return ratio>5&&ratio<6;}),'adult stylized body is between five and six head heights');
 const footSamples=await rp.evaluate(()=>{const g=RealmTrialCharacters.create(),out=[];for(let i=0;i<16;i++){RealmTrialCharacters.animate(g,{walking:true,phase:i/16*Math.PI*2,time:0});g.updateMatrixWorld(true);out.push(g.userData.feet.map(f=>new THREE.Box3().setFromObject(f).min.y));}return out;});for(const [i,feet]of footSamples.entries()){check(feet.every(y=>y>=-.008),'feet never sink through floor at stride '+i);check(Math.min(...feet)<.035,'one stance foot stays planted at stride '+i);}
 const stancePositions=await rp.evaluate(()=>{const g=RealmTrialCharacters.create(),out=[];for(let i=0;i<8;i++){const cycle=i/16;g.position.z=cycle*.76;RealmTrialCharacters.animate(g,{walking:true,phase:cycle*Math.PI*2,time:0});g.updateMatrixWorld(true);out.push(g.userData.feet[0].getWorldPosition(new THREE.Vector3()).z);}return out;});for(const [i,z]of stancePositions.entries())check(Math.abs(z-stancePositions[0])<.002,'stance foot stays on the same world position at step '+i);
 check(await rp.evaluate(()=>{const g=RealmTrialCharacters.create(),r=g.userData,joints=()=>[...r.arms,...r.elbows,...r.legs,...r.knees,...r.feet].map(o=>o.rotation.toArray().join(',')).join('|');RealmTrialCharacters.animate(g,{walking:true,phase:0,time:0,reduced:true});const a=joints();RealmTrialCharacters.animate(g,{walking:true,phase:3,time:5,reduced:true});return a===joints()&&r.upper.position.y===0;}),'reduced motion freezes joints and breathing');
 await rp.evaluate(()=>{__rb3d.teleport(-2,-1.91);__rb3d.state.yaw=0;});await rp.keyboard.down('w');await rp.waitForTimeout(250);await rp.keyboard.up('w');check(await rp.evaluate(()=>!__rb3d.state.moving&&__rb3d.hero.userData.legs.every(l=>l.rotation.x===0)),'blocked walking stops rather than marching into a person');
 await rp.evaluate(()=>__rb3d.teleport(-2,-1.3));await rp.getByRole('button',{name:'Interact',exact:true}).click();await rp.waitForTimeout(550);check(await rp.evaluate(()=>{const h=__rb3d.hero,k=__rb3d.keeper;const facing=(a,b)=>{const v=new THREE.Vector3(0,0,1).applyAxisAngle(new THREE.Vector3(0,1,0),a.rotation.y),to=b.position.clone().sub(a.position).normalize();return v.dot(to)>.95;};return facing(h,k)&&facing(k,h);}), 'conversation turns both people toward each other');check(await rp.evaluate(()=>__rb3d.keeper.userData.elbows[1].rotation.x<-.5),'Keeper uses a restrained talking gesture');await rp.keyboard.press('Escape');await rigContext.close();
 // Equipment previews use the actual gear field shape without touching item rules or storage.
 const ec=await browser.newContext({viewport:{width:1920,height:1080},serviceWorkers:'block',reducedMotion:'reduce'}),ep=await ec.newPage();await ep.goto(origin+'/experiments/realmbound-3d/');await ep.waitForFunction(()=>window.__rb3d);
 await ep.getByRole('button',{name:'Outfits',exact:true}).click();await ep.getByRole('button',{name:'Warrior kit'}).click();
 check(await ep.evaluate(()=>Object.keys(__rb3d.hero.userData.gearDescriptors).length===8),'real outfit controls equip all eight slots');
 check(await ep.evaluate(()=>{const r=__rb3d.hero.userData,b=new THREE.Box3().setFromObject(r.gearVisuals.chest[0].clone()).getSize(new THREE.Vector3());return b.y<.7&&b.x<.7;}),'chest armour stays torso-sized rather than stretching across the face');
 check(await ep.evaluate(()=>{const out=[];__rb3d.hero.userData.head.traverse(o=>{if(o.name==='hair')out.push(o.visible);});return out.length>0&&out.every(v=>!v);}),'helmet hides hair that would clip through it');
 check(await ep.evaluate(()=>__rb3d.hero.userData.gearDescriptors.weapon.id==='gear/weapon/sword'&&__rb3d.hero.userData.gearDescriptors.offhand.type==='shield'),'Warrior carries sword and shield');
 await ep.evaluate(()=>{__rb3d.teleport(0,0);__rb3d.state.yaw=0;__rb3d.hero.rotation.y=0;__rb3d.state.distance=3.6;});await ep.waitForTimeout(150);await ep.screenshot({path:path.join(out,'gear-warrior-1920.png')});
 for(const preset of ['Hunter kit','Mage kit','Travel clothes']){await ep.getByRole('button',{name:'Outfits',exact:true}).click();await ep.getByRole('button',{name:preset,exact:true}).click();const count=await ep.evaluate(()=>Object.keys(__rb3d.hero.userData.gearDescriptors).length);check(count===(preset==='Travel clothes'?0:8),preset+' replaces all equipment without duplicates');if(preset!=='Travel clothes'){await ep.waitForTimeout(100);await ep.screenshot({path:path.join(out,'gear-'+preset.split(' ')[0].toLowerCase()+'-1920.png')});}}
 check(await ep.evaluate(()=>{const h=__rb3d.hero;RealmTrialGear.apply(h,RealmTrialGear.presets[1].gear);const r=h.userData;return r.gearSockets.chest[1].parent===r.arms[0]&&r.gearSockets.chest[2].parent===r.arms[1];}),'shoulder armour follows each shoulder joint');
 check(await ep.evaluate(()=>{const h=RealmTrialCharacters.create();RealmTrialGear.apply(h,RealmTrialGear.presets[1].gear);for(let i=0;i<16;i++){RealmTrialCharacters.animate(h,{walking:true,phase:i/16*Math.PI*2});h.updateMatrixWorld(true);if(new THREE.Box3().setFromObject(h.userData.gearVisuals.weapon[0]).min.y<0)return false;}return true;}),'downward sword stays above the floor throughout the walk cycle');
 const result=await ep.evaluate(()=>{const G=RealmTrialGear,h=__rb3d.hero,r=h.userData,gear=G.presets[1].gear,before=JSON.stringify(gear);G.apply(h,gear);G.apply(h,gear);const counts=Object.values(r.gearSockets).flat().map(s=>s.children.length);const mounted=r.gearSockets.weapon[0].parent===r.elbows[1]&&r.gearSockets.offhand[0].parent===r.elbows[0]&&r.gearSockets.head[0].parent===r.head&&r.gearSockets.feet.every((s,i)=>s.parent===r.feet[i]);const unchanged=JSON.stringify(gear)===before;const id=G.profile('weapon',{wtype:'sword',name:'Renamed sword',rar:4}).id===G.profile('weapon',gear.weapon).id;const bad=G.profile('weapon',{wtype:'future-type'});G.apply(h,{weapon:{wtype:'future-type'}});const fallback=r.gearDescriptors.weapon.id===bad.id&&r.gearVisuals.weapon[0].children.length>0;let types=true;for(const wtype of ['sword','dagger','mace','staff','bow']){G.apply(h,{weapon:{wtype}});types&&=r.gearDescriptors.weapon.type===wtype&&r.gearVisuals.weapon[0].children.length>0;}for(const otype of ['shield','tome','dagger']){G.apply(h,{offhand:{otype}});types&&=r.gearDescriptors.offhand.type===otype&&r.gearVisuals.offhand[0].children.length>0;}G.apply(h,{});return {counts,mounted,unchanged,id,fallback,types,cleared:Object.values(r.gearSockets).flat().every(s=>!s.children.length)};});
 check(result.counts.every(n=>n===1),'repeated equip never accumulates meshes');check(result.mounted,'equipment sockets follow head, hands and feet joints');check(result.unchanged,'render adapter does not mutate source items');check(result.id,'visual identity does not depend on item name or rarity');check(result.fallback,'unsupported types have explicit visible fallback');check(result.types,'all existing weapon and offhand types have visible art');check(result.cleared,'unequipping restores travel clothes and removes every gear mesh');await ec.close();
 // Library failure is readable rather than a blank scene.
 const context=await browser.newContext({serviceWorkers:'block'}),p=await context.newPage();await p.route('**/three.min.js',r=>r.abort());await p.goto(origin+'/experiments/realmbound-3d/');check((await p.textContent('#loading')).includes('could not load'),'CDN failure explains how to return to the working game');await context.close();
 console.log('PASS — '+checks+' third-person trial checks.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});