/* T46: separate editions, separate progress. Preview IDs intentionally have no browser save keys.
   Scope/controls come from the current game READMEs; screenshots are existing recorded game frames. */
(function(){'use strict';
/* Sections (Evan, 2026-10-09: say what each game is like and which are similar). Order is the page order. */
window.ArcadeKinds=[
  {id:'adventure',name:'Adventures',like:'Explore a world on foot, meet people, fight and grow stronger. Wildbond is about catching and raising creatures; Realmbound is a classic MMO with quests and a guild.'},
  {id:'build',name:'Build and manage',like:'Run a place and the people in it: post jobs, earn coin, upgrade buildings and hire helpers who take work off your hands.'},
  {id:'sports',name:'Sports',like:'Sporting careers and teams. Diamond Career is an early baseball test; more sports and running a whole team are being planned.'},
  {id:'story',name:'Stories',like:'Read, choose and live with what you chose. Lives branch toward different endings.'},
  {id:'different',name:'Something different',like:'Small experiments that do not fit the others. Primordial is an idle game about evolving life from one cell.'},
];
window.ArcadeGames=[
  {id:'wildbond-preview',title:'Wildbond',tcls:'t-wildbond',status:['New version · Early preview','s-proto'],href:'play/wildbond/',
   blurb:'Walk into faded Larkhaven, choose a partner and bring colour back with your first bond. Explore all eight regions and take on the league: four courts and the Champion, meet their Wardens, and care for creatures at the ranch.',
   tags:['On foot','Eight regions and the league','Ranch & nursery'],cover:'wildbond',preview:true,classic:'wildbond',image:'images/play/wb-barn.png',
   alt:'Wildbond preview: the barn, with creatures, a feeding trough and the nursery',
   goal:'Walk into faded Larkhaven, choose a partner and bond with creatures to bring the colour back.',
   controls:'Arrows or WASD to walk · Enter or E to talk · J for the field book · M for music.',
   load:'Best on a computer. The first load needs internet and may take a moment.',
   kind:'adventure'},
  {id:'starfall-preview',title:'Starfall Guild',tcls:'t-starfall',status:['New version · Early preview','s-proto'],href:'play/starfall/',
   blurb:'Build a frontier guild town. Post jobs for adventurers, serve meals at the inn, work the forge and grow the town with a healer, training yard and apothecary.',
   tags:['Guild village','Hands-on work','Earned helpers'],cover:'starfall',preview:true,classic:'starfall-guild',image:'images/play/sf-town.png',
   alt:'Starfall preview: the Guild Hall, inn, Smithy, Apothecary, Healer’s Hut and Training Yard',
   goal:'Grow a frontier guild town: post jobs for adventurers, cook at the inn, work the forge, then hire help.',
   controls:'Arrows, WASD or a click to walk · Enter or E to use a place · M for music.',
   load:'Best on a computer. The first load needs internet and may take a moment.',
   kind:'build'},
  {id:'primordial',title:'Primordial',tcls:'t-primordial',status:['Playable','s-play'],href:'games/primordial/index.html',
   blurb:'Grow from a single cell. Evolve instincts that play for you, draft random mutations, and restart through extinctions for permanent progress.',
   tags:['Evolution','Idle','Roguelike runs'],cover:'primordial',
   kind:'different',goal:'Feed a single cell until it can evolve, pick mutations, and survive extinctions that make your next run stronger.',controls:'Mouse or tap only: click the pool to feed, then pick from the buttons and tabs.'},
  {id:'starfall-guild',title:'Starfall Guild Classic',tcls:'t-starfall',status:['Prototype','s-proto'],href:'games/starfall-guild/index.html',
   blurb:'Run an adventurer guild. Recruit heroes, find class combos, push the dungeon, build up the town, and hire staff who manage it for you.',
   tags:['Guild sim','Autobattler','Pixel art'],cover:'starfall',
   kind:'build',goal:'Recruit heroes, send them into the dungeon, spend what they bring back on the town, then hire staff to run it.',controls:'Mouse or tap only: every action is a button. Your old guild save lives here.'},
  {id:'realmbound',title:'Realmbound',tcls:'t-mmo',status:['Beta','s-play'],href:'games/realmbound/index.html',
   blurb:'A classic-MMO adventure: pick a faction and a class, quest from level 1 to 60 through eight zones, clear four dungeons and their Heroic tiers, found a guild whose members work and fight beside you, and raid The Hollow Throne. Play it yourself or let Auto take over.',
   tags:['Classic MMO','Level 1–60','Guild & raid'],cover:'mmo',guide:'guides/realmbound.html',
   kind:'adventure',goal:'Make a hero, take quests in town, fight on the road and level up from 1 to 60.',controls:'Arrows or WASD (or tap) to walk · Enter to talk · in fights: C combo, D dodge, L loot all.'},
  {id:'wildbond',title:'Wildbond Classic',tcls:'t-wildbond',status:['Beta','s-play'],href:'games/wildbond/index.html',
   blurb:'Pick a partner, meet your rival Wren and walk from Larkhaven across eight regions, earning eight Warden badges on the way to the league and its Champion. Catch, raise and breed creatures, climb the Lighthouse Spire after the story, and watch a faded world grow from Game Boy greens into a 3D diorama.',
   tags:['Catch & raise','Evolving art','Full story'],cover:'wildbond',
   kind:'adventure',goal:'Choose a partner creature, catch and raise more, and beat the eight Wardens.',controls:'Arrows or WASD (or tap) to walk · Shift to run once you have shoes · menus by mouse or tap.'},
  {id:'baseball',title:'Diamond Manager',tcls:'t-baseball',status:['Test version','s-proto'],href:'games/diamond-manager/index.html',
   blurb:'Take over the worst club in the league. Watch your games play out, set the batting order, trade with five rival clubs, sign free agents, re-sign or let go, and grow Lamplight Field with the gate money.',
   tags:['Baseball','Team manager','Trades & contracts'],cover:'baseball',
   kind:'sports',goal:'Take over the worst club in a six-club league and manage it through a thirty-game season: the batting order, trades, free agents and the ballpark.',controls:'Press Play ball (or Space) to watch the next game · open the Front office (or F) to change the team · everything else by mouse or tap.'},
  {id:'otherworld',title:'Otherworld',tcls:'t-otherworld',status:['Prototype','s-proto'],href:'games/otherworld/index.html',
   blurb:'Your old life ends. In the Between, the Archivist lets you choose your next world, each a different kind of story, and one gift with a cost. Live a life, make choices that branch, reach your ending, and carry soul memories into the next life.',
   tags:['Isekai','Story arcs','Reincarnation'],cover:'otherworld',
   kind:'story',goal:'Pick a new world and a gift, then make choices that branch your life toward one of several endings.',controls:'Mouse or tap to choose · Space or Enter for the highlighted choice.'},
];
})();
