/* Storm Front: original Saltmarsh harbour art, shared arcade sound and settings. */
(function(){'use strict';
 const M=StormModel,$=id=>document.getElementById(id),canvas=$('sea'),ctx=canvas.getContext('2d'),KEY='storm-front-save-v1';
 Arcade.validators[KEY]=o=>!!o&&o.v===1&&o.game==='storm-front'&&Array.isArray(o.scores);
 const raw=Arcade.load(KEY),valid=Arcade.validators[KEY](raw),save={v:1,game:'storm-front',scores:M.scores(valid?raw.scores:[]),sound:valid&&[0,1,2].includes(raw.sound)?raw.sound:0,scanlines:!!(valid&&raw.scanlines===true)};
 let state=null,demo=M.create(1,29),last=0,queuedFire=false,padPause=false,padMove=false,entry=0,entries=[],uiPhase='title';
 M.ready(demo);const keys=new Set(),pointers=new Map(),reduce=Settings.reduced();
 function persist(){return Arcade.save(KEY,save);}
 function scan(){document.body.classList.toggle('scanlines',save.scanlines&&!reduce);}scan();
 const audio=ArcadeSound.create({mode:()=>save.sound,setMode:v=>{save.sound=v;persist();},button:()=>$('sound'),musicKey:()=>state&&state.phase==='playing'&&!state.paused?'harbour':null,tracks:{harbour:{bpm:100,lead:'triangle',mel:'D5 . A4 . F5 E5 D5 . A4 . C5 . E5 . A4 .',bass:'D3 . D3 . F3 . F3 . C3 . C3 . A2 . A2 .',drum:'k . h . s . h .'}}});
 $('sound').addEventListener('click',()=>audio.cycle());audio.render();
 const settings=Settings.create({mount:'#settingsMount',rows:[{label:'Sound',options:[[0,'Off'],[1,'Effects'],[2,'Effects and music']],get:()=>save.sound,set:v=>{save.sound=v;persist();audio.render();audio.sfx('select');}},{label:'Scanlines',options:[[false,'Off'],[true,'On']],get:()=>save.scanlines,set:v=>{save.scanlines=v;scan();persist();},note:'A soft cabinet texture. Hidden with reduced motion.'}]});
 if(window.Feedback)Feedback.register('Storm Front','',()=>state?'player '+(state.active+1)+' of '+state.players.length+', wave '+M.current(state).wave+', '+M.current(state).score+' points':'title screen');
 settings.button.addEventListener('click',()=>{clearInput();if(state&&state.phase==='playing')pause();});
 function clearInput(){keys.clear();pointers.clear();queuedFire=false;}
 function table(){return '<table class="scores"><caption>Harbour high scores</caption><tbody>'+ (save.scores.length?save.scores.map((r,i)=>'<tr><td>'+String(i+1).padStart(2,'0')+'</td><th scope="row">'+r.name+'</th><td>'+String(r.score).padStart(6,'0')+'</td></tr>').join(''):'<tr><td>No scores yet. Light the harbour.</td></tr>')+'</tbody></table>';}
 function modal(title,body){clearInput();$('panel').innerHTML='<p class="eyebrow">SALTMARSH HARBOUR</p><h2 id="panelTitle">'+title+'</h2>'+body;$('curtain').hidden=false;canvas.inert=true;$('pause').hidden=true;document.querySelector('.touch-controls').inert=true;const first=$('panel').querySelector('button,input');if(first)first.focus();}
 function buttons(){return '<div class="actions"><button data-start="1">One player</button><button class="secondary" data-start="2">Two players · take turns</button></div>';}
 function title(){uiPhase='title';state=null;modal('Storm Front','<p>Clear the storm clouds before they reach the harbour. Your lighthouse beam can chip the sea wall, too.</p>'+buttons()+table()+'<p class="fine">Three lights per player. Gull: 150 points. Clouds speed up as you clear them.<br>Demo plays behind this window.</p>');}
 function start(count){state=M.create(count,(Date.now()>>>0));entries=[];entry=0;readyPanel();}
 function readyPanel(){uiPhase='ready';modal('Player '+(state.active+1)+' · get ready','<p>'+ (state.players.length===2?'Each player has their own score and three lights. Player 2 starts when Player 1 finishes.':'Keep the storm above the sea wall.')+'</p><div class="actions"><button data-launch>Light the harbour</button></div>');}
 function launch(){uiPhase='playing';M.ready(state);state.paused=false;$('curtain').hidden=true;canvas.inert=false;document.querySelector('.touch-controls').inert=false;$('pause').hidden=false;canvas.focus();clearInput();last=performance.now();}
 function pause(){if(!state||state.phase!=='playing')return;state.paused=true;modal('Harbour paused','<div class="actions"><button data-resume>Resume</button><button class="secondary" data-title>Finish this run</button></div><p class="fine">Unfinished runs do not enter the high-score table.</p>');}
 function finish(){uiPhase='over';entries=state.players.map((p,i)=>({player:i+1,score:p.score})).filter(p=>p.score>0&&(save.scores.length<5||p.score>save.scores[save.scores.length-1].score));entry=0;nextScore();}
 function nextScore(){if(entry>=entries.length){modal('Harbour watch complete','<p>'+state.players.map((p,i)=>'Player '+(i+1)+': '+p.score+' points').join(' · ')+'</p>'+table()+buttons());return;}const p=entries[entry];modal('Player '+p.player+' · high score','<p>'+p.score+' points. Enter three initials for the harbour board.</p><form id="initialForm"><label for="initials">Your initials</label><input id="initials" name="initials" maxlength="3" pattern="[A-Za-z0-9]{3}" value="AAA" autocomplete="off" autocapitalize="characters" required aria-describedby="initialHint"><p id="initialHint" class="fine">Three letters or numbers. Saved on this device.</p><div class="actions"><button type="submit">Keep score</button><button type="button" class="secondary" data-skip>Skip</button></div></form>');$('initials').focus();$('initials').select();$('initialForm').addEventListener('submit',e=>{e.preventDefault();if(!$('initialForm').checkValidity())return;const value=$('initials').value;save.scores=M.record(save.scores,value,p.score);const kept=persist();if(kept)Arcade.report('storm-front',{summary:'Best: '+save.scores[0].score+' points',detail:'Saltmarsh harbour high scores'});entry++;nextScore();if(!kept)$('notice').textContent='Score kept for this visit. This browser could not save it.';});}
 $('panel').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.start)start(Number(b.dataset.start));else if(b.hasAttribute('data-launch')||b.hasAttribute('data-resume'))launch();else if(b.hasAttribute('data-title'))title();else if(b.hasAttribute('data-skip')){entry++;nextScore();}});
 $('pause').addEventListener('click',pause);
 const gameKey=k=>['arrowleft','arrowright','a','d',' '].includes(k);
 window.addEventListener('keydown',e=>{if(e.target.closest&&e.target.closest('input,button,a,select,textarea,.arc-set-bg'))return;const k=e.key.toLowerCase();if(k==='p'||k==='escape'){e.preventDefault();if(state&&state.paused)launch();else pause();return;}if(gameKey(k)&&state&&state.phase==='playing'&&!state.paused){e.preventDefault();keys.add(k);if(k===' ')queuedFire=true;}});
 window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pause();}});
 document.querySelectorAll('[data-hold]').forEach(b=>{b.addEventListener('pointerdown',e=>{if(!state||state.paused||state.phase!=='playing')return;e.preventDefault();try{b.setPointerCapture(e.pointerId);}catch(_){}pointers.set(e.pointerId,b.dataset.hold);if(b.dataset.hold==='fire')queuedFire=true;});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,e=>pointers.delete(e.pointerId));b.addEventListener('click',e=>{if(e.detail===0&&b.dataset.hold==='fire')queuedFire=true;});b.addEventListener('keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();keys.add('touch-'+b.dataset.hold);}});b.addEventListener('keyup',()=>keys.delete('touch-'+b.dataset.hold));});
 function input(){const held=v=>[...pointers.values()].includes(v)||keys.has('touch-'+v);let axis=(keys.has('arrowright')||keys.has('d')||held('right')?1:0)-(keys.has('arrowleft')||keys.has('a')||held('left')?1:0),fire=keys.has(' ')||held('fire')||queuedFire;queuedFire=false;const pad=[...(navigator.getGamepads?navigator.getGamepads():[])].find(p=>p&&p.connected);if(pad){const press=i=>!!(pad.buttons[i]&&pad.buttons[i].pressed),x=pad.axes[0]||0;if(Math.abs(x)>.2)axis=x;if(press(14))axis=-1;if(press(15))axis=1;fire=fire||press(0)||press(7);}else padPause=false;return {axis,fire};}
 function menuPad(){const pad=[...(navigator.getGamepads?navigator.getGamepads():[])].find(p=>p&&p.connected);if(!pad){padPause=false;padMove=false;return;}const press=i=>!!pad.buttons[i]?.pressed,settingsOpen=!!document.querySelector('.arc-set-bg:not([hidden])');const action=press(9)||(!$('curtain').hidden&&press(0)),move=press(12)||press(13)||press(14)||press(15)||Math.abs(pad.axes[1]||0)>.55;if(!settingsOpen){if(move&&!padMove&&!$('curtain').hidden){const buttons=[...$('panel').querySelectorAll('button')],index=buttons.indexOf(document.activeElement),back=press(12)||press(14)||(pad.axes[1]||0)<-.55;buttons[(index+(back?-1:1)+buttons.length)%buttons.length]?.focus();}if(action&&!padPause){if($('curtain').hidden)pause();else{const active=document.activeElement,b=$('panel').contains(active)&&active.tagName==='BUTTON'?active:$('panel').querySelector('button');b?.click();}}}padPause=action;padMove=move;}
 function hud(s,isDemo){const p=M.current(s);$('playerLabel').textContent=isDemo?'DEMO · PRESS START':'PLAYER '+(s.active+1);$('score').textContent=String(p.score).padStart(6,'0');$('best').textContent=String(save.scores[0]?.score||0).padStart(6,'0');$('wave').textContent='WAVE '+String(p.wave).padStart(2,'0');$('lives').textContent='◆ '.repeat(Math.max(0,p.lives)).trim();$('lives').setAttribute('aria-label',p.lives+' lights remaining');}
 function draw(s){const r=canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.setTransform(w/640,0,0,h/640,0,0);const p=M.current(s),t=s.elapsed;ctx.fillStyle='#081d30';ctx.fillRect(0,0,640,640);
  ctx.fillStyle='#476777';for(let i=0;i<38;i++)ctx.fillRect((i*131+31)%640,35+(i*37)%360,2,2);ctx.fillStyle='#dce8cb';ctx.fillRect(549,82,22,22);ctx.fillStyle='#081d30';ctx.fillRect(557,78,21,20);
  ctx.fillStyle='#123c4c';ctx.fillRect(0,544,640,96);ctx.fillStyle='#286779';for(let y=557;y<638;y+=18)for(let x=0;x<640;x+=63)ctx.fillRect(x+(reduce?0:Math.floor(Math.sin(t*.7+y)*8)),y,33,2);
  ctx.fillStyle='#23485a';for(let x=0;x<640;x+=47){ctx.fillRect(x,613,39,27);ctx.fillRect(x+9,601,20,13);}ctx.fillStyle='#71969b';ctx.fillRect(9,525,24,85);ctx.fillStyle='#b6c4aa';ctx.fillRect(6,520,30,8);ctx.fillStyle='#f3d580';ctx.fillRect(11,507,20,13);ctx.fillStyle='#729195';ctx.beginPath();ctx.moveTo(4,507);ctx.lineTo(22,491);ctx.lineTo(40,507);ctx.fill();
  for(const c of p.clouds){if(!c.alive)continue;ctx.fillStyle=['#c4bada','#a3c7d3','#87b7cd','#729bad'][c.row];ctx.fillRect(c.x-24,c.y-4,48,17);ctx.fillRect(c.x-16,c.y-13,31,17);ctx.fillRect(c.x-8,c.y-18,14,12);ctx.fillStyle='#22435b';ctx.fillRect(c.x-10,c.y+2,5,4);ctx.fillRect(c.x+6,c.y+2,5,4);ctx.fillRect(c.x-2,c.y+9,5,3);}
  for(const b of p.wall){if(!b.hp)continue;ctx.fillStyle=b.hp===2?'#83aca2':'#426c71';ctx.fillRect(b.x,b.y,9,9);ctx.fillStyle='#aec8ae';ctx.fillRect(b.x,b.y,9,2);}
  if(p.gull){ctx.strokeStyle='#f7efd3';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.gull.x-17,p.gull.y-5);ctx.lineTo(p.gull.x-8,p.gull.y);ctx.lineTo(p.gull.x,p.gull.y-4);ctx.lineTo(p.gull.x+8,p.gull.y);ctx.lineTo(p.gull.x+17,p.gull.y-5);ctx.stroke();}
  ctx.fillStyle='#f6d275';for(const b of p.shots)ctx.fillRect(b.x-2,b.y-8,4,16);ctx.fillStyle='#83d4e1';for(const b of p.rain)ctx.fillRect(b.x-2,b.y-5,4,11);
  ctx.globalAlpha=p.invincible>0&&!reduce?.6:1;ctx.fillStyle='#d9d4ba';ctx.fillRect(p.x-18,578,36,10);ctx.fillRect(p.x-11,568,22,12);ctx.fillStyle='#f6d275';ctx.fillRect(p.x-4,559,8,12);ctx.fillStyle='#2e6874';ctx.fillRect(p.x-24,587,48,6);ctx.globalAlpha=1;
 }
 function frame(now){const dt=Math.min(.08,Math.max(0,(now-last)/1000));last=now;menuPad();if(!state){if(demo.phase!=='playing') {demo=M.create(1,29);M.ready(demo);}const p=M.current(demo);const target=p.clouds.find(c=>c.alive);M.advance(demo,reduce?0:dt,{axis:target?Math.sign(target.x-p.x):Math.sin(now/1600),fire:true});draw(demo);hud(demo,true);}else{if(state.phase==='playing'&&!state.paused){M.advance(state,dt,input());for(const e of state.events){audio.sfx(e==='shot'?'blip':e==='hit'?'hit':e==='bonus'?'coin':e==='clear'||e==='wave'?'level':'select');}}if(state.phase==='ready'&&uiPhase!=='ready')readyPanel();else if(state.phase==='over'&&uiPhase!=='over')finish();draw(state);hud(state,false);}requestAnimationFrame(frame);}
 title();requestAnimationFrame(frame);
 if(['localhost','127.0.0.1','[::1]'].includes(location.hostname))window.__storm={M,get state(){return state;},save,start,launch,pause,title,finish};
})();
