'use strict';
/* =================== world data =================== */
const FACTIONS={
  concord:{name:'The Concord',desc:'Old kingdoms of the west, bound by oath and stone.',col:'var(--concord)',races:['human','stonekin'],start:'thornvale'},
  wild:{name:'The Wildclans',desc:'Free peoples of the red steppe, bound by blood and honor.',col:'var(--wild)',races:['grishar','duskelf'],start:'redsand'},
};
const RACES={
  human:{name:'Human',faction:'concord',bonus:'Quests give 5% more experience.',qxp:1.05,skin:'#f1c9a0',hair:'#6b4423'},
  stonekin:{name:'Stonekin',faction:'concord',bonus:'10% more armor, +2 Stamina.',armor:1.1,stat:{sta:2},skin:'#e0b08a',hair:'#b5662a',beard:true},
  grishar:{name:'Grishar',faction:'wild',bonus:'5% more health. Below 30% health you deal 10% more damage. Bonds with tamed beasts 20% faster.',hp:1.05,bloodrage:true,beastkin:true,skin:'#7fa65a',hair:'#2b2b2b',tusks:true},
  duskelf:{name:'Duskelf',faction:'wild',bonus:'+2% critical strike chance.',crit:2,skin:'#b9a3d9',hair:'#e8e8f0',ears:true},
};
const CLASSES={
  warrior:{name:'Warrior',role:'Tank / Damage',res:'rage',armor:['mail','leather','cloth'],weap:['sword','mace'],off:'shield',col:'#c79c6e',
    base:{str:23,agi:20,int:10,sta:22,spi:11},grow:{str:2,agi:1,int:0,sta:2,spi:.5},w:{str:2,agi:1,sta:1.2,int:0,spi:0,dps:4,armor:.04},
    desc:'Plate-and-steel fighter. Builds rage by hitting and being hit, spends it on heavy strikes.'},
  rogue:{name:'Rogue',role:'Damage',res:'energy',armor:['leather','cloth'],weap:['dagger','sword'],off:'dagger',col:'#fff469',
    base:{str:18,agi:24,int:11,sta:20,spi:12},grow:{str:1,agi:2,int:0,sta:1.5,spi:.5},w:{agi:2,str:1,sta:1,int:0,spi:0,dps:4,armor:.02},
    desc:'Quick blades and combo points. Builds combos, then spends them on a finisher.'},
  mage:{name:'Mage',role:'Damage',res:'mana',armor:['cloth'],weap:['staff','dagger'],off:'tome',col:'#69ccf0',
    base:{str:10,agi:12,int:24,sta:17,spi:20},grow:{str:0,agi:.5,int:2,sta:1,spi:1.5},w:{int:2,spi:1,sta:1,str:0,agi:0,dps:.5,armor:.01},
    desc:'Fire and frost from range. Huge damage, little health, watch your mana.'},
  priest:{name:'Priest',role:'Healer / Damage',res:'mana',armor:['cloth'],weap:['staff','mace'],off:'tome',col:'#f0f0f0',
    base:{str:11,agi:12,int:22,sta:18,spi:24},grow:{str:0,agi:.5,int:1.5,sta:1,spi:2},w:{int:1.5,spi:1.5,sta:1,str:0,agi:0,dps:.5,armor:.01},
    desc:'Holy light and shadow. Heals and shields keep you standing through long fights.'},
  hunter:{name:'Hunter',role:'Damage · Pet tamer',res:'mana',armor:['leather','cloth'],weap:['bow'],off:'dagger',col:'#abd473',
    base:{str:16,agi:24,int:14,sta:20,spi:14},grow:{str:.5,agi:2,int:.8,sta:1.5,spi:.5},w:{agi:2,sta:1,int:.5,str:0,spi:0,dps:4,armor:.02},
    desc:'Tames wild beasts and fights beside them. Rarer beasts make stronger pets, and your bond grows with every fight.'},
};
const STAT_NAME={str:'Strength',agi:'Agility',int:'Intellect',sta:'Stamina',spi:'Spirit'};

const ZONES={
  thornvale:{name:'Thornvale',lv:[1,10],faction:'concord',hub:'Thornvale Abbey',sky:['#86b7e6','#dff0d0'],hill:'#4f7a3a',ground:'#5f8f3f',
    lore:"Thornvale Abbey keeps the valley's road lamps burning beside fields and old boundary stones. Beneath those fields, the abandoned mine has become a refuge for Diggers, while red kerchiefs on the road warn that even a familiar journey needs an escort.",
    mobs:[
      {id:'wolf',name:'Young Wolf',lv:[1,2],kind:'beast',fam:'wolf',col:'#8a8a8a'},
      {id:'digger',name:'Tunnel Digger',lv:[2,4],kind:'humanoid',col:'#b07a3a',drop:'Waxy Candle'},
      {id:'boar',name:'Thornback Boar',lv:[4,6],kind:'beast',fam:'boar',col:'#7a4a2a',drop:'Thornback Tusk'},
      {id:'bandit',name:'Redkerchief Bandit',lv:[5,7],kind:'humanoid',col:'#c0392b',drop:'Red Kerchief'},
      {id:'foreman',name:'Digger Foreman',lv:[7,9],kind:'humanoid',col:'#d0a050'},
      {id:'grizzle',name:'Grizzlemaw',lv:[10,10],kind:'beast',fam:'wolf',col:'#5a5a6a',elite:true,rare:true},
    ]},
  redsand:{name:'Redsand Steppe',lv:[1,10],faction:'wild',hub:'Bloodstone Camp',sky:['#e8a868','#f6dcb0'],hill:'#a5552e',ground:'#b8683a',
    lore:"At Bloodstone Camp, travelers share water before they share news, and clan promises are spoken where everyone can hear them. Beyond the camp, red canyons shelter hyena packs, raiders carry discarded loyalties into battle, and the cliffs echo with harpy cries.",
    mobs:[
      {id:'lizard',name:'Sun Lizard',lv:[1,2],kind:'beast',fam:'lizard',col:'#c9a03a'},
      {id:'hyena',name:'Dust Hyena',lv:[2,4],kind:'beast',fam:'hyena',col:'#b8925a',drop:'Hyena Mane'},
      {id:'razor',name:'Razorhide Boar',lv:[4,6],kind:'beast',fam:'boar',col:'#6a3a2a',drop:'Razorhide Pelt'},
      {id:'outcast',name:'Outcast Raider',lv:[5,7],kind:'humanoid',col:'#5a6a3a',drop:'Raider Totem'},
      {id:'harpy',name:'Cliff Harpy',lv:[7,9],kind:'humanoid',col:'#8a5ab0'},
      {id:'duneclaw',name:'Kraska Duneclaw',lv:[10,10],kind:'beast',fam:'cat',col:'#a03020',elite:true,rare:true},
    ]},
  fens:{name:'Greywater Fens',lv:[10,20],faction:null,hub:{concord:'Fenwatch Post',wild:'Mudtusk Camp'},sky:['#7d8f8a','#b9c4b0'],hill:'#3f5a48',ground:'#4a5e3c',
    lore:"Greywater covers the stones of an older road, leaving both the Concord and the Wildclans dependent on its narrow causeway. Fenwatch Post and Mudtusk Camp watch each other across the mist, while tide sigils and voices from the drowned ruins hint at a danger neither side can face by guarding its own bank alone.",
    mobs:[
      {id:'gloomfin',name:'Gloomfin Hunter',lv:[10,12],kind:'humanoid',col:'#3a8a7a',drop:'Gloomfin Scale'},
      {id:'lurker',name:'Bog Lurker',lv:[12,14],kind:'beast',fam:'croc',col:'#4a6a3a'},
      {id:'spider',name:'Fen Spider',lv:[13,15],kind:'beast',fam:'spider',col:'#3a3a4a',drop:'Bog Silk'},
      {id:'cultist',name:'Drowned Cultist',lv:[15,17],kind:'humanoid',col:'#2a5a8a',drop:'Tide Sigil'},
      {id:'troll',name:'Mire Troll',lv:[17,19],kind:'humanoid',col:'#5a8a5a',drop:'Mire Troll Tusk'},
      {id:'prophet',name:'The Drowned Prophet',lv:[20,20],kind:'humanoid',col:'#1a4a7a',elite:true,rare:true},
    ]},
  ashen:{name:'Ashen Ridge',lv:[20,30],faction:null,hub:{concord:'Emberwatch Hold',wild:'Cinderhorn Outpost'},sky:['#75434a','#e5a16a'],hill:'#493333',ground:'#65463c',
    lore:"Ash settles on the ridge road faster than travelers can brush it from their cloaks. Emberwatch Hold and Cinderhorn Outpost keep the pass supplied, but stolen caravans and Covenant seals lead toward the Cindervein Foundry, where the mountain's heat has become a promise in the wrong hands.",
    mobs:[
      {id:'ashwolf',name:'Cinderfang Wolf',lv:[20,22],kind:'beast',fam:'wolf',col:'#9a5440',drop:'Cinderfang Pelt'},
      {id:'ridgeboar',name:'Obsidian Boar',lv:[22,24],kind:'beast',fam:'boar',col:'#38343c',drop:'Obsidian Tusk'},
      {id:'ogre',name:'Ridgebreaker Ogre',lv:[23,25],kind:'humanoid',col:'#a38a61',drop:'Stolen Supply Crate'},
      {id:'embercult',name:'Ember Covenant Adept',lv:[25,27],kind:'humanoid',col:'#b54e32',drop:'Ember Seal'},
      {id:'slagscale',name:'Slagscale Lizard',lv:[27,29],kind:'beast',fam:'lizard',col:'#da7939',drop:'Heatproof Scale'},
      {id:'coalmaw',name:'Coalmaw, the Living Furnace',lv:[30,30],kind:'beast',fam:'boar',col:'#b53d26',elite:true,rare:true},
    ]},
  frostmere:{name:'Frostmere',lv:[30,40],faction:null,hub:{concord:'Lanternrest Lodge',wild:'Whitebough Hearth'},sky:['#6d91b2','#e5eef2'],hill:'#889eaa',ground:'#c4d3d6',
    lore:"The winter road joins Lanternrest Lodge and Whitebough Hearth across a tundra where a lit window is a promise to the traveler still outside. Ice trolls have stripped its waymarkers and taken its provisions, while pale stones uncovered beyond the drifts point toward a necropolis neither camp remembers building.",
    mobs:[
      {id:'rimewolf',name:'Rimecoat Wolf',lv:[30,32],kind:'beast',fam:'wolf',col:'#aabacb',drop:'Rimecoat Pelt'},
      {id:'snowboar',name:'Snowroot Boar',lv:[32,34],kind:'beast',fam:'boar',col:'#c4bcb2',drop:'Snowroot Tusk'},
      {id:'iceraider',name:'Ice Troll Forager',lv:[33,35],kind:'humanoid',col:'#82b2b8',drop:'Winter Provision Sack'},
      {id:'rimekeeper',name:'Ice Troll Waykeeper',lv:[35,37],kind:'humanoid',col:'#678eaa',drop:'Carved Road Stone'},
      {id:'driftcat',name:'Driftstalker Cat',lv:[37,39],kind:'beast',fam:'cat',col:'#d1dce2',drop:'Driftstalker Pelt'},
      {id:'hushfang',name:'Hushfang, the White Vigil',lv:[40,40],kind:'beast',fam:'wolf',col:'#e4edf1',elite:true,rare:true},
    ]},
  barrowfield:{xpMult:.6,name:"The Barrowfields",lv:[40,45],faction:null,hub:{"concord":"Lanternrest Lodge","wild":"Whitebough Hearth"},sky:["#657c91","#c5d3de"],hill:"#3e4b59",ground:"#a9bbc8",
    lore:"Beyond the winter road, grey-blue snow lies between dark barrow stones. Lanternrest Lodge and Whitebough Hearth keep forward camps where grave-cold creeps toward their lamps. The recovered carvings name the Wayfolk, keepers of the Reach's crossings before the Sundering: they buried road-stones with their dead, believing a road remembers whoever walked it. The ice trolls reused those stones for crossings of their own; now restless wardens bar the living from the Silent Barrows.",
    mobs:[
      {"id":"gravewolf","name":"Gravebreath Wolf","lv":[40,41],"kind":"beast","fam":"wolf","col":"#8295ad","drop":"Gravebreath Pelt"},
      {"id":"barrowspider","name":"Stoneweft Spider","lv":[40,42],"kind":"beast","fam":"spider","col":"#4a5366","drop":"Stoneweft Silk"},
      {"id":"waydead","name":"Wayfolk Roadshade","lv":[41,43],"kind":"humanoid","col":"#8ca8b9","drop":"Wayfolk Road Fragment"},
      {"id":"icedigger","name":"Ice Troll Cairn Digger","lv":[42,44],"kind":"humanoid","col":"#6b8f9e","drop":"Reused Crossing Stone"},
      {"id":"barrowguard","name":"Wayfolk Threshold Keeper","lv":[43,45],"kind":"humanoid","col":"#627789","drop":"Threshold Inscription"},
      {"id":"paleweft","name":"Paleweft, the Lamp-Eater","lv":[45,45],"kind":"beast","fam":"spider","col":"#c7d6e2","elite":true,"rare":true},
    ]},
  hollowcrown:{xpMult:.6,name:'The Hollow Crown',lv:[45,52],faction:null,hub:{concord:'Thornmantle Camp',wild:'Thornmantle Camp'},sky:['#626b37','#c7bc68'],hill:'#43532e',ground:'#302e23',
    lore:"The barrows road runs east into a forest grown around an empty throne. The Wayfolk crowned no one after the Sundering; the absence festered, and now the wood tries to fill the seat with anything it can bind. Sick green-gold leaves cover dark roots, while the Ashwing, a lineage of lesser drakes, nest in the canopy and claim the throne as their hoard. Concord and Wildclan travelers share Thornmantle Camp at the outer edge. Rootrot Hollow opens beneath the tangled approaches; the Crown's heart still lies beyond.",
    mobs:[
      {id:'rotgnaw',name:'Rotgnaw Wolf',lv:[45,47],kind:'beast',fam:'wolf',col:'#737b45',drop:'Rotgnaw Pelt'},
      {id:'thornridge',name:'Thornridge Boar',lv:[46,48],kind:'beast',fam:'boar',col:'#84764b',drop:'Forked Briar Tusk'},
      {id:'giltweb',name:'Giltweb Canopy Spider',lv:[47,49],kind:'beast',fam:'spider',col:'#a99b4e',drop:'Giltweb Silk'},
      {id:'hollowroot',name:'Hollowroot Warden',lv:[48,51],kind:'humanoid',col:'#667443',drop:'Empty Seat Carving'},
      {id:'ashwing',name:'Ashwing Canopy Drake',lv:[50,52],kind:'beast',fam:'lizard',col:'#93834b',drop:'Ashwing Hoard Scale'},
      {id:'veskareth',name:'Veskareth, the Bough Sentinel',lv:[52,52],kind:'beast',fam:'lizard',col:'#c6b87a',elite:true,rare:true},
    ]},
  crownheart:{xpMult:.6,name:"The Crown's Heart",lv:[52,60],faction:null,hub:{concord:'Heartwatch Camp',wild:'Heartwatch Camp'},sky:['#263323','#b49a52'],hill:'#243023',ground:'#29271c',
    lore:"Thornmantle's watch has moved inward to Heartwatch Camp, where older trunks shut out the sky and gold light falls on the Hollow Throne. Rootbound choirs pull beast and branch toward the seat: the forest's hunger has not ended because Seraveth, the Ashwing matriarch, now sits upon it. Her voice carries from beyond the Heartwood Vault, but the road has not yet reached her. Travelers who have cleared the Silent Barrows and Rootrot Hollow can prepare the Hollow Key, opening a return path to the throne without claiming its crown.",
    mobs:[
      {id:'crownfang',name:'Crownfang Wolf',lv:[52,54],kind:'beast',fam:'wolf',col:'#79794e',drop:'Crownfang Pelt'},
      {id:'hearttusk',name:'Hearttusk Boar',lv:[53,55],kind:'beast',fam:'boar',col:'#746443',drop:'Heartwood Tusk'},
      {id:'veilweft',name:'Veilweft Spider',lv:[54,56],kind:'beast',fam:'spider',col:'#ad985c',drop:'Veilweft Cord'},
      {id:'choirroot',name:'Rootbound Choir-Treant',lv:[55,58],kind:'humanoid',col:'#697847',drop:'Return-Road Verse'},
      {id:'broodguard',name:'Ashwing Broodguard',lv:[56,59],kind:'beast',fam:'lizard',col:'#9b794c',drop:'Broodward Scale'},
      {id:'elderwing',name:'Ashwing Gilded Elder',lv:[58,60],kind:'beast',fam:'lizard',col:'#bda264',drop:'Hoard-Sign Scale'},
      {id:'aurethyn',name:'Aurethyn, the Unbound Wing',lv:[60,60],kind:'beast',fam:'lizard',col:'#d0b778',elite:true,rare:true},
    ]},
};
const ZONE_ORDER={concord:['thornvale','fens','ashen','frostmere','barrowfield','hollowcrown','crownheart'],wild:['redsand','fens','ashen','frostmere','barrowfield','hollowcrown','crownheart']};

const QUESTS={
  thornvale:[
    {id:'t1',name:'Wolves at the Fence',giver:'Farmer Aldous',text:'The wolves have taken three of my lambs this week. Thin them out before they take the rest.',done:"I heard the flock settle before sundown for the first time all week. Thank you for giving the lambs a quieter night.",type:'kill',mob:'wolf',n:8,lvl:1},
    {id:'t2',name:'Candles in the Dark',giver:'Deputy Rhea',text:'The Diggers in the old mine steal our candles. Bring back what they took.',done:"These candles belong on our windowsills, not under someone else's mine. I will see them returned before dark.",type:'collect',mob:'digger',n:8,lvl:2},
    {id:'t3',name:'Clearing the Old Mine',giver:'Deputy Rhea',text:'Enough is enough. Drive the Diggers out of the mine.',done:"Good. We can put a watch at the entrance now, instead of sending another neighbor down alone.",type:'kill',mob:'digger',n:10,lvl:3,req:'t2'},
    {id:'t4',name:'Tusks for the Smith',giver:'Smith Corwen',text:'Thornback tusk makes the best handles in the valley. Six should do.',done:"Fine tusks, with a good grain through the core. I will shape handles that hold steady when a hand is tired.",type:'collect',mob:'boar',n:6,lvl:4},
    {id:'t5',name:'The Redkerchief Gang',giver:'Captain Morrow',text:'Bandits are robbing the road to the abbey. Show them the law.',done:"The abbey road carries bread as well as pilgrims. You have protected both, and I will remember it.",type:'kill',mob:'bandit',n:10,lvl:5},
    {id:'t6',name:'Proof of the Deed',giver:'Captain Morrow',text:'Bring me their red kerchiefs so I can pay the bounty.',done:"Eight kerchiefs, accounted for. Here is your bounty; the road watch keeps its word.",type:'collect',mob:'bandit',n:8,lvl:6,req:'t5'},
    {id:'t7',name:"The Foreman's Ledger",giver:'Deputy Rhea',text:'Someone is giving the Diggers orders. Find the foremen and end it.',done:"The foremen will not be sending anyone after our candles tonight. I still want to know who taught them to organize like that.",type:'kill',mob:'foreman',n:8,lvl:7,req:'t3'},
    {id:'t8',name:'Grizzlemaw',giver:'Farmer Aldous',text:'The old wolf that leads the pack is bigger than a horse. Bring friends, or a lot of courage.',done:"Grizzlemaw will not lead another pack to my fence. Whatever you found the courage to do out there, you have my thanks.",type:'kill',mob:'grizzle',n:1,lvl:10,elite:true,req:'t1'},
  ],
  redsand:[
    {id:'r1',name:'Lizards in the Water',giver:'Elder Ugra',text:'Sun lizards foul our watering hole. Drive them off.',done:"The watering hole is ours to share again. Sit a while; even a strong traveler needs a drink.",type:'kill',mob:'lizard',n:8,lvl:1},
    {id:'r2',name:'Manes for the Hunt',giver:'Huntress Kesh',text:'Young hunters prove themselves with hyena manes. Prove yourself.',done:"You brought the manes, and you came back to tell the tale. That is a beginning worth honoring.",type:'collect',mob:'hyena',n:8,lvl:2},
    {id:'r3',name:'The Laughing Packs',giver:'Huntress Kesh',text:'The hyenas grow bold. Cut their numbers.',done:"The packs will think twice before following our young hunters. Keep listening for laughter on the wind.",type:'kill',mob:'hyena',n:10,lvl:3,req:'r2'},
    {id:'r4',name:'Razorhide Pelts',giver:'Tanner Bosk',text:'Razorhide makes armor that turns a blade. Six pelts.',done:"Six sound pelts. I will make their toughness count for someone who has no hide of their own.",type:'collect',mob:'razor',n:6,lvl:4},
    {id:'r5',name:'Outcasts',giver:'Warchief Drogan',text:'Raiders cast out of the clans attack our caravans. Show them why they were cast out.',done:"A caravan can cross our land without paying for another clan's quarrel. You have reminded the outcasts of that.",type:'kill',mob:'outcast',n:10,lvl:5},
    {id:'r6',name:'Broken Totems',giver:'Warchief Drogan',text:'Take their totems. Without them they have no clan, no luck.',done:"Their stolen promises end here. Let these broken loyalties warn anyone who would raid under a clan's name.",type:'collect',mob:'outcast',n:8,lvl:6,req:'r5'},
    {id:'r7',name:'Harpies on the Cliffs',giver:'Elder Ugra',text:'The cliff harpies have taken our scouts. Climb up and end their nests.',done:"The cliffs are quieter, though that will not bring every scout home. We will speak their names at the fire tonight.",type:'kill',mob:'harpy',n:8,lvl:7,req:'r3'},
    {id:'r8',name:'Kraska Duneclaw',giver:'Huntress Kesh',text:'The great beast of the dunes. Many hunters went out. None came back.',done:"You faced Kraska and returned. I will tell the hunters what you did, and remember those who never had that chance.",type:'kill',mob:'duneclaw',n:1,lvl:10,elite:true,req:'r1'},
  ],
  fens:[
    {id:'f1',name:'Scales of the Gloomfin',giver:['Scout Merrin','Tracker Vosh'],text:'The gloomfins came up out of the water a month ago. Bring their scales so we can learn why.',done:["These scales may tell us what changed beneath the water. A month is not long for a whole shore to become dangerous.", "Good tracks sometimes fit in a pouch. Let us see what these scales tell us about the water they left."],type:'collect',mob:'gloomfin',n:8,lvl:10},
    {id:'f2',name:'Hold the Causeway',giver:['Captain Hale','Blademaster Ruk'],text:'Gloomfin hunting parties are cutting the causeway. Hold it.',done:["The causeway is still open. I can move the next supply cart without asking its driver to gamble on the bog.", "You held the stones. Our caravans need a road beneath their feet, not another argument over whose road it is."],type:'kill',mob:'gloomfin',n:12,lvl:11},
    {id:'f3',name:'What Lurks Below',giver:['Scout Merrin','Tracker Vosh'],text:'Something drags travelers into the bog. Find it and kill it.',done:["Those drag marks will trouble fewer travelers now. I will keep watching the pools; the fens rarely have only one secret.", "The mud tells a quieter story today. Stay on firm ground until we know what else hunts below it."],type:'kill',mob:'lurker',n:10,lvl:12},
    {id:'f4',name:'Silk for Bandages',giver:['Sister Ilsa','Mender Garra'],text:'Our wounded need bandages and fen silk is strong. Eight bundles.',done:["Strong silk, thank you. I can bind a wound with this without fearing the cloth will tear.", "Eight bundles, and none wasted. These will hold our wounded together until they can stand at the fire again."],type:'collect',mob:'spider',n:8,lvl:13},
    {id:'f5',name:'The Spider Nests',giver:['Captain Hale','Blademaster Ruk'],text:'The spiders are breeding faster than we can burn them.',done:["Fewer nests means our bandage gatherers can work without an escort at every step. Keep your boots clear of the webs.", "The nests will not swallow the path today. A clean blade is useful, but a clear road serves the whole camp."],type:'kill',mob:'spider',n:12,lvl:14,req:'f4'},
    {id:'f6',name:'Signs of the Tide',giver:['Sister Ilsa','Mender Garra'],text:'Cultists in the drowned ruins carry strange sigils. Bring them to me.',done:["I do not recognize this prayer, and that worries me. I will study the sigils away from the wounded.", "These marks are asking for something. I would rather learn the price before anyone in camp answers them."],type:'collect',mob:'cultist',n:8,lvl:15,req:'f2'},
    {id:'f7',name:'The Drowned Cult',giver:['Captain Hale','Blademaster Ruk'],text:'They worship something under the water. Stop the ritual before it finishes.',done:["You have stopped these rites. Keep the sigils under watch; a broken ritual can still leave believers behind.", "Their voices have fallen quiet for now. Do not mistake silence for an empty ruin."],type:'kill',mob:'cultist',n:12,lvl:16,req:'f6'},
    {id:'f8',name:'Trolls in the Mire',giver:['Scout Merrin','Tracker Vosh'],text:'Mire trolls guard the way to the ruins. Clear a path.',done:["I can reach the ruins without walking straight into a troll guard. That is a path worth marking carefully.", "You opened the way. I will mark the safe footing before the mire hides it again."],type:'kill',mob:'troll',n:10,lvl:17},
    {id:'f9',name:'Tusks of the Mire',giver:['Smith Dunstan','Smith Grall'],text:'Troll tusk is harder than iron. I can work with eight.',done:["Harder than iron, just as I said. Let me find the grain before I put a tool to them.", "Eight good tusks. Give me a steady fire and I will make them useful to living hands."],type:'collect',mob:'troll',n:8,lvl:18,req:'f8'},
    {id:'f10',name:'The Drowned Prophet',giver:['Captain Hale','Blademaster Ruk'],text:'The cult answers to one voice. Silence it. Then we can enter the Drowned Sanctum.',done:["The Prophet no longer gives the cult its orders. Gather allies before you enter the Sanctum; I want the whole party back.", "One voice silenced, but the water still moves. Take allies into the Sanctum, and leave no one behind."],type:'kill',mob:'prophet',n:1,lvl:20,elite:true,req:'f7'},
  ],
  ashen:[
    {id:'a1',name:'Teeth in the Ash',giver:['Ranger Elowen','Scout Brakka'],text:'Cinderfang packs follow every caravan. Make the ridge road safe.',done:["The caravans have a little room to breathe. I will walk the ridge road again before I call it safe.", "The packs have lost our trail for now. I will watch the ash for fresh tracks while the next caravan passes."],type:'kill',mob:'ashwolf',n:12,lvl:20},
    {id:'a2',name:'Cinderfang Cloaks',giver:['Smith Halden','Tanner Ursha'],text:'Their pelts resist sparks. Our scouts need new cloaks.',done:["These pelts will spare our scouts a few burns. Sparks find every gap, so I will stitch the seams twice.", "A cloak that catches fire is no favor to a scout. These hides will do better, once I have worked them."],type:'collect',mob:'ashwolf',n:8,lvl:21,req:'a1'},
    {id:'a3',name:'Black Glass Tusks',giver:['Smith Halden','Tanner Ursha'],text:'Obsidian tusks hold an edge even in this heat. Bring me eight.',done:["A fine edge needs a material that will keep it. These tusks should stand the ridge heat without losing their bite.", "Black glass is sharp work. I will fit it carefully; our people need tools, not another cut to mend."],type:'collect',mob:'ridgeboar',n:8,lvl:22},
    {id:'a4',name:'Break the Ridgebreakers',giver:['Captain Veyra','Warden Korr'],text:'The ogres have seized the mountain pass. Drive them back.',done:["The pass is open again. Now we can look for the supplies they took from us.", "They no longer own the narrow ground. Next we take back what belongs to the outpost."],type:'kill',mob:'ogre',n:12,lvl:23},
    {id:'a5',name:'The Missing Caravan',giver:['Captain Veyra','Warden Korr'],text:'Recover our supplies from the ogre camps before the outpost runs dry.',done:["Counted and recovered. There will be food at the watch fires tonight because you went back for it.", "The stores will last longer now. A defended outpost still needs a meal, and you have remembered that."],type:'collect',mob:'ogre',n:10,lvl:24,req:'a4'},
    {id:'a6',name:'Seals of the Covenant',giver:['Scholar Iven','Seer Morra'],text:'A fire cult is paying the ogres. Their seals will reveal who gives the orders.',done:["These seals turn suspicion into something I can read. The Covenant has paid for more than a few hungry ogres.", "Fire leaves a mark even when the hand that paid for it stays hidden. These seals give us a trail to follow."],type:'collect',mob:'embercult',n:8,lvl:25,req:'a5'},
    {id:'a7',name:'Extinguish the Covenant',giver:['Captain Veyra','Warden Korr'],text:'They plan to awaken something beneath the ridge. Stop their rites.',done:["Their rites will not reach their end today. We still need to learn what they hoped to wake beneath us.", "You broke their gathering. Until we know what sleeps below the ridge, I will keep a watch on every ember."],type:'kill',mob:'embercult',n:14,lvl:26,req:'a6'},
    {id:'a8',name:'Scales Against the Flame',giver:['Smith Halden','Tanner Ursha'],text:'Slagscale hides survive molten stone. We will need them for the descent.',done:["Heatproof scales, and sound ones. I can prepare protection for the descent without trusting ordinary leather to molten stone.", "These hides have already endured what waits below. I will work them into protection worthy of that lesson."],type:'collect',mob:'slagscale',n:10,lvl:27},
    {id:'a9',name:'The Molten Trail',giver:['Ranger Elowen','Scout Brakka'],text:'Slagscales block the trail to the foundry. Clear our approach.',done:["Our approach to the foundry is clearer. I will mark the trail while the ash still remembers your steps.", "We have a route down now. Keep together; a clear trail is not a promise of a safe foundry."],type:'kill',mob:'slagscale',n:14,lvl:28,req:'a8'},
    {id:'a10',name:'Coalmaw',giver:['Captain Veyra','Warden Korr'],text:'The great boar feeds on the foundry runoff. Bring allies and end its rampage.',done:["Coalmaw's rampage has ended. Thank your allies for me; the ridge road needed every one of you.", "The great boar will not scatter another caravan today. You and your allies have earned a place at our fire."],type:'kill',mob:'coalmaw',n:1,lvl:30,elite:true,req:'a7'},
  ],
  frostmere:[
    {id:'fm1',name:'Tracks to the Hearth',giver:['Roadwarden Sella','Pathkeeper Dorr'],text:'Rimecoat packs trail the last supply sleds. Clear the approach so every driver reaches a fire tonight.',done:["The last sled reached Lanternrest with its driver beside it. That is how I count a good day's work.", "The sled tracks reach our hearth unbroken. Come warm your hands; you have earned more than a place in the snow."],type:'kill',mob:'rimewolf',n:12,lvl:30},
    {id:'fm2',name:'Cloaks for the Last Watch',giver:['Seamster Oren','Hideworker Naska'],text:'The last watch stands outside while everyone else sleeps. Bring rimecoat pelts for cloaks that will see them through.',done:["I will leave room in each collar for a scarf. Warmth is in the small things you remember before the wind rises.", "These hides kept their owners warm in the drifts. I will make them do the same for our watch."],type:'collect',mob:'rimewolf',n:8,lvl:31,req:'fm1'},
    {id:'fm3',name:'Runners That Hold',giver:['Seamster Oren','Hideworker Naska'],text:'Snowroot tusk makes a strong brace for a sled runner. Bring eight before the next load goes north.',done:["Eight braces will keep more than eight sleds moving if we mend the old ones carefully. Nothing sound goes to waste this winter.", "A strong runner carries food, children and tired feet alike. These tusks will bear their share."],type:'collect',mob:'snowboar',n:8,lvl:32},
    {id:'fm4',name:'The Empty Supply Sleds',giver:['Roadwarden Sella','Pathkeeper Dorr'],text:'Ice troll foragers leave our sleds empty and our drivers stranded. Drive the raiding bands off the winter road.',done:["Our drivers can stop looking over their shoulders at every bend. Now help me recover the provisions before the stores run low.", "The raiders have lost the road. We still need what they carried away; a victory does not fill a supper bowl."],type:'kill',mob:'iceraider',n:12,lvl:33,req:'fm2'},
    {id:'fm5',name:'Enough for Both Fires',giver:['Roadwarden Sella','Pathkeeper Dorr'],text:'Recover the stolen provision sacks. Both camps have travelers to feed; sort the tally after everyone has eaten.',done:["I sent a share to Whitebough before counting our own. A tally can wait; a hungry traveler cannot.", "Lanternrest has its share, and our pot is full. Let tomorrow's argument begin with everyone fed."],type:'collect',mob:'iceraider',n:10,lvl:34,req:'fm4'},
    {id:'fm6',name:'The Missing Waymarkers',giver:['Surveyor Tavin','Storykeeper Eshra'],text:'The waykeepers carry stones taken from our crossings. Bring them back so we can read which paths they have hidden.',done:["These crossing marks are familiar, but the carving beneath them is older. Someone has reused stones from a place our road maps leave blank.", "The road marks sit over older cuts. I know the stories of these crossings, but none explains the words beneath them."],type:'collect',mob:'rimekeeper',n:8,lvl:35,req:'fm5'},
    {id:'fm7',name:'Open the Pale Crossing',giver:['Roadwarden Sella','Pathkeeper Dorr'],text:'The ice troll waykeepers hold the northern crossing. Clear it while we return the markers to their places.',done:["The crossing is open and marked again. Keep the lamps burning for the sled that always arrives after the others.", "We can follow the road by its stones again. Leave a light at the far bend for anyone whose feet are slower than ours."],type:'kill',mob:'rimekeeper',n:14,lvl:36,req:'fm6'},
    {id:'fm8',name:'A Shelter Beyond the Drifts',giver:['Seamster Oren','Hideworker Naska'],text:'Driftstalker pelts turn the cutting wind. Bring enough to line the scouts\' shelter beyond the crossing.',done:["The shelter will have a warm lining before our scouts leave. I cannot shorten their journey, but I can give them a kinder night.", "These hides will hold a little warmth at the far camp. Tell the scouts to share it with whoever reaches them."],type:'collect',mob:'driftcat',n:10,lvl:37,req:'fm7'},
    {id:'fm9',name:'Stones Beneath the Snow',giver:['Surveyor Tavin','Storykeeper Eshra'],text:'Driftstalkers prowl the pale stone approach. Clear a path so our scouts can examine what the thaw has uncovered.',done:["The scouts found doorways facing one another across a buried street. It looks like a city for the dead; I will not give it a name until we know whose dead they were.", "There are doorways beneath the snow, and no hearths behind them. We will listen before deciding which story belongs to that silent city."],type:'kill',mob:'driftcat',n:14,lvl:38,req:'fm8'},
    {id:'fm10',name:'The White Vigil',giver:['Roadwarden Sella','Pathkeeper Dorr'],text:'Hushfang waits where the winter road meets the buried city. Bring allies and end the great wolf\'s watch before another sled is lost.',done:["The winter road reaches its last lamp again. Rest here before you seek the necropolis; a safe approach is only the beginning.", "Hushfang no longer bars the crossing, and every sled can reach a fire. The city beyond can wait until we are ready to face it together."],type:'kill',mob:'hushfang',n:1,lvl:40,elite:true,req:'fm9'},
  ],
  barrowfield:[
    {"id":"bf1","name":"Cold Beyond the Last Lamp","giver":["Roadwarden Sella","Pathkeeper Dorr"],
      "text":"Grave-cold follows the wolves back toward our forward camp. Clear the path beyond the last road lamp before another watch freezes at its post.",
      "done":["The watch has room to stand without wolves at its heels. The cold still comes from the barrows; keep the lamps supplied.","The wolves no longer follow our footsteps to the hearth. Warm your hands, then help us learn what chills the road."],
      "type":"kill","mob":"gravewolf","n":12,"lvl":40},
    {"id":"bf2","name":"A Lining for the Living","giver":["Seamster Oren","Hideworker Naska"],
      "text":"Gravebreath pelts resist the cold that seeps through ordinary cloaks. Bring eight for the forward watch.",
      "done":["I will stitch these over the old lining, with room for a second scarf. Our watch must come home wearing them.","Eight hides for eight cold shoulders. Share the finished cloaks with Lanternrest; the wind does not choose a faction."],
      "type":"collect","mob":"gravewolf","n":8,"lvl":40,"req":"bf1"},
    {"id":"bf3","name":"Silk Between the Stones","giver":["Seamster Oren","Hideworker Naska"],
      "text":"Stoneweft silk binds a cracked sled brace without snapping in this cold. Gather eight bundles where the spiders web the barrow stones.",
      "done":["These braces will carry a tired scout as safely as a crate. I will mend what we already have before making more.","The silk holds even against frost. A sled that returns with everyone matters more than one that returns laden."],
      "type":"collect","mob":"barrowspider","n":8,"lvl":40},
    {"id":"bf4","name":"Names Under the Road Marks","giver":["Surveyor Tavin","Storykeeper Eshra"],
      "text":"The restless dead carry fragments bearing the same cuts as the stolen waymarkers. Recover enough to read the older names.",
      "done":["Wayfolk: keepers of the crossings before the Sundering. These are road-stones laid beside their dead, not foundations for a new camp.","The fragments name the Wayfolk. They believed a road remembers whoever walked it; their stones kept those journeys beside the dead."],
      "type":"collect","mob":"waydead","n":8,"lvl":41,"req":"bf2"},
    {"id":"bf5","name":"Make Room for Footsteps","giver":["Roadwarden Sella","Pathkeeper Dorr"],
      "text":"The Roadshades turn every living traveler from the crossing. Hold a path while our readers examine their stones.",
      "done":["The readers reached the crossing and returned. Whatever woke these wardens, our road still has living people to carry.","Our people can walk the stones again. We will remember the dead without surrendering the road to them."],
      "type":"kill","mob":"waydead","n":12,"lvl":41,"req":"bf4"},
    {"id":"bf6","name":"Stones Used Twice","giver":["Surveyor Tavin","Storykeeper Eshra"],
      "text":"Cairn diggers have set barrow stones along their own paths. Recover the loose pieces they carry; compare their fresh marks with the old carvings.",
      "done":["The newer cuts mark troll crossings. They needed roads too; these stones were reused, not taken to insult the Wayfolk.","Two peoples marked journeys on the same stone. I find no curse in the trolls' cuts, only a crossing they wanted to keep."],
      "type":"collect","mob":"icedigger","n":8,"lvl":42,"req":"bf5"},
    {"id":"bf7","name":"Stop the Breaking","giver":["Roadwarden Sella","Pathkeeper Dorr"],
      "text":"The diggers keep breaking cairns while grave-cold spills onto the road. Drive them from the open barrows so we can secure the crossing.",
      "done":["The cairns are no longer being broken here. That does not explain what first woke the dead; Tavin needs time to read.","We stopped the digging at this crossing. Do not turn that into a story blaming the trolls for a waking we do not yet understand."],
      "type":"kill","mob":"icedigger","n":12,"lvl":42,"req":"bf6"},
    {"id":"bf8","name":"Unbind the Approach","giver":["Roadwarden Sella","Pathkeeper Dorr"],
      "text":"Stoneweft nests stretch across the doorway approach. Clear them so a party can reach the thresholds together.",
      "done":["A party can reach the doors without losing its last traveler to a web. Keep the return path marked as carefully as the way in.","The approach is open. Leave room for the slowest companion, and a lamp for the party coming back."],
      "type":"kill","mob":"barrowspider","n":14,"lvl":43,"req":"bf7"},
    {"id":"bf9","name":"The Threshold Refuses","giver":["Surveyor Tavin","Storykeeper Eshra"],
      "text":"Threshold Keepers bar us from the inscriptions inside the facing doorways. Break their watch so we can read whom the road once served.",
      "done":["The inner stones speak of shelter and shared crossings. Their wardens defend a duty, but have forgotten that living feet need it too.","The words promise a road for travelers, not a road kept empty. We must learn why its wardens now refuse the living."],
      "type":"kill","mob":"barrowguard","n":14,"lvl":43,"req":"bf8"},
    {"id":"bf10","name":"A Road Remembers","giver":["Surveyor Tavin","Storykeeper Eshra"],
      "text":"Bring the inscriptions carried by the Threshold Keepers. The scattered lines may tell us who still commands the barrows.",
      "done":["The Last Wayward: a warden who bars those who forgot why the road was built. No inscription tells us what woke that refusal.","The lines name the Last Wayward. The warden remembers the duty but calls every living traveler forgetful; the waking itself remains unanswered."],
      "type":"collect","mob":"barrowguard","n":8,"lvl":44,"req":"bf9"},
    {"id":"bf11","name":"The Lamp-Eater","giver":["Roadwarden Sella","Pathkeeper Dorr"],
      "text":"Paleweft webs the last lamps before the Silent Barrows. Bring allies to end the great spider's hunt, or earn its companionship if you can.",
      "done":["The last lamps can burn clear again. Thank your allies; a light beyond the crossing helps everyone find the return road.","Paleweft no longer hunts beside our lamps. Whatever bond you made there, the road has room for living travelers again."],
      "type":"kill","mob":"paleweft","n":1,"lvl":45,"req":"bf10","elite":true},
    {"id":"bf12","name":"Carry the Road Within","giver":["Surveyor Tavin","Storykeeper Eshra"],
      "text":"Clear the remaining Threshold Keepers from the party's approach, then gather four companions for the Silent Barrows. The Last Wayward waits inside; the road must serve the living as well as remember the dead.",
      "done":["The approach is ready. Enter the Silent Barrows together and face the Last Wayward; clearing these guards is not the same as settling the warden's refusal.","Carry a lamp into the Silent Barrows, with four companions beside you. The Last Wayward still waits; show that remembering a road means keeping it for others."],
      "type":"kill","mob":"barrowguard","n":14,"lvl":45,"req":"bf11"},
  ],
  hollowcrown:[
    {id:'hc1',name:'East of the Barrows',giver:['Trailwarden Aven','Rootscout Neral'],
      text:'The barrows road continues beneath these trees. Rot-bitten wolves follow the returning scouts; clear the outer trail so both camps can send travelers to Thornmantle.',
      done:['The return watch can see its travelers coming now. I will mark a shared trail before anyone starts drawing boundaries.','Fewer teeth at our backs. Keep the trail wide enough for the people arriving after us, whatever fire they came from.'],
      type:'kill',mob:'rotgnaw',n:12,lvl:45},
    {id:'hc2',name:'Cloaks for a Shared Camp',giver:['Campwright Tessa','Cordmender Ghor'],
      text:'The green-gold canopy sheds bitter damp all night. Bring Rotgnaw pelts for the scouts at Thornmantle Camp; their old winter cloaks have worn through.',
      done:['I can mend these into the old linings. A shared camp needs dry shoulders before it needs another banner.','Sound hide under the rot. I will stitch for whoever comes back cold; a clan mark does not keep the rain out.'],
      type:'collect',mob:'rotgnaw',n:8,lvl:45,req:'hc1'},
    {id:'hc3',name:"Pell's Cart Road",giver:['Trailwarden Aven','Rootscout Neral'],
      text:"Pell wants to bring lamps along the cart road, but his patient mule Brisket will not pass the thornback boars. Clear the bend. He says, 'Just passing through! Honest prices, mind; I claim to have sold a lantern to every hero ever, but I still have to pay for the oil.'",
      done:["The cart can reach our watch now. Pell has his prices on the board, and Brisket has stopped arguing with the bend. I will see the lamps reach both watches.","Pell says Brisket thanks you without charging a copper. His prices are honest, and the lamps can reach everyone who needs this road."],
      type:'kill',mob:'thornridge',n:12,lvl:46,req:'hc1'},
    {id:'hc4',name:'Braces in the Briar',giver:['Campwright Tessa','Cordmender Ghor'],
      text:'Forked briar tusks can brace the camp walkways above the dark roots. Gather eight sound pieces from the Thornridge boars; we will fit the braces without cutting another living tree.',
      done:['Eight braces, fitted where tired feet slip. I would rather build a return path than watch another scout climb roots in the dark.','These forks hold a knot well. The walkway will carry both watches, and no one needs to cut healthy wood for it.'],
      type:'collect',mob:'thornridge',n:8,lvl:46,req:'hc3'},
    {id:'hc5',name:'Bridges of Gold',giver:['Campwright Tessa','Cordmender Ghor'],
      text:'The canopy spiders spin strong silk across the old crossings. Bring eight bundles of Giltweb silk to lash our raised walkways before the roots shift again.',
      done:['Golden thread, useful for once. I will lash the spans so a loose root cannot take the whole crossing with it.','A flexible cord gives before it breaks. These spans will bend for the next traveler instead of dropping them.'],
      type:'collect',mob:'giltweb',n:8,lvl:47,req:'hc2'},
    {id:'hc6',name:'A Path Under the Canopy',giver:['Trailwarden Aven','Rootscout Neral'],
      text:'Giltweb nests have closed the path beyond our new walkways. Thin the canopy spiders so the readers can reach the ring of wardens without climbing alone.',
      done:['The readers have a path and a returning escort. I will keep the crossing watched while they work.','You opened room beneath the webs. Let the readers pass together; a story is no help if its teller cannot come home.'],
      type:'kill',mob:'giltweb',n:14,lvl:48,req:'hc5'},
    {id:'hc7',name:'Wardens of the Vacant Ring',giver:['Canopy Reader Ilyen','Barklistener Sova'],
      text:'The Hollowroot Wardens are corrupted treants, shaped like guards around a seat no one occupies. Clear a way through their outer ring so we can read what their bark encloses.',
      done:['They guard the shape of an office with no one in it. I will record the carving before another root covers the words.','The trunks reach inward as though someone must sit there. I hear hunger for an answer, not the name of a ruler.'],
      type:'kill',mob:'hollowroot',n:14,lvl:49,req:'hc4'},
    {id:'hc8',name:'A Seat for No One',giver:['Canopy Reader Ilyen','Barklistener Sova'],
      text:'Bring the Empty Seat carvings caught in the wardens. The Wayfolk crowned no one after the Sundering; these fragments may show how an absence became the center of a growing wood.',
      done:['The record leaves the throne empty. The forest has grown around that refusal until its roots try to crown anything they catch.','No crowned successor, only room left waiting. The wood tries to fill it with beast, branch or traveler; waiting has become a hunger.'],
      type:'collect',mob:'hollowroot',n:8,lvl:49,req:'hc7'},
    {id:'hc9',name:'The Ashwing Hoard',giver:['Trailwarden Aven','Rootscout Neral'],
      text:'Ashwing drakes nest above the empty seat and drive scouts from its approaches. They treat the throne as their hoard. Push back the lesser drakes without mistaking them for the wood itself.',
      done:['The scouts can approach again. A drake guarding a hoard is a danger we know; the hungry roots remain a different problem.','The Ashwing defend what they claim. Their claws did not carve the first seat, and clearing them does not answer the forest.'],
      type:'kill',mob:'ashwing',n:14,lvl:50,req:'hc8'},
    {id:'hc10',name:'Scales on the Seat',giver:['Canopy Reader Ilyen','Barklistener Sova'],
      text:'Gather the hoard scales carried by the Ashwing. Scouts hear the name Seraveth deeper in the Crown; compare their signs here before we follow a rumor into the heart.',
      done:['Their claim points inward, toward Seraveth, the Ashwing matriarch. We have not reached her throne; do not write a meeting we have not had.','Seraveth is the name the scouts brought back. The scales mark an Ashwing claim, not a road to her won already. The heart still waits.'],
      type:'collect',mob:'ashwing',n:8,lvl:51,req:'hc9'},
    {id:'hc11',name:'The Bough Sentinel',giver:['Trailwarden Aven','Rootscout Neral'],
      text:'Veskareth, an old Ashwing drake, watches the last outer crossing from its bough. Bring allies to end its hunt, or earn its companionship if you can. The path below must serve living travelers.',
      done:['The sentinel no longer hunts the crossing. Thank your companions; I want everyone who follows this road to have a way back.','Veskareth has left its watch over our footsteps. Whatever bond you earned, the next traveler can pass beneath that bough.'],
      type:'kill',mob:'veskareth',n:1,lvl:52,elite:true,req:'hc10'},
    {id:'hc12',name:'Under the Claiming Roots',giver:['Canopy Reader Ilyen','Barklistener Sova'],
      text:"Clear the Hollowroot Wardens from the descent and gather four companions for Rootrot Hollow. The root passages guard the outer approach; beyond them lies the Crown's heart and Seraveth's claimed throne, still ahead of us.",
      done:["The descent to Rootrot Hollow is ready. Face its keepers together; clearing the surface is not a dungeon victory, and Seraveth still waits in the Crown's heart.","Take four companions beneath the roots. Rootrot Hollow holds the next crossing, not Seraveth herself. Keep a return road for those who follow you inward."],
      type:'kill',mob:'hollowroot',n:14,lvl:52,req:'hc11'},
  ],
  crownheart:[
    {id:'ch1',name:'The Watch Moves Inward',giver:['Trailwarden Aven','Rootscout Neral'],
      text:'Thornmantle cannot watch a road hidden behind the older trees. Clear the Crownfang wolves from the inward trail so both watches can raise Heartwatch Camp.',
      done:['The watch has a path to Heartwatch and a path back. I will count returning people before I count tents.','We can move our fire inward without abandoning the late arrivals. Keep their footsteps in mind when you mark the trail.'],
      type:'kill',mob:'crownfang',n:14,lvl:52},
    {id:'ch2',name:'Linings Under Old Branches',giver:['Campwright Tessa','Cordmender Ghor'],
      text:'The deeper canopy holds damp against every shoulder. Gather Crownfang pelts; the shared watch needs its winter linings mended again.',
      done:['These linings will keep the inward watch warm. A second camp does not give us a second set of shoulders.','Good hide under the crown-bites. I will stitch for both watches; no knot asks which banner its wearer follows.'],
      type:'collect',mob:'crownfang',n:8,lvl:52,req:'ch1'},
    {id:'ch3',name:'A Cart Can Turn Around',giver:['Trailwarden Aven','Rootscout Neral'],
      text:'Hearttusk boars have rooted through the only place a supply cart can turn. Clear the bend before anyone mistakes a way in for a road home.',
      done:['The cart can turn without unloading its tired driver. Our road will carry supplies in both directions.','A trail with no turning place is a trap for the last traveler. You have left them a choice.'],
      type:'kill',mob:'hearttusk',n:14,lvl:53,req:'ch1'},
    {id:'ch4',name:'Braces for Heartwatch',giver:['Campwright Tessa','Cordmender Ghor'],
      text:'Heartwood tusks brace a platform without sinking into the moving roots. Bring eight from the boars so Heartwatch can stand above the wood rather than wound it.',
      done:['I have fitted the braces around the living roots. If they shift, we can move a platform instead of losing a scout.','Eight sound forks. A good camp bends when the ground changes; a proud one falls.'],
      type:'collect',mob:'hearttusk',n:8,lvl:53,req:'ch3'},
    {id:'ch5',name:'A Span Above the Hunger',giver:['Campwright Tessa','Cordmender Ghor'],
      text:'Veilweft cord can hold the inward spans while hungry roots search below. Gather eight bundles for the crossings used by both watches.',
      done:['The spans hold, and I have left a handrail for anyone returning hurt. Useful gold belongs in a crossing, not a crown.','These cords will hold a traveler who stumbles. Tie the last knot where the smallest hand can reach it.'],
      type:'collect',mob:'veilweft',n:8,lvl:54,req:'ch2'},
    {id:'ch6',name:'The Choir Beyond the Webs',giver:['Canopy Reader Ilyen','Barklistener Sova'],
      text:'Veilweft nests curtain the old ring. Clear the spiders so we can hear the rootbound choir without leaving our escort behind.',
      done:['The curtain is open. Their repeated words sound like a request for a ruler; I will record them before deciding what they mean.','I can hear the same hunger through many trunks. Bring a returning escort; the wood has room for every voice it catches.'],
      type:'kill',mob:'veilweft',n:16,lvl:55,req:'ch5'},
    {id:'ch7',name:'Verses That Face Outward',giver:['Canopy Reader Ilyen','Barklistener Sova'],
      text:'The choir-treants carry older verses beneath their new inward chant. Recover the Return-Road verses before roots close over the words.',
      done:['The older lines face outward: shelter, crossing, return. The wood repeats the seat and forgets everyone who must leave it.','These words remember feet walking away together. The choir wants one answer sitting still; the road kept many answers moving.'],
      type:'collect',mob:'choirroot',n:8,lvl:55,req:'ch6'},
    {id:'ch8',name:'The Vault Has a Return Door',giver:['Trailwarden Aven','Rootscout Neral'],
      text:'The Rootbound Choir-Treants bar the descent to the Heartwood Vault. Clear its approach and gather four companions; its keepers are not Seraveth, and no one goes beneath these roots alone.',
      done:['The Heartwood Vault can be approached together. Face its keepers with four companions and keep a lamp at the return door.','The descent is open. Clearing its approach is no dungeon victory; take your companions down and bring them back.'],
      type:'kill',mob:'choirroot',n:16,lvl:56,req:'ch7'},
    {id:'ch9',name:'The Brood Keeps the Claim',giver:['Trailwarden Aven','Rootscout Neral'],
      text:'Ashwing Broodguards drive the watch from every gold-lit branch. Push them from the crossing while the readers compare the matriarch\'s signs.',
      done:['The crossing is watched again. Those guards defend Seraveth\'s claim, but they do not speak for a forest trying to crown anything.','The brood has given us room. A guarded hoard and a hungry wood are two dangers; do not call them one.'],
      type:'kill',mob:'broodguard',n:16,lvl:57,req:'ch8'},
    {id:'ch10',name:'Gold Light on an Occupied Seat',giver:['Canopy Reader Ilyen','Barklistener Sova'],
      text:'Gather Hoard-Sign scales from the gilded elders. Through a break in the canopy scouts glimpsed Seraveth on the Hollow Throne; her voice carries farther than her wings.',
      done:['The scales match her claim. Seraveth sits on the throne, yet the roots still reach for more. An occupied seat has not healed the absence.','We heard the matriarch and saw her shape in the gold light. She has taken the seat as a hoard; the hunger beneath it still pulls inward.'],
      type:'collect',mob:'elderwing',n:8,lvl:58,req:'ch9'},
    {id:'ch11',name:'The Unbound Wing',giver:['Trailwarden Aven','Rootscout Neral'],
      text:'Aurethyn hunts above the last outward branch. Bring allies to end the old drake\'s watch, or earn its companionship if you can. Seraveth waits farther in; this is not her fight.',
      done:['Aurethyn no longer hunts our return crossing. Thank your allies. We can prepare the Hollow Key without pretending the matriarch has fallen.','The unbound wing has left its watch over this branch. Whatever bond you earned, it leaves a way back for the people following us.'],
      type:'kill',mob:'aurethyn',n:1,lvl:60,elite:true,req:'ch10'},
    {id:'ch12',name:'The Hollow Key: Remember the Crossings',giver:['Canopy Reader Ilyen','Barklistener Sova'],
      text:'First clear the Silent Barrows and Rootrot Hollow. Then recover Return-Road verses from the choir-treants: the Hollow Key must remember a crossing kept open, not a seat filled.',
      done:['Your passage through both dungeons gives these verses their witness. A quiet Archivist in a grey coat copied our account, asked whether everyone returned, and offered no story about where they came from.','Both crossings have been walked and faced. The verses belong to the return road; we will not bend their words into a crown.'],
      type:'collect',mob:'choirroot',n:8,lvl:60,req:'ch11',attune:true,needDun:['barrows','rootrot']},
    {id:'ch13',name:'The Hollow Key: Unbind the Claim',giver:['Campwright Tessa','Cordmender Ghor'],
      text:'With the Silent Barrows and Rootrot Hollow cleared, bring Broodward scales for the Key\'s binding. We will fit the witness of those roads to a grip that does not close around a crown.',
      done:['The binding holds without hiding the old words. I have left room for another hand beside yours.','A sound knot, loose enough to open again. The Key must let people pass; it must not keep them for its bearer.'],
      type:'collect',mob:'broodguard',n:8,lvl:60,req:'ch12',attune:true,needDun:['barrows','rootrot']},
    {id:'ch14',name:'The Hollow Key: A Road Past the Throne',giver:['Trailwarden Aven','Rootscout Neral'],
      text:'The Silent Barrows and Rootrot Hollow are behind you. Clear the gilded elders from the last approach so we can carry the finished Hollow Key to the Hollow Throne. Seraveth waits there for a raid, not a lone traveler.',
      done:['Take the Hollow Key. It opens the way to the Hollow Throne; gather ten raiders to face Seraveth. I am not asking who will wear her crown. I am asking who will keep the road for the people coming home.','The Hollow Key is yours. The Hollow Throne lies ahead; bring ten raiders for Seraveth, and leave a return path for everyone. Taking her seat will not be our answer to the wood.'],
      type:'kill',mob:'elderwing',n:18,lvl:60,req:'ch13',attune:true,needDun:['barrows','rootrot']},
  ],
};
