'use strict';
/* Generated by tools/catalogue-export.cjs from Wildbond data. No battle numbers or rules. */
const CreatureCatalogue = Object.freeze({
  "ashskip": {
    "name": "Ashskip",
    "family": "lizard",
    "element": "Ember",
    "color": "#d99154",
    "lore": "It hops between cooling rocks and leaves tiny tail prints in the soft ash."
  },
  "bellmote": {
    "name": "Bellmote",
    "family": "sprite",
    "element": "Radiant",
    "color": "#d9d797",
    "lore": "It rests inside a silent bell and lights the rim when a returning team approaches."
  },
  "blazefang": {
    "name": "Blazefang",
    "family": "wolf",
    "element": "Ember",
    "color": "#e8441e",
    "lore": "Its mane burns brighter the more it trusts its tamer."
  },
  "bloomcourser": {
    "name": "Bloomcourser",
    "family": "horse",
    "element": "Grove",
    "color": "#6d9a49",
    "lore": "Flowers open along its mane where young creatures lean against it during a storm."
  },
  "bogbough": {
    "name": "Bogbough",
    "family": "croc",
    "element": "Grove",
    "color": "#6f8652",
    "lore": "Willow seedlings root in its ridged back; it rests where the bank needs holding together."
  },
  "bogsnap": {
    "name": "Bogsnap",
    "family": "croc",
    "element": "Tide",
    "color": "#4a6a4a",
    "lore": "It waits in still water for hours without moving."
  },
  "boughchorus": {
    "name": "Boughchorus",
    "family": "bird",
    "element": "Grove",
    "color": "#427b54",
    "lore": "In Sunthread Commons, it sings from orchard branches, leaving the first ripe fruit for the smaller birds."
  },
  "breakwatermane": {
    "name": "Breakwatermane",
    "family": "wolf",
    "element": "Tide",
    "color": "#497a9e",
    "lore": "The coast falls silent when this ancient wolf walks the breakers, its mane carrying the rhythm of every tide."
  },
  "briarwatch": {
    "name": "Briarwatch",
    "family": "wolf",
    "element": "Grove",
    "color": "#49734b",
    "lore": "It walks the hedge at dawn, gently carrying lost hatchlings back to their nests."
  },
  "brineskit": {
    "name": "Brineskit",
    "family": "lizard",
    "element": "Tide",
    "color": "#569eaa",
    "lore": "It skims shallow tide pools on its wide toes and shelters beneath empty shells."
  },
  "buoyglint": {
    "name": "Buoyglint",
    "family": "sprite",
    "element": "Radiant",
    "color": "#e8d6a2",
    "lore": "It lights the sheltered side of a mooring post until the last returning team has landed."
  },
  "cairnclasp": {
    "name": "Cairnclasp",
    "family": "lizard",
    "element": "Stone",
    "color": "#a09b88",
    "lore": "It grips a cairn with all four feet and refuses to let a loose stone fall on the trail."
  },
  "cairnhound": {
    "name": "Cairnhound",
    "family": "wolf",
    "element": "Stone",
    "color": "#827b6b",
    "lore": "It keeps Cloudglass Pass's cairns upright through winter, resting against the smallest stones when the wind rises."
  },
  "chartwing": {
    "name": "Chartwing",
    "family": "bird",
    "element": "Gale",
    "color": "#bdd3d5",
    "lore": "It circles a lookout twice when fog closes the usual approach, then waits for the shore signal."
  },
  "chimespark": {
    "name": "Chimespark",
    "family": "sprite",
    "element": "Radiant",
    "color": "#d4c5ed",
    "lore": "Rarely seen outside quiet hollows, it answers distant bells with a single bright note."
  },
  "cindercub": {
    "name": "Cindercub",
    "family": "wolf",
    "element": "Ember",
    "color": "#d8642e",
    "lore": "A wolf pup with smoldering fur. It sleeps curled around warm stones."
  },
  "cinderstitch": {
    "name": "Cinderstitch",
    "family": "spider",
    "element": "Ember",
    "color": "#cc815b",
    "lore": "Beside the Emberfall Highlands' warm vents, it stitches ash into a snug nest. It never evolves: eight careful feet already make all the shelter its family needs."
  },
  "cirrusmane": {
    "name": "Cirrusmane",
    "family": "horse",
    "element": "Gale",
    "color": "#dfe6ec",
    "lore": "Its mane streams like a wisp of high cloud, and it never runs a ridge its herd can't follow."
  },
  "cloudharrier": {
    "name": "Cloudharrier",
    "family": "bird",
    "element": "Gale",
    "color": "#8fa6bd",
    "lore": "It circles above a stranded traveler until someone climbs up to see what it has found."
  },
  "clovercolt": {
    "name": "Clovercolt",
    "family": "horse",
    "element": "Grove",
    "color": "#a5bb63",
    "lore": "It carries loose shelter ties in its mane and waits while slower partners cross the meadow."
  },
  "cragskein": {
    "name": "Cragskein",
    "family": "spider",
    "element": "Stone",
    "color": "#82736d",
    "lore": "Its mineral-dusted webs bridge narrow cracks, giving smaller creatures a safe path across the crags."
  },
  "dawntassel": {
    "name": "Dawntassel",
    "family": "sprite",
    "element": "Radiant",
    "color": "#ffdfa0",
    "lore": "A rare visitor at first light, it leaves a gold glimmer on the knots of a well-mended shelter."
  },
  "dewspinner": {
    "name": "Dewspinner",
    "family": "spider",
    "element": "Tide",
    "color": "#83b8bb",
    "lore": "Its cupped webs collect morning dew; thirsty shore creatures drink before it rebuilds them."
  },
  "draftscale": {
    "name": "Draftscale",
    "family": "lizard",
    "element": "Gale",
    "color": "#7ca4ad",
    "lore": "Above Cloudglass Pass, its broad sail catches the rising air; it circles back whenever a young Saillet falls behind."
  },
  "dripdart": {
    "name": "Dripdart",
    "family": "lizard",
    "element": "Tide",
    "color": "#6f9e9c",
    "lore": "It follows falling drops to shallow pools, then taps the rock to call its neighbors."
  },
  "dunepounce": {
    "name": "Dunepounce",
    "family": "cat",
    "element": "Stone",
    "color": "#c5aa75",
    "lore": "It buries its stone-tipped paws in warm dunes before springing at shadows on the sand."
  },
  "duskcord": {
    "name": "Duskcord",
    "family": "spider",
    "element": "Shade",
    "color": "#76677c",
    "lore": "Its dusk webs catch drifting seeds above the water while leaving a gap for passing wings."
  },
  "duskweaver": {
    "name": "Duskweaver",
    "family": "spider",
    "element": "Shade",
    "color": "#5a4a7a",
    "lore": "It weaves webs only at dusk, and they vanish by morning."
  },
  "elderhorn": {
    "name": "Elderhorn",
    "family": "horse",
    "element": "Grove",
    "color": "#6a8a4a",
    "lore": "The ancient guardian of Thornwood. Few have seen it and fewer have earned its trust."
  },
  "emberling": {
    "name": "Emberling",
    "family": "lizard",
    "element": "Ember",
    "color": "#e06a2a",
    "lore": "It basks on hot rocks and glows faintly at night."
  },
  "fernruff": {
    "name": "Fernruff",
    "family": "wolf",
    "element": "Grove",
    "color": "#719b60",
    "lore": "This fern-maned pup leaves gaps in its den hedge so smaller neighbours can shelter with it."
  },
  "ferrycrest": {
    "name": "Ferrycrest",
    "family": "croc",
    "element": "Tide",
    "color": "#4c8177",
    "lore": "Its broad crest parts a quiet channel through reeds without overturning their nests."
  },
  "flintpup": {
    "name": "Flintpup",
    "family": "wolf",
    "element": "Stone",
    "color": "#aaa18b",
    "lore": "On the Emberfall Highlands' cool scree, it taps loose stones with its paws before leading the pack across."
  },
  "flintroot": {
    "name": "Flintroot",
    "family": "boar",
    "element": "Stone",
    "color": "#9a927a",
    "lore": "It rubs loose stone from the trail with its shoulders before settling down to sleep."
  },
  "foamglint": {
    "name": "Foamglint",
    "family": "sprite",
    "element": "Tide",
    "color": "#a0dfcf",
    "lore": "This elusive fleck of living foam glows only where moonlit waves meet the marsh."
  },
  "fogsail": {
    "name": "Fogsail",
    "family": "lizard",
    "element": "Shade",
    "color": "#918ba9",
    "lore": "It drifts along Cloudglass Pass's fog banks, showing the pale edge of its sail to companions who might lose the path."
  },
  "fogtail": {
    "name": "Fogtail",
    "family": "cat",
    "element": "Gale",
    "color": "#c9d2d8",
    "lore": "When the cloud rolls in it vanishes completely, except for the tip of its tail."
  },
  "fordfoal": {
    "name": "Fordfoal",
    "family": "horse",
    "element": "Tide",
    "color": "#88ada5",
    "lore": "At Stillreed Basin's shallow crossings, it tests the riverbed before anyone follows. It never evolves: a small, sure-footed body is just right for the reed paths."
  },
  "galefoal": {
    "name": "Galefoal",
    "family": "horse",
    "element": "Gale",
    "color": "#cfd8e0",
    "lore": "A wild foal that runs with the wind. Born to race."
  },
  "glassbill": {
    "name": "Glassbill",
    "family": "bird",
    "element": "Gale",
    "color": "#a6c9bc",
    "lore": "Rarely seen among the reeds, it taps clear notes on rain-filled shells before dawn."
  },
  "glimmerwing": {
    "name": "Glimmerwing",
    "family": "bird",
    "element": "Gale",
    "color": "#9fd6f0",
    "lore": "Its feathers catch the light like glass."
  },
  "glowmote": {
    "name": "Glowmote",
    "family": "sprite",
    "element": "Radiant",
    "color": "#f4cb78",
    "lore": "This seldom-seen spark drifts through the steam, lighting the way home when mist covers the highlands."
  },
  "gnawhound": {
    "name": "Gnawhound",
    "family": "hyena",
    "element": "Shade",
    "color": "#6a5a4a",
    "lore": "Packs of them laugh at night to frighten travelers."
  },
  "gritbeak": {
    "name": "Gritbeak",
    "family": "bird",
    "element": "Stone",
    "color": "#7d776e",
    "lore": "It cracks seeds on the rocks with its stone-hard beak, and the noise carries a long way in fog."
  },
  "gustreed": {
    "name": "Gustreed",
    "family": "bird",
    "element": "Gale",
    "color": "#d0bd78",
    "lore": "It whistles between reed stems, then falls quiet when a tired ferry reaches the bank."
  },
  "hearthcrown": {
    "name": "Hearthcrown",
    "family": "horse",
    "element": "Ember",
    "color": "#a66e4c",
    "lore": "The guardian of Emberfall warms frozen springs with its ember-lit antlers so every creature can drink."
  },
  "hearthlaugh": {
    "name": "Hearthlaugh",
    "family": "hyena",
    "element": "Radiant",
    "color": "#d8bb7c",
    "lore": "It never evolves; its warm chuckle steadies frightened companions, and its light grows with practice."
  },
  "hearthrunner": {
    "name": "Hearthrunner",
    "family": "wolf",
    "element": "Ember",
    "color": "#cb7445",
    "lore": "It warms cold paws beneath the meeting benches, then trots out to carry a message."
  },
  "hedgelark": {
    "name": "Hedgelark",
    "family": "bird",
    "element": "Grove",
    "color": "#688c51",
    "lore": "Thornwood's hedges shelter its leafy nests; its dawn call waits until every nestling answers."
  },
  "hemglow": {
    "name": "Hemglow",
    "family": "sprite",
    "element": "Radiant",
    "color": "#f3d184",
    "lore": "Its small light marks the edge of a shelter cloth so tired travelers can find a place beneath it."
  },
  "hushmane": {
    "name": "Hushmane",
    "family": "hyena",
    "element": "Shade",
    "color": "#66597c",
    "lore": "Its soft call carries around stone bends without startling the creatures sheltering there."
  },
  "hushpup": {
    "name": "Hushpup",
    "family": "hyena",
    "element": "Shade",
    "color": "#81729b",
    "lore": "It stops at a fork until the returning echo matches the footfalls of its friends."
  },
  "inkwhisk": {
    "name": "Inkwhisk",
    "family": "cat",
    "element": "Shade",
    "color": "#777d98",
    "lore": "It rests beside corrected charts and follows the fresh ink when an old shortcut becomes unsafe."
  },
  "isleglimmer": {
    "name": "Isleglimmer",
    "family": "sprite",
    "element": "Radiant",
    "color": "#cde5e9",
    "lore": "Rarely seen beyond the lookouts, it hovers over a dry foothold before vanishing into sea fog."
  },
  "keeljaw": {
    "name": "Keeljaw",
    "family": "croc",
    "element": "Tide",
    "color": "#758f89",
    "lore": "It nudges drifting planks into the harbor shallows and leaves them where smaller paws can climb."
  },
  "kilnchirp": {
    "name": "Kilnchirp",
    "family": "bird",
    "element": "Ember",
    "color": "#cb7752",
    "lore": "It dries its clay-lined nest beside warm vents, singing when the mud is ready for chicks."
  },
  "kilntusk": {
    "name": "Kilntusk",
    "family": "boar",
    "element": "Ember",
    "color": "#965338",
    "lore": "Its glowing tusks loosen hardened lava so its herd can root for tender shoots beneath the stone."
  },
  "kiteskirl": {
    "name": "Kiteskirl",
    "family": "bird",
    "element": "Gale",
    "color": "#adc9da",
    "lore": "It rides the sea breeze without flapping and whistles whenever a storm approaches."
  },
  "lanterncrest": {
    "name": "Lanterncrest",
    "family": "bird",
    "element": "Radiant",
    "color": "#f6d77a",
    "lore": "The guardian of Cloudglass Pass. Its crest burns like a lamp through the thickest cloud, lighting the way to shelter."
  },
  "lanternwisp": {
    "name": "Lanternwisp",
    "family": "sprite",
    "element": "Radiant",
    "color": "#ffe9a8",
    "lore": "Rarely seen. It glows brightest beside the shelters, as if it knows which doors are open."
  },
  "laughrill": {
    "name": "Laughrill",
    "family": "hyena",
    "element": "Tide",
    "color": "#78a7b2",
    "lore": "In Stillreed Basin, its bubbling chuckle carries over the pools. It never evolves; the same familiar voice guides its family home through every flood."
  },
  "ledgewhisk": {
    "name": "Ledgewhisk",
    "family": "cat",
    "element": "Stone",
    "color": "#b0a698",
    "lore": "Its whiskers brush the wall while its paws find the broadest ledge in the dark."
  },
  "meadowmantle": {
    "name": "Meadowmantle",
    "family": "boar",
    "element": "Grove",
    "color": "#668950",
    "lore": "The guardian rests across the windward edge of nursery ground, keeping tender roots and sleeping young sheltered."
  },
  "mistfinch": {
    "name": "Mistfinch",
    "family": "bird",
    "element": "Gale",
    "color": "#b9c8d6",
    "lore": "It sings only when the cloud is thick, so lost walkers can follow the sound down to a ledge."
  },
  "moorweft": {
    "name": "Moorweft",
    "family": "spider",
    "element": "Stone",
    "color": "#aba698",
    "lore": "Its stout silk catches loose pebbles above paths without hiding the marks travelers follow."
  },
  "mosshog": {
    "name": "Mosshog",
    "family": "boar",
    "element": "Grove",
    "color": "#5d9a3e",
    "lore": "Moss grows on its back. Birds nest in it, and it lets them."
  },
  "orchardroot": {
    "name": "Orchardroot",
    "family": "boar",
    "element": "Grove",
    "color": "#7d9a52",
    "lore": "It turns fallen orchard fruit into soft soil and leaves the growing roots undisturbed."
  },
  "pallweaver": {
    "name": "Pallweaver",
    "family": "spider",
    "element": "Stone",
    "color": "#9a9590",
    "lore": "Its silk bridges the narrow cracks in the pass, and small creatures cross on them every morning."
  },
  "pebblepaw": {
    "name": "Pebblepaw",
    "family": "cat",
    "element": "Stone",
    "color": "#9a8a74",
    "lore": "It sharpens its claws on granite and naps in the sun."
  },
  "pennantlark": {
    "name": "Pennantlark",
    "family": "bird",
    "element": "Radiant",
    "color": "#ebbe67",
    "lore": "It flashes its wings above a gathering when the last returning team reaches the hall."
  },
  "poolkit": {
    "name": "Poolkit",
    "family": "cat",
    "element": "Tide",
    "color": "#80b1b8",
    "lore": "It pats rain rings in shallow pools, then watches the ripples reach the reeds."
  },
  "reedlet": {
    "name": "Reedlet",
    "family": "lizard",
    "element": "Tide",
    "color": "#759b89",
    "lore": "It balances on floating reeds and nudges loose ferry ropes toward the landing."
  },
  "reedtusk": {
    "name": "Reedtusk",
    "family": "boar",
    "element": "Grove",
    "color": "#829956",
    "lore": "It combs the marsh with curved tusks, leaving narrow trails that fill with fresh reeds."
  },
  "ribbonstride": {
    "name": "Ribbonstride",
    "family": "horse",
    "element": "Gale",
    "color": "#b7cfb8",
    "lore": "It runs ahead of sudden gusts and brings wind-loosened ribbons back to their posts."
  },
  "ridgewarden": {
    "name": "Ridgewarden",
    "family": "wolf",
    "element": "Stone",
    "color": "#656b70",
    "lore": "Cloudglass Pass's oldest ridge packs follow its patient steps; it returns for the last pup before leaving a ledge."
  },
  "rilllynx": {
    "name": "Rilllynx",
    "family": "cat",
    "element": "Tide",
    "color": "#488d9e",
    "lore": "Its whiskers read currents beneath the bank; it crosses streams without disturbing a nest."
  },
  "rillwhisk": {
    "name": "Rillwhisk",
    "family": "lizard",
    "element": "Tide",
    "color": "#8db7aa",
    "lore": "Its whiskers tremble before the channel rises, giving boat families time to loosen their lines."
  },
  "ripplet": {
    "name": "Ripplet",
    "family": "lizard",
    "element": "Tide",
    "color": "#3a8fd8",
    "lore": "A curious river lizard that blows bubbles when it is happy."
  },
  "saillet": {
    "name": "Saillet",
    "family": "lizard",
    "element": "Gale",
    "color": "#b0c2b9",
    "lore": "On Saltmarsh Coast, it lifts its little back sail to dry after rain, leaning into whichever breeze smells of home."
  },
  "screegrin": {
    "name": "Screegrin",
    "family": "hyena",
    "element": "Stone",
    "color": "#8c7760",
    "lore": "Its cheerful chatter carries down the slopes as it gathers smooth stones for its den."
  },
  "seedpip": {
    "name": "Seedpip",
    "family": "bird",
    "element": "Grove",
    "color": "#9ca86a",
    "lore": "In Thornwood, it tucks fallen seeds into fence cracks and checks them again after rain."
  },
  "shalecat": {
    "name": "Shalecat",
    "family": "cat",
    "element": "Stone",
    "color": "#8e8a86",
    "lore": "It naps on loose scree and knows, before anyone, which stones are about to slide."
  },
  "shoalcrest": {
    "name": "Shoalcrest",
    "family": "croc",
    "element": "Tide",
    "color": "#307e96",
    "lore": "Its ridged back parts the surf into calm channels where smaller creatures can cross."
  },
  "shoalpup": {
    "name": "Shoalpup",
    "family": "wolf",
    "element": "Tide",
    "color": "#8cabb1",
    "lore": "It waits at the tideline until every returning paw has reached dry sand."
  },
  "siltjaw": {
    "name": "Siltjaw",
    "family": "croc",
    "element": "Tide",
    "color": "#7c8970",
    "lore": "It rests under grey-green water with only its mossy nose above the surface."
  },
  "slaglet": {
    "name": "Slaglet",
    "family": "boar",
    "element": "Ember",
    "color": "#b77748",
    "lore": "It rolls in warm volcanic dust until its coat forms a snug crust that keeps out the mountain chill."
  },
  "slatehoof": {
    "name": "Slatehoof",
    "family": "horse",
    "element": "Stone",
    "color": "#89949b",
    "lore": "Its broad hooves test each ledge before it lets the rest of the herd follow."
  },
  "soundhowl": {
    "name": "Soundhowl",
    "family": "wolf",
    "element": "Tide",
    "color": "#5e8d9c",
    "lore": "Its low call passes along the shore, letting separated teams find the same sheltered inlet."
  },
  "spindriftfoal": {
    "name": "Spindriftfoal",
    "family": "horse",
    "element": "Gale",
    "color": "#d2d9cb",
    "lore": "It races along the waterline, scattering ribbons of sea spray with every stride."
  },
  "stillwake": {
    "name": "Stillwake",
    "family": "croc",
    "element": "Tide",
    "color": "#638d7c",
    "lore": "Stillreed Basin's guardian shelters small creatures in its calm wake as flooded channels carry them across."
  },
  "stormfrill": {
    "name": "Stormfrill",
    "family": "lizard",
    "element": "Gale",
    "color": "#5f7f9b",
    "lore": "Cloudglass Pass's storm winds bend its great frill, but it folds the sail to shelter its companions from the worst gusts."
  },
  "sunfrill": {
    "name": "Sunfrill",
    "family": "lizard",
    "element": "Radiant",
    "color": "#d3b66a",
    "lore": "Sunthread Commons's fence rails are its sunny resting places; its bright sail shades the little creatures gathered underneath."
  },
  "sunspark": {
    "name": "Sunspark",
    "family": "sprite",
    "element": "Radiant",
    "color": "#ffe36a",
    "lore": "A rare spark of living light. Seeing one is said to be good luck."
  },
  "thermwing": {
    "name": "Thermwing",
    "family": "bird",
    "element": "Gale",
    "color": "#baa9a0",
    "lore": "It circles on rising warmth, calling out sheltered ledges to the creatures climbing below."
  },
  "thornback": {
    "name": "Thornback",
    "family": "boar",
    "element": "Grove",
    "color": "#3f7a2a",
    "lore": "Its thorns can split a fallen log. It guards its herd fiercely."
  },
  "tidewyrm": {
    "name": "Tidewyrm",
    "family": "croc",
    "element": "Tide",
    "color": "#1f6fbf",
    "lore": "It rides the river currents and can call up a wave at will."
  },
  "tilthtusk": {
    "name": "Tilthtusk",
    "family": "boar",
    "element": "Grove",
    "color": "#938353",
    "lore": "It loosens worn soil beside shared paths, carefully circling the marked nursery beds."
  },
  "tumbletusk": {
    "name": "Tumbletusk",
    "family": "boar",
    "element": "Gale",
    "color": "#b5bbc5",
    "lore": "It rolls into a headwind, scattering seeds through the high meadows with every tumble."
  },
  "umbrelace": {
    "name": "Umbrelace",
    "family": "spider",
    "element": "Shade",
    "color": "#726b84",
    "lore": "It hangs silk beside unsafe ledges, leaving the familiar passage open."
  },
  "undertone": {
    "name": "Undertone",
    "family": "hyena",
    "element": "Shade",
    "color": "#504765",
    "lore": "Its low call passes through winding stone to guide separated groups back to one another."
  },
  "veilmote": {
    "name": "Veilmote",
    "family": "sprite",
    "element": "Shade",
    "color": "#85779f",
    "lore": "A solitary mote folds deep shade around abandoned nests, keeping their last warmth through the night."
  },
  "ventwhisk": {
    "name": "Ventwhisk",
    "family": "cat",
    "element": "Ember",
    "color": "#b55e4a",
    "lore": "It curls beside warm vents and fans little clouds of steam with its copper-coloured tail."
  },
  "watchlight": {
    "name": "Watchlight",
    "family": "sprite",
    "element": "Radiant",
    "color": "#f4e0a5",
    "lore": "Farwatch Reach's guardian marks a safe approach through fog, waiting for travelers to answer before moving on."
  },
  "wrackjaw": {
    "name": "Wrackjaw",
    "family": "hyena",
    "element": "Stone",
    "color": "#94877b",
    "lore": "Its rattling laugh echoes through driftwood piles as it cracks shellfish with pebble-hard jaws."
  }
});
