'use strict';
// Run from any folder: node tools/catalogue-export.cjs. Data snapshot, never combat rules.
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'games/wildbond/js/00-data.js'),'utf8');
const species=vm.runInNewContext(source+'\nSPECIES',{},{timeout:1000});
const rows=Object.fromEntries(Object.entries(species).sort(([a],[b])=>a.localeCompare(b)).map(([id,s])=>[id,{name:s.name,family:s.fam,element:s.el,color:s.col,lore:s.dex}]));
const text="'use strict';\n/* Generated by tools/catalogue-export.cjs from Wildbond data. No battle numbers or rules. */\nconst CreatureCatalogue = Object.freeze("+JSON.stringify(rows,null,2)+");\n";
const target=path.join(root,'shared/catalogue.js');
if(process.argv.includes('--check')){if(fs.readFileSync(target,'utf8').replace(/\r\n/g,'\n')!==text)throw Error('Catalogue is stale; run node tools/catalogue-export.cjs');console.log('PASS: '+Object.keys(rows).length+' catalogue entries match Wildbond.');}
else{fs.writeFileSync(target,text);console.log('Exported '+Object.keys(rows).length+' catalogue entries.');}